use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::{Path, PathBuf};

const GENERATED_BY: &str = "crawclaw-runtime emit-bundled-provider-auth-env-vars";
const RUNTIME_CONSTANTS_GENERATED_BY: &str = "crawclaw-runtime emit-provider-runtime-constants";
const BUNDLED_CAPABILITY_METADATA_GENERATED_BY: &str =
    "crawclaw-runtime emit-bundled-capability-metadata";

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedModuleWriteResult {
    pub changed: bool,
    pub wrote: bool,
    pub output_path: PathBuf,
}

#[derive(Clone, Debug, Default, PartialEq, Eq)]
struct BundledCapabilityMetadataEntryBuilder {
    provider_ids: BTreeSet<String>,
    web_fetch_provider_ids: BTreeSet<String>,
    web_search_provider_ids: BTreeSet<String>,
    tool_names: BTreeSet<String>,
}

#[derive(Clone, Debug, PartialEq, Eq)]
struct BundledCapabilityMetadataEntry {
    plugin_id: String,
    provider_ids: Vec<String>,
    web_fetch_provider_ids: Vec<String>,
    web_search_provider_ids: Vec<String>,
    tool_names: Vec<String>,
}

#[derive(Clone, Debug, PartialEq, Eq)]
struct BundledNativeProviderInvocation {
    plugin_id: String,
    operation: String,
}

#[derive(Clone, Debug, PartialEq, Eq)]
struct BundledNativeWebProviderMetadataEntry {
    plugin_id: String,
    id: String,
    label: String,
    invocation: BundledNativeProviderInvocation,
}

#[derive(Clone, Debug, PartialEq, Eq)]
struct BundledNativeSpeechProviderMetadataEntry {
    plugin_id: String,
    id: String,
    label: String,
    voices: Vec<String>,
    synthesize: BundledNativeProviderInvocation,
}

impl BundledCapabilityMetadataEntry {
    fn is_empty(&self) -> bool {
        self.provider_ids.is_empty()
            && self.web_fetch_provider_ids.is_empty()
            && self.web_search_provider_ids.is_empty()
            && self.tool_names.is_empty()
    }
}

impl BundledCapabilityMetadataEntryBuilder {
    fn into_entry(self, plugin_id: String) -> BundledCapabilityMetadataEntry {
        BundledCapabilityMetadataEntry {
            plugin_id,
            provider_ids: self.provider_ids.into_iter().collect(),
            web_fetch_provider_ids: self.web_fetch_provider_ids.into_iter().collect(),
            web_search_provider_ids: self.web_search_provider_ids.into_iter().collect(),
            tool_names: self.tool_names.into_iter().collect(),
        }
    }
}

pub fn render_bundled_provider_auth_env_var_module() -> String {
    let mut entries = crawclaw_providers::bundled_provider_auth_env_vars();
    entries.sort_by(|left, right| left.provider.cmp(right.provider));
    let rendered_entries = entries
        .iter()
        .map(|entry| {
            let rendered_key = if is_javascript_identifier(entry.provider) {
                entry.provider.to_string()
            } else {
                serde_json::to_string(entry.provider).expect("provider id encodes as JSON")
            };
            let rendered_env_vars = entry
                .env_vars
                .iter()
                .map(|value| serde_json::to_string(value).expect("env var encodes as JSON"))
                .collect::<Vec<_>>()
                .join(", ");
            format!("  {rendered_key}: [{rendered_env_vars}],")
        })
        .collect::<Vec<_>>()
        .join("\n");
    format!(
        "// Auto-generated by {GENERATED_BY}. Do not edit directly.\n\nexport const BUNDLED_PROVIDER_AUTH_ENV_VAR_CANDIDATES = {{\n{rendered_entries}\n}} as const satisfies Record<string, readonly string[]>;\n"
    )
}

pub fn write_bundled_provider_auth_env_var_module(
    output_path: impl AsRef<Path>,
    check: bool,
) -> Result<GeneratedModuleWriteResult, String> {
    let output_path = output_path.as_ref().to_path_buf();
    let next = render_bundled_provider_auth_env_var_module();
    let current = match fs::read_to_string(&output_path) {
        Ok(value) => Some(value),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => None,
        Err(error) => return Err(format!("failed to read {}: {error}", output_path.display())),
    };
    let changed = current.as_deref() != Some(next.as_str());
    if check {
        return Ok(GeneratedModuleWriteResult {
            changed,
            wrote: false,
            output_path,
        });
    }
    if changed {
        if let Some(parent) = output_path.parent() {
            fs::create_dir_all(parent)
                .map_err(|error| format!("failed to create {}: {error}", parent.display()))?;
        }
        fs::write(&output_path, next)
            .map_err(|error| format!("failed to write {}: {error}", output_path.display()))?;
    }
    Ok(GeneratedModuleWriteResult {
        changed,
        wrote: changed,
        output_path,
    })
}

pub fn render_bundled_capability_metadata_module() -> String {
    let (snapshots, legacy_aliases, auto_enable_provider_plugins) =
        bundled_capability_metadata_payload();
    let rendered_snapshots = render_bundled_capability_snapshots(&snapshots);
    let rendered_legacy_aliases = render_string_record(&legacy_aliases);
    let rendered_auto_enable_provider_plugins = render_string_record(&auto_enable_provider_plugins);
    let native_metadata = bundled_native_provider_metadata_payload();
    let rendered_native_web_search_providers =
        render_bundled_native_web_provider_metadata(&native_metadata.web_search_providers);
    let rendered_native_web_fetch_providers =
        render_bundled_native_web_provider_metadata(&native_metadata.web_fetch_providers);
    let rendered_native_speech_providers =
        render_bundled_native_speech_provider_metadata(&native_metadata.speech_providers);
    format!(
        r#"// Auto-generated by {BUNDLED_CAPABILITY_METADATA_GENERATED_BY}. Do not edit directly.

export type BundledPluginContractSnapshot = {{
  pluginId: string;
  providerIds: readonly string[];
  webFetchProviderIds: readonly string[];
  webSearchProviderIds: readonly string[];
  toolNames: readonly string[];
}};

export type BundledNativeProviderInvocation = {{
  pluginId: string;
  operation: string;
}};

export type BundledNativeWebProviderMetadata = {{
  pluginId: string;
  id: string;
  label: string;
  invocation: BundledNativeProviderInvocation;
}};

export type BundledNativeSpeechProviderMetadata = {{
  pluginId: string;
  id: string;
  label: string;
  voices: readonly string[];
  synthesize: BundledNativeProviderInvocation;
}};

export const BUNDLED_PLUGIN_CONTRACT_SNAPSHOTS = {rendered_snapshots} as const satisfies readonly BundledPluginContractSnapshot[];

export const BUNDLED_NATIVE_WEB_SEARCH_PROVIDERS = {rendered_native_web_search_providers} as const satisfies readonly BundledNativeWebProviderMetadata[];

export const BUNDLED_NATIVE_WEB_FETCH_PROVIDERS = {rendered_native_web_fetch_providers} as const satisfies readonly BundledNativeWebProviderMetadata[];

export const BUNDLED_NATIVE_SPEECH_PROVIDERS = {rendered_native_speech_providers} as const satisfies readonly BundledNativeSpeechProviderMetadata[];

export const BUNDLED_LEGACY_PLUGIN_ID_ALIASES = {rendered_legacy_aliases} as const satisfies Readonly<Record<string, string>>;

export const BUNDLED_AUTO_ENABLE_PROVIDER_PLUGIN_IDS = {rendered_auto_enable_provider_plugins} as const satisfies Readonly<Record<string, string>>;
"#
    )
}

pub fn write_bundled_capability_metadata_module(
    output_path: impl AsRef<Path>,
    check: bool,
) -> Result<GeneratedModuleWriteResult, String> {
    let output_path = output_path.as_ref().to_path_buf();
    let next = render_bundled_capability_metadata_module();
    let current = match fs::read_to_string(&output_path) {
        Ok(value) => Some(value),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => None,
        Err(error) => return Err(format!("failed to read {}: {error}", output_path.display())),
    };
    let changed = current.as_deref() != Some(next.as_str());
    if check {
        return Ok(GeneratedModuleWriteResult {
            changed,
            wrote: false,
            output_path,
        });
    }
    if changed {
        if let Some(parent) = output_path.parent() {
            fs::create_dir_all(parent)
                .map_err(|error| format!("failed to create {}: {error}", parent.display()))?;
        }
        fs::write(&output_path, next)
            .map_err(|error| format!("failed to write {}: {error}", output_path.display()))?;
    }
    Ok(GeneratedModuleWriteResult {
        changed,
        wrote: changed,
        output_path,
    })
}

pub fn render_provider_runtime_constants_module() -> String {
    format!(
        r#"// Auto-generated by {RUNTIME_CONSTANTS_GENERATED_BY}. Do not edit directly.

export const CLAUDE_CLI_BACKEND_ID = {claude_cli_backend_id};
export const AGENT_DEFAULT_PROVIDER = {agent_default_provider};
export const AGENT_DEFAULT_MODEL = {agent_default_model};
export const AGENT_DEFAULT_CONTEXT_TOKENS = {agent_default_context_tokens};
export const AGENT_DEFAULT_MODEL_ALIASES = {agent_default_model_aliases} as const satisfies Readonly<Record<string, string>>;
export const DEFAULT_CLAUDE_CLI_MODEL = {default_claude_cli_model};
export const ANTHROPIC_VERTEX_DEFAULT_REGION = {anthropic_vertex_default_region};
export const ANTHROPIC_VERTEX_CREDENTIALS_MARKER = {anthropic_vertex_credentials_marker};
export const OLLAMA_DEFAULT_BASE_URL = {ollama_default_base_url};
export const OLLAMA_DEFAULT_CONTEXT_WINDOW = {ollama_default_context_window};
export const OLLAMA_DEFAULT_MAX_TOKENS = {ollama_default_max_tokens};
export const OLLAMA_DEFAULT_MODEL = {ollama_default_model};
export const OLLAMA_DEFAULT_EMBEDDING_MODEL = {ollama_default_embedding_model};
export const OPENAI_DEFAULT_MODEL = {openai_default_model};
export const OPENAI_CODEX_DEFAULT_MODEL = {openai_codex_default_model};
export const OPENAI_DEFAULT_IMAGE_MODEL = {openai_default_image_model};
export const OPENAI_DEFAULT_AUDIO_TRANSCRIPTION_MODEL = {openai_default_audio_transcription_model};
export const OPENAI_DEFAULT_EMBEDDING_MODEL = {openai_default_embedding_model};
export const GOOGLE_GEMINI_DEFAULT_MODEL = {google_gemini_default_model};
export const OPENCODE_GO_DEFAULT_MODEL_REF = {opencode_go_default_model_ref};
export const OPENCODE_ZEN_DEFAULT_MODEL = {opencode_zen_default_model};
export const LEGACY_OPENCODE_ZEN_DEFAULT_MODELS = {legacy_opencode_zen_default_models} as const;
"#,
        claude_cli_backend_id = json_string(crawclaw_providers::CLAUDE_CLI_BACKEND_ID),
        agent_default_provider = json_string(crawclaw_providers::AGENT_DEFAULT_PROVIDER),
        agent_default_model = json_string(crawclaw_providers::AGENT_DEFAULT_MODEL),
        agent_default_context_tokens = crawclaw_providers::AGENT_DEFAULT_CONTEXT_TOKENS,
        agent_default_model_aliases =
            render_static_string_record(crawclaw_providers::AGENT_DEFAULT_MODEL_ALIASES),
        default_claude_cli_model = json_string(crawclaw_providers::DEFAULT_CLAUDE_CLI_MODEL),
        anthropic_vertex_default_region =
            json_string(crawclaw_providers::ANTHROPIC_VERTEX_DEFAULT_REGION),
        anthropic_vertex_credentials_marker =
            json_string(crawclaw_providers::ANTHROPIC_VERTEX_CREDENTIALS_MARKER),
        ollama_default_base_url = json_string(crawclaw_providers::OLLAMA_DEFAULT_BASE_URL),
        ollama_default_context_window = crawclaw_providers::OLLAMA_DEFAULT_CONTEXT_WINDOW,
        ollama_default_max_tokens = crawclaw_providers::OLLAMA_DEFAULT_MAX_TOKENS,
        ollama_default_model = json_string(crawclaw_providers::OLLAMA_DEFAULT_MODEL),
        ollama_default_embedding_model =
            json_string(crawclaw_providers::OLLAMA_DEFAULT_EMBEDDING_MODEL),
        openai_default_model = json_string(crawclaw_providers::OPENAI_DEFAULT_MODEL_REF),
        openai_codex_default_model =
            json_string(crawclaw_providers::OPENAI_CODEX_DEFAULT_MODEL_REF),
        openai_default_image_model = json_string(crawclaw_providers::OPENAI_DEFAULT_IMAGE_MODEL),
        openai_default_audio_transcription_model =
            json_string(crawclaw_providers::OPENAI_DEFAULT_AUDIO_TRANSCRIPTION_MODEL),
        openai_default_embedding_model =
            json_string(crawclaw_providers::OPENAI_DEFAULT_EMBEDDING_MODEL),
        google_gemini_default_model =
            json_string(crawclaw_providers::GOOGLE_GEMINI_DEFAULT_MODEL_REF),
        opencode_go_default_model_ref =
            json_string(crawclaw_providers::OPENCODE_GO_DEFAULT_MODEL_REF),
        opencode_zen_default_model =
            json_string(crawclaw_providers::OPENCODE_ZEN_DEFAULT_MODEL_REF),
        legacy_opencode_zen_default_models =
            render_static_string_array(crawclaw_providers::LEGACY_OPENCODE_ZEN_DEFAULT_MODEL_REFS),
    )
}

pub fn write_provider_runtime_constants_module(
    output_path: impl AsRef<Path>,
    check: bool,
) -> Result<GeneratedModuleWriteResult, String> {
    let output_path = output_path.as_ref().to_path_buf();
    let next = render_provider_runtime_constants_module();
    let current = match fs::read_to_string(&output_path) {
        Ok(value) => Some(value),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => None,
        Err(error) => return Err(format!("failed to read {}: {error}", output_path.display())),
    };
    let changed = current.as_deref() != Some(next.as_str());
    if check {
        return Ok(GeneratedModuleWriteResult {
            changed,
            wrote: false,
            output_path,
        });
    }
    if changed {
        if let Some(parent) = output_path.parent() {
            fs::create_dir_all(parent)
                .map_err(|error| format!("failed to create {}: {error}", parent.display()))?;
        }
        fs::write(&output_path, next)
            .map_err(|error| format!("failed to write {}: {error}", output_path.display()))?;
    }
    Ok(GeneratedModuleWriteResult {
        changed,
        wrote: changed,
        output_path,
    })
}

fn bundled_capability_metadata_payload() -> (
    Vec<BundledCapabilityMetadataEntry>,
    BTreeMap<String, String>,
    BTreeMap<String, String>,
) {
    let mut entries = BTreeMap::<String, BundledCapabilityMetadataEntryBuilder>::new();
    let mut legacy_aliases = BTreeMap::<String, String>::new();
    let mut auto_enable_provider_plugins = BTreeMap::<String, String>::new();

    for metadata in crawclaw_providers::bundled_provider_plugin_contract_metadata() {
        let entry = entries.entry(metadata.plugin_id.clone()).or_default();
        entry.provider_ids.extend(metadata.provider_ids);
        for legacy_plugin_id in metadata.legacy_plugin_ids {
            legacy_aliases.insert(legacy_plugin_id, metadata.plugin_id.clone());
        }
        for provider_id in metadata.auto_enable_when_configured_providers {
            auto_enable_provider_plugins.insert(provider_id, metadata.plugin_id.clone());
        }
    }

    for descriptor in crawclaw_native_plugins::registry::builtin_native_plugin_descriptors() {
        let entry = entries.entry(descriptor.plugin_id.clone()).or_default();
        entry.provider_ids.extend(
            descriptor
                .model_providers
                .into_iter()
                .map(|provider| provider.id),
        );
        entry.web_fetch_provider_ids.extend(
            descriptor
                .web_fetch_providers
                .into_iter()
                .map(|provider| provider.id),
        );
        entry.web_search_provider_ids.extend(
            descriptor
                .web_search_providers
                .into_iter()
                .map(|provider| provider.id),
        );
        entry
            .tool_names
            .extend(descriptor.tools.into_iter().map(|tool| tool.name));
    }

    let snapshots = entries
        .into_iter()
        .map(|(plugin_id, entry)| entry.into_entry(plugin_id))
        .filter(|entry| !entry.is_empty())
        .collect();

    (snapshots, legacy_aliases, auto_enable_provider_plugins)
}

#[derive(Clone, Debug, Default, PartialEq, Eq)]
struct BundledNativeProviderMetadataPayload {
    web_search_providers: Vec<BundledNativeWebProviderMetadataEntry>,
    web_fetch_providers: Vec<BundledNativeWebProviderMetadataEntry>,
    speech_providers: Vec<BundledNativeSpeechProviderMetadataEntry>,
}

fn bundled_native_provider_metadata_payload() -> BundledNativeProviderMetadataPayload {
    let mut payload = BundledNativeProviderMetadataPayload::default();
    for descriptor in crawclaw_native_plugins::registry::builtin_native_plugin_descriptors() {
        let plugin_id = descriptor.plugin_id;
        payload
            .web_search_providers
            .extend(descriptor.web_search_providers.into_iter().map(|provider| {
                BundledNativeWebProviderMetadataEntry {
                    plugin_id: plugin_id.clone(),
                    id: provider.id,
                    label: provider.label,
                    invocation: BundledNativeProviderInvocation {
                        plugin_id: provider.invocation.plugin_id,
                        operation: provider.invocation.operation,
                    },
                }
            }));
        payload
            .web_fetch_providers
            .extend(descriptor.web_fetch_providers.into_iter().map(|provider| {
                BundledNativeWebProviderMetadataEntry {
                    plugin_id: plugin_id.clone(),
                    id: provider.id,
                    label: provider.label,
                    invocation: BundledNativeProviderInvocation {
                        plugin_id: provider.invocation.plugin_id,
                        operation: provider.invocation.operation,
                    },
                }
            }));
        payload
            .speech_providers
            .extend(descriptor.speech_providers.into_iter().map(|provider| {
                BundledNativeSpeechProviderMetadataEntry {
                    plugin_id: plugin_id.clone(),
                    id: provider.id,
                    label: provider.label,
                    voices: provider.voices,
                    synthesize: BundledNativeProviderInvocation {
                        plugin_id: provider.synthesize.plugin_id,
                        operation: provider.synthesize.operation,
                    },
                }
            }));
    }
    payload.web_search_providers.sort_by(|left, right| {
        left.id
            .cmp(&right.id)
            .then_with(|| left.plugin_id.cmp(&right.plugin_id))
    });
    payload.web_fetch_providers.sort_by(|left, right| {
        left.id
            .cmp(&right.id)
            .then_with(|| left.plugin_id.cmp(&right.plugin_id))
    });
    payload.speech_providers.sort_by(|left, right| {
        left.id
            .cmp(&right.id)
            .then_with(|| left.plugin_id.cmp(&right.plugin_id))
    });
    payload
}

fn render_bundled_capability_snapshots(entries: &[BundledCapabilityMetadataEntry]) -> String {
    if entries.is_empty() {
        return "[]".to_string();
    }
    let rendered_entries = entries
        .iter()
        .map(|entry| {
            format!(
                "  {{\n    pluginId: {plugin_id},\n    providerIds: {provider_ids},\n    webFetchProviderIds: {web_fetch_provider_ids},\n    webSearchProviderIds: {web_search_provider_ids},\n    toolNames: {tool_names},\n  }},",
                plugin_id = json_string(&entry.plugin_id),
                provider_ids = render_string_array(&entry.provider_ids),
                web_fetch_provider_ids = render_string_array(&entry.web_fetch_provider_ids),
                web_search_provider_ids = render_string_array(&entry.web_search_provider_ids),
                tool_names = render_string_array(&entry.tool_names),
            )
        })
        .collect::<Vec<_>>()
        .join("\n");
    format!("[\n{rendered_entries}\n]")
}

fn render_bundled_native_provider_invocation(
    invocation: &BundledNativeProviderInvocation,
) -> String {
    format!(
        "{{ pluginId: {plugin_id}, operation: {operation} }}",
        plugin_id = json_string(&invocation.plugin_id),
        operation = json_string(&invocation.operation),
    )
}

fn render_bundled_native_web_provider_metadata(
    entries: &[BundledNativeWebProviderMetadataEntry],
) -> String {
    if entries.is_empty() {
        return "[]".to_string();
    }
    let rendered_entries = entries
        .iter()
        .map(|entry| {
            format!(
                "  {{\n    pluginId: {plugin_id},\n    id: {id},\n    label: {label},\n    invocation: {invocation},\n  }},",
                plugin_id = json_string(&entry.plugin_id),
                id = json_string(&entry.id),
                label = json_string(&entry.label),
                invocation = render_bundled_native_provider_invocation(&entry.invocation),
            )
        })
        .collect::<Vec<_>>()
        .join("\n");
    format!("[\n{rendered_entries}\n]")
}

fn render_bundled_native_speech_provider_metadata(
    entries: &[BundledNativeSpeechProviderMetadataEntry],
) -> String {
    if entries.is_empty() {
        return "[]".to_string();
    }
    let rendered_entries = entries
        .iter()
        .map(|entry| {
            format!(
                "  {{\n    pluginId: {plugin_id},\n    id: {id},\n    label: {label},\n    voices: {voices},\n    synthesize: {synthesize},\n  }},",
                plugin_id = json_string(&entry.plugin_id),
                id = json_string(&entry.id),
                label = json_string(&entry.label),
                voices = render_string_array(&entry.voices),
                synthesize = render_bundled_native_provider_invocation(&entry.synthesize),
            )
        })
        .collect::<Vec<_>>()
        .join("\n");
    format!("[\n{rendered_entries}\n]")
}

fn render_string_record(entries: &BTreeMap<String, String>) -> String {
    if entries.is_empty() {
        return "{}".to_string();
    }
    let rendered_entries = entries
        .iter()
        .map(|(key, value)| {
            format!(
                "  {key}: {value},",
                key = render_javascript_property_key(key),
                value = json_string(value),
            )
        })
        .collect::<Vec<_>>()
        .join("\n");
    format!("{{\n{rendered_entries}\n}}")
}

fn render_static_string_record(entries: &[(&str, &str)]) -> String {
    let entries = entries
        .iter()
        .map(|(key, value)| ((*key).to_string(), (*value).to_string()))
        .collect::<BTreeMap<_, _>>();
    render_string_record(&entries)
}

fn render_string_array(values: &[String]) -> String {
    if values.is_empty() {
        return "[]".to_string();
    }
    let rendered_values = values
        .iter()
        .map(|value| json_string(value))
        .collect::<Vec<_>>()
        .join(", ");
    format!("[{rendered_values}]")
}

fn render_static_string_array(values: &[&str]) -> String {
    if values.is_empty() {
        return "[]".to_string();
    }
    if values.len() > 1 {
        let rendered_values = values
            .iter()
            .map(|value| format!("  {},", json_string(value)))
            .collect::<Vec<_>>()
            .join("\n");
        return format!("[\n{rendered_values}\n]");
    }
    let rendered_values = values
        .iter()
        .map(|value| json_string(value))
        .collect::<Vec<_>>()
        .join(", ");
    format!("[{rendered_values}]")
}

fn render_javascript_property_key(value: &str) -> String {
    if is_javascript_identifier(value) {
        value.to_string()
    } else {
        json_string(value)
    }
}

fn json_string(value: &str) -> String {
    serde_json::to_string(value).expect("string literal encodes as JSON")
}

fn is_javascript_identifier(value: &str) -> bool {
    let mut chars = value.chars();
    let Some(first) = chars.next() else {
        return false;
    };
    if !(first == '$' || first == '_' || first.is_ascii_alphabetic()) {
        return false;
    }
    chars.all(|ch| ch == '$' || ch == '_' || ch.is_ascii_alphanumeric())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bundled_provider_auth_env_var_module_uses_rust_provider_metadata() {
        let source = render_bundled_provider_auth_env_var_module();
        assert!(source.contains("anthropic: [\"ANTHROPIC_OAUTH_TOKEN\", \"ANTHROPIC_API_KEY\"],"));
        assert!(source.contains(
            "\"github-copilot\": [\"COPILOT_GITHUB_TOKEN\", \"GH_TOKEN\", \"GITHUB_TOKEN\"],"
        ));
        assert!(source.contains("openai: [\"OPENAI_API_KEY\"],"));
        assert!(!source.contains("openai-codex"));
    }

    #[test]
    fn bundled_capability_metadata_module_uses_rust_plugin_metadata() {
        let source = render_bundled_capability_metadata_module();
        assert!(source.contains(r#"pluginId: "openai""#));
        assert!(source.contains(r#"providerIds: ["openai", "openai-codex"]"#));
        assert!(source.contains(r#"pluginId: "searxng""#));
        assert!(source.contains(r#"webSearchProviderIds: ["searxng"]"#));
        assert!(source.contains(r#"pluginId: "spider-fetch""#));
        assert!(source.contains(r#"webFetchProviderIds: ["spider"]"#));
        assert!(source.contains(r#"pluginId: "comfyui""#));
        assert!(source.contains(r#"toolNames: ["comfyui_workflow"]"#));
        assert!(source.contains(r#""minimax-portal-auth": "minimax""#));
        assert!(source.contains(r#""google-gemini-cli": "google""#));
    }

    #[test]
    fn bundled_capability_metadata_module_emits_native_provider_descriptors_from_rust() {
        let source = render_bundled_capability_metadata_module();
        assert!(source.contains("export const BUNDLED_NATIVE_WEB_SEARCH_PROVIDERS"));
        assert!(source.contains("export const BUNDLED_NATIVE_WEB_FETCH_PROVIDERS"));
        assert!(source.contains("export const BUNDLED_NATIVE_SPEECH_PROVIDERS"));
        assert!(source.contains(r#"id: "searxng""#));
        assert!(source.contains(r#"label: "SearXNG""#));
        assert!(source.contains(r#"invocation: { pluginId: "searxng", operation: "search" }"#));
        assert!(source.contains(r#"id: "spider""#));
        assert!(source.contains(r#"invocation: { pluginId: "spider-fetch", operation: "fetch" }"#));
        assert!(source.contains(r#"id: "qwen3-tts""#));
        assert!(source.contains(r#"voices: ["assistant"]"#));
        assert!(
            source.contains(r#"synthesize: { pluginId: "qwen3-tts", operation: "synthesize" }"#)
        );
    }

    #[test]
    fn provider_runtime_constants_module_uses_rust_provider_metadata() {
        let source = render_provider_runtime_constants_module();
        assert!(source.contains("export const CLAUDE_CLI_BACKEND_ID = \"claude-cli\";"));
        assert!(source.contains("export const AGENT_DEFAULT_PROVIDER = \"anthropic\";"));
        assert!(source.contains("export const AGENT_DEFAULT_MODEL = \"claude-opus-4-6\";"));
        assert!(source.contains("export const AGENT_DEFAULT_CONTEXT_TOKENS = 200000;"));
        assert!(source.contains("opus: \"anthropic/claude-opus-4-6\""));
        assert!(source.contains("\"gpt-mini\": \"openai/gpt-5-mini\""));
        assert!(source.contains("\"gemini-flash-lite\": \"google/gemini-3.1-flash-lite-preview\""));
        assert!(source.contains("export const ANTHROPIC_VERTEX_DEFAULT_REGION = \"global\";"));
        assert!(
            source.contains("export const OLLAMA_DEFAULT_BASE_URL = \"http://127.0.0.1:11434\";")
        );
        assert!(source.contains("export const OLLAMA_DEFAULT_CONTEXT_WINDOW = 128000;"));
        assert!(source.contains("export const OPENAI_DEFAULT_MODEL = \"openai/gpt-5.4\";"));
        assert!(source.contains(
            "export const GOOGLE_GEMINI_DEFAULT_MODEL = \"google/gemini-3.1-pro-preview\";"
        ));
        assert!(source
            .contains("export const OPENCODE_ZEN_DEFAULT_MODEL = \"opencode/claude-opus-4-6\";"));
        assert!(source.contains(
            "export const LEGACY_OPENCODE_ZEN_DEFAULT_MODELS = [\n  \"opencode/claude-opus-4-5\",\n  \"opencode-zen/claude-opus-4-5\",\n] as const;"
        ));
    }
}
