use std::fs;
use std::path::{Path, PathBuf};

const GENERATED_BY: &str = "crawclaw-runtime emit-bundled-provider-auth-env-vars";

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedModuleWriteResult {
    pub changed: bool,
    pub wrote: bool,
    pub output_path: PathBuf,
}

pub fn render_bundled_provider_auth_env_var_module() -> String {
    let mut entries = crawclaw_providers::bundled_provider_auth_env_vars();
    entries.sort_by(|left, right| left.provider.cmp(right.provider));
    let rendered_entries = entries
        .iter()
        .map(|entry| {
            let rendered_key = if is_javascript_identifier(entry.provider) {
                entry.provider.to_string()
            } else {
                serde_json::to_string(entry.provider).expect("provider id encodes as JSON")
            };
            let rendered_env_vars = entry
                .env_vars
                .iter()
                .map(|value| serde_json::to_string(value).expect("env var encodes as JSON"))
                .collect::<Vec<_>>()
                .join(", ");
            format!("  {rendered_key}: [{rendered_env_vars}],")
        })
        .collect::<Vec<_>>()
        .join("\n");
    format!(
        "// Auto-generated by {GENERATED_BY}. Do not edit directly.\n\nexport const BUNDLED_PROVIDER_AUTH_ENV_VAR_CANDIDATES = {{\n{rendered_entries}\n}} as const satisfies Record<string, readonly string[]>;\n"
    )
}

pub fn write_bundled_provider_auth_env_var_module(
    output_path: impl AsRef<Path>,
    check: bool,
) -> Result<GeneratedModuleWriteResult, String> {
    let output_path = output_path.as_ref().to_path_buf();
    let next = render_bundled_provider_auth_env_var_module();
    let current = match fs::read_to_string(&output_path) {
        Ok(value) => Some(value),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => None,
        Err(error) => return Err(format!("failed to read {}: {error}", output_path.display())),
    };
    let changed = current.as_deref() != Some(next.as_str());
    if check {
        return Ok(GeneratedModuleWriteResult {
            changed,
            wrote: false,
            output_path,
        });
    }
    if changed {
        if let Some(parent) = output_path.parent() {
            fs::create_dir_all(parent)
                .map_err(|error| format!("failed to create {}: {error}", parent.display()))?;
        }
        fs::write(&output_path, next)
            .map_err(|error| format!("failed to write {}: {error}", output_path.display()))?;
    }
    Ok(GeneratedModuleWriteResult {
        changed,
        wrote: changed,
        output_path,
    })
}

fn is_javascript_identifier(value: &str) -> bool {
    let mut chars = value.chars();
    let Some(first) = chars.next() else {
        return false;
    };
    if !(first == '$' || first == '_' || first.is_ascii_alphabetic()) {
        return false;
    }
    chars.all(|ch| ch == '$' || ch == '_' || ch.is_ascii_alphanumeric())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bundled_provider_auth_env_var_module_uses_rust_provider_metadata() {
        let source = render_bundled_provider_auth_env_var_module();
        assert!(source.contains("anthropic: [\"ANTHROPIC_OAUTH_TOKEN\", \"ANTHROPIC_API_KEY\"],"));
        assert!(source.contains(
            "\"github-copilot\": [\"COPILOT_GITHUB_TOKEN\", \"GH_TOKEN\", \"GITHUB_TOKEN\"],"
        ));
        assert!(source.contains("openai: [\"OPENAI_API_KEY\"],"));
        assert!(!source.contains("openai-codex"));
    }
}
