use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::{Path, PathBuf};

const GENERATED_BY: &str = "crawclaw-runtime emit-bundled-provider-auth-env-vars";
const RUNTIME_CONSTANTS_GENERATED_BY: &str = "crawclaw-runtime emit-provider-runtime-constants";
const BUNDLED_CAPABILITY_METADATA_GENERATED_BY: &str =
    "crawclaw-runtime emit-bundled-capability-metadata";
const WEB_DOCS_URL: &str = "https://docs.crawclaw.ai/tools/web";

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedModuleWriteResult {
    pub changed: bool,
    pub wrote: bool,
    pub output_path: PathBuf,
}

#[derive(Clone, Debug, Default, PartialEq, Eq)]
struct BundledCapabilityMetadataEntryBuilder {
    provider_ids: BTreeSet<String>,
    web_fetch_provider_ids: BTreeSet<String>,
    web_search_provider_ids: BTreeSet<String>,
    tool_names: BTreeSet<String>,
}

#[derive(Clone, Debug, PartialEq, Eq)]
struct BundledCapabilityMetadataEntry {
    plugin_id: String,
    provider_ids: Vec<String>,
    web_fetch_provider_ids: Vec<String>,
    web_search_provider_ids: Vec<String>,
    tool_names: Vec<String>,
}

#[derive(Clone, Debug, PartialEq, Eq)]
struct BundledNativeProviderInvocation {
    plugin_id: String,
    operation: String,
}

#[derive(Clone, Debug, PartialEq, Eq)]
struct BundledNativeWebProviderMetadataEntry {
    plugin_id: String,
    id: String,
    label: String,
    hint: String,
    onboarding_scopes: Vec<String>,
    requires_credential: bool,
    env_vars: Vec<String>,
    placeholder: String,
    signup_url: String,
    docs_url: String,
    invocation: BundledNativeProviderInvocation,
}

#[derive(Clone, Debug, PartialEq, Eq)]
struct BundledNativeSpeechProviderMetadataEntry {
    plugin_id: String,
    id: String,
    label: String,
    voices: Vec<String>,
    synthesize: BundledNativeProviderInvocation,
}

impl BundledCapabilityMetadataEntry {
    fn is_empty(&self) -> bool {
        self.provider_ids.is_empty()
            && self.web_fetch_provider_ids.is_empty()
            && self.web_search_provider_ids.is_empty()
            && self.tool_names.is_empty()
    }
}

impl BundledCapabilityMetadataEntryBuilder {
    fn into_entry(self, plugin_id: String) -> BundledCapabilityMetadataEntry {
        BundledCapabilityMetadataEntry {
            plugin_id,
            provider_ids: self.provider_ids.into_iter().collect(),
            web_fetch_provider_ids: self.web_fetch_provider_ids.into_iter().collect(),
            web_search_provider_ids: self.web_search_provider_ids.into_iter().collect(),
            tool_names: self.tool_names.into_iter().collect(),
        }
    }
}

pub fn render_bundled_provider_auth_env_var_module() -> String {
    let mut entries = crawclaw_providers::bundled_provider_auth_env_vars();
    entries.sort_by(|left, right| left.provider.cmp(right.provider));
    let rendered_entries = entries
        .iter()
        .map(|entry| {
            let rendered_key = if is_javascript_identifier(entry.provider) {
                entry.provider.to_string()
            } else {
                serde_json::to_string(entry.provider).expect("provider id encodes as JSON")
            };
            let rendered_env_vars = entry
                .env_vars
                .iter()
                .map(|value| serde_json::to_string(value).expect("env var encodes as JSON"))
                .collect::<Vec<_>>()
                .join(", ");
            format!("  {rendered_key}: [{rendered_env_vars}],")
        })
        .collect::<Vec<_>>()
        .join("\n");
    format!(
        "// Auto-generated by {GENERATED_BY}. Do not edit directly.\n\nexport const BUNDLED_PROVIDER_AUTH_ENV_VAR_CANDIDATES = {{\n{rendered_entries}\n}} as const satisfies Record<string, readonly string[]>;\n"
    )
}

pub fn write_bundled_provider_auth_env_var_module(
    output_path: impl AsRef<Path>,
    check: bool,
) -> Result<GeneratedModuleWriteResult, String> {
    let output_path = output_path.as_ref().to_path_buf();
    let next = render_bundled_provider_auth_env_var_module();
    let current = match fs::read_to_string(&output_path) {
        Ok(value) => Some(value),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => None,
        Err(error) => return Err(format!("failed to read {}: {error}", output_path.display())),
    };
    let changed = current.as_deref() != Some(next.as_str());
    if check {
        return Ok(GeneratedModuleWriteResult {
            changed,
            wrote: false,
            output_path,
        });
    }
    if changed {
        if let Some(parent) = output_path.parent() {
            fs::create_dir_all(parent)
                .map_err(|error| format!("failed to create {}: {error}", parent.display()))?;
        }
        fs::write(&output_path, next)
            .map_err(|error| format!("failed to write {}: {error}", output_path.display()))?;
    }
    Ok(GeneratedModuleWriteResult {
        changed,
        wrote: changed,
        output_path,
    })
}

pub fn render_bundled_capability_metadata_module() -> String {
    let (snapshots, legacy_aliases, auto_enable_provider_plugins) =
        bundled_capability_metadata_payload();
    let rendered_snapshots = render_bundled_capability_snapshots(&snapshots);
    let rendered_legacy_aliases = render_string_record(&legacy_aliases);
    let rendered_auto_enable_provider_plugins = render_string_record(&auto_enable_provider_plugins);
    let native_metadata = bundled_native_provider_metadata_payload();
    let rendered_native_web_search_providers =
        render_bundled_native_web_provider_metadata(&native_metadata.web_search_providers);
    let rendered_native_web_fetch_providers =
        render_bundled_native_web_provider_metadata(&native_metadata.web_fetch_providers);
    let rendered_native_speech_providers =
        render_bundled_native_speech_provider_metadata(&native_metadata.speech_providers);
    format!(
        r#"// Auto-generated by {BUNDLED_CAPABILITY_METADATA_GENERATED_BY}. Do not edit directly.

export type BundledPluginContractSnapshot = {{
  pluginId: string;
  providerIds: readonly string[];
  webFetchProviderIds: readonly string[];
  webSearchProviderIds: readonly string[];
  toolNames: readonly string[];
}};

export type BundledNativeProviderInvocation = {{
  pluginId: string;
  operation: string;
}};

export type BundledNativeWebProviderMetadata = {{
  pluginId: string;
  id: string;
  label: string;
  hint: string;
  onboardingScopes: ReadonlyArray<"text-inference">;
  requiresCredential: boolean;
  envVars: readonly string[];
  placeholder: string;
  signupUrl: string;
  docsUrl: string;
  invocation: BundledNativeProviderInvocation;
}};

export type BundledNativeSpeechProviderMetadata = {{
  pluginId: string;
  id: string;
  label: string;
  voices: readonly string[];
  synthesize: BundledNativeProviderInvocation;
}};

export const BUNDLED_PLUGIN_CONTRACT_SNAPSHOTS = {rendered_snapshots} as const satisfies readonly BundledPluginContractSnapshot[];

export const BUNDLED_NATIVE_WEB_SEARCH_PROVIDERS = {rendered_native_web_search_providers} as const satisfies readonly BundledNativeWebProviderMetadata[];

export const BUNDLED_NATIVE_WEB_FETCH_PROVIDERS = {rendered_native_web_fetch_providers} as const satisfies readonly BundledNativeWebProviderMetadata[];

export const BUNDLED_NATIVE_SPEECH_PROVIDERS = {rendered_native_speech_providers} as const satisfies readonly BundledNativeSpeechProviderMetadata[];

export const BUNDLED_LEGACY_PLUGIN_ID_ALIASES = {rendered_legacy_aliases} as const satisfies Readonly<Record<string, string>>;

export const BUNDLED_AUTO_ENABLE_PROVIDER_PLUGIN_IDS = {rendered_auto_enable_provider_plugins} as const satisfies Readonly<Record<string, string>>;
"#
    )
}

pub fn write_bundled_capability_metadata_module(
    output_path: impl AsRef<Path>,
    check: bool,
) -> Result<GeneratedModuleWriteResult, String> {
    let output_path = output_path.as_ref().to_path_buf();
    let next = render_bundled_capability_metadata_module();
    let current = match fs::read_to_string(&output_path) {
        Ok(value) => Some(value),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => None,
        Err(error) => return Err(format!("failed to read {}: {error}", output_path.display())),
    };
    let changed = current.as_deref() != Some(next.as_str());
    if check {
        return Ok(GeneratedModuleWriteResult {
            changed,
            wrote: false,
            output_path,
        });
    }
    if changed {
        if let Some(parent) = output_path.parent() {
            fs::create_dir_all(parent)
                .map_err(|error| format!("failed to create {}: {error}", parent.display()))?;
        }
        fs::write(&output_path, next)
            .map_err(|error| format!("failed to write {}: {error}", output_path.display()))?;
    }
    Ok(GeneratedModuleWriteResult {
        changed,
        wrote: changed,
        output_path,
    })
}

pub fn render_provider_runtime_constants_module() -> String {
    format!(
        r#"// Auto-generated by {RUNTIME_CONSTANTS_GENERATED_BY}. Do not edit directly.

export const CLAUDE_CLI_BACKEND_ID = {claude_cli_backend_id};
export const AGENT_DEFAULT_PROVIDER = {agent_default_provider};
export const AGENT_DEFAULT_MODEL = {agent_default_model};
export const AGENT_DEFAULT_CONTEXT_TOKENS = {agent_default_context_tokens};
export const AGENT_DEFAULT_MODEL_ALIASES = {agent_default_model_aliases} as const satisfies Readonly<Record<string, string>>;
export const PROVIDER_ID_ALIASES = {provider_id_aliases} as const satisfies Readonly<Record<string, string>>;
export const PROVIDER_AUTH_ID_ALIASES = {provider_auth_id_aliases} as const satisfies Readonly<Record<string, string>>;
export const ANTHROPIC_ADAPTIVE_THINKING_MODEL_PATTERN =
  {anthropic_adaptive_thinking_model_pattern};
export const AMAZON_BEDROCK_ADAPTIVE_THINKING_MODEL_PATTERN =
  {amazon_bedrock_adaptive_thinking_model_pattern};
export const OPENAI_XHIGH_THINKING_MODEL_IDS = {openai_xhigh_thinking_model_ids} as const;
export const OPENAI_CODEX_XHIGH_THINKING_MODEL_IDS = {openai_codex_xhigh_thinking_model_ids} as const;
export const GITHUB_COPILOT_XHIGH_THINKING_MODEL_IDS = {github_copilot_xhigh_thinking_model_ids} as const;
export const DEFAULT_MODEL_COST = {default_model_cost} as const;
export const DEFAULT_MODEL_INPUT = {default_model_input} as const;
export const DEFAULT_MODEL_MAX_TOKENS = {default_model_max_tokens};
export const PROVIDER_DEFAULT_API_BY_PROVIDER = {provider_default_api_by_provider} as const satisfies Readonly<Record<string, string>>;
export const MODEL_APIS = {model_apis} as const;
export const ANTHROPIC_CONTEXT_1M_MODEL_PREFIXES = {anthropic_context_1m_model_prefixes} as const;
export const ANTHROPIC_CONTEXT_1M_TOKENS = {anthropic_context_1m_tokens};
export const DEFAULT_PROVIDER_CAPABILITIES = {default_provider_capabilities} as const;
export const PROVIDER_CAPABILITY_FALLBACKS = {provider_capability_fallbacks} as const;
export const CORE_PROVIDER_AUTH_ENV_VAR_CANDIDATES = {core_provider_auth_env_var_candidates} as const satisfies Readonly<Record<string, readonly string[]>>;
export const CORE_PROVIDER_SETUP_ENV_VAR_OVERRIDES = {core_provider_setup_env_var_overrides} as const satisfies Readonly<Record<string, readonly string[]>>;
export const EXTRA_PROVIDER_AUTH_ENV_VARS = {extra_provider_auth_env_vars} as const;
export const MINIMAX_OAUTH_MARKER = {minimax_oauth_marker};
export const OAUTH_API_KEY_MARKER_PREFIX = {oauth_api_key_marker_prefix};
export const OLLAMA_LOCAL_AUTH_MARKER = {ollama_local_auth_marker};
export const CUSTOM_LOCAL_AUTH_MARKER = {custom_local_auth_marker};
export const GCP_VERTEX_CREDENTIALS_MARKER = {gcp_vertex_credentials_marker};
export const NON_ENV_SECRETREF_MARKER = {non_env_secretref_marker};
export const SECRETREF_ENV_HEADER_MARKER_PREFIX = {secretref_env_header_marker_prefix};
export const AWS_BEDROCK_BEARER_TOKEN_ENV = {aws_bedrock_bearer_token_env};
export const AWS_ACCESS_KEY_ID_ENV = {aws_access_key_id_env};
export const AWS_SECRET_ACCESS_KEY_ENV = {aws_secret_access_key_env};
export const AWS_PROFILE_ENV = {aws_profile_env};
export const AWS_SDK_ENV_MARKERS = {aws_sdk_env_markers} as const;
export const LEGACY_ENV_API_KEY_MARKERS = {legacy_env_api_key_markers} as const;
export const ANTHROPIC_PROVIDER_ID = {anthropic_provider_id};
export const AMAZON_BEDROCK_PROVIDER_ID = {amazon_bedrock_provider_id};
export const GITHUB_COPILOT_PROVIDER_ID = {github_copilot_provider_id};
export const GOOGLE_PROVIDER_ID = {google_provider_id};
export const GOOGLE_VERTEX_PROVIDER_ID = {google_vertex_provider_id};
export const GROQ_PROVIDER_ID = {groq_provider_id};
export const MINIMAX_PROVIDER_ID = {minimax_provider_id};
export const MINIMAX_PORTAL_PROVIDER_ID = {minimax_portal_provider_id};
export const MISTRAL_PROVIDER_ID = {mistral_provider_id};
export const MODELSTUDIO_PROVIDER_ID = {modelstudio_provider_id};
export const MOONSHOT_PROVIDER_ID = {moonshot_provider_id};
export const OLLAMA_PROVIDER_ID = {ollama_provider_id};
export const OPENAI_PROVIDER_ID = {openai_provider_id};
export const OPENAI_CODEX_PROVIDER_ID = {openai_codex_provider_id};
export const OPENROUTER_PROVIDER_ID = {openrouter_provider_id};
export const TOGETHER_PROVIDER_ID = {together_provider_id};
export const VERCEL_AI_GATEWAY_PROVIDER_ID = {vercel_ai_gateway_provider_id};
export const XAI_PROVIDER_ID = {xai_provider_id};
export const ZAI_PROVIDER_ID = {zai_provider_id};
export const ANTHROPIC_API_KEY_ENV = {anthropic_api_key_env};
export const ANTHROPIC_OAUTH_TOKEN_ENV = {anthropic_oauth_token_env};
export const PROVIDER_USAGE_LABELS = {provider_usage_labels} as const satisfies Readonly<Record<string, string>>;
export const PROVIDER_ATTRIBUTION_PRODUCT = {provider_attribution_product};
export const PROVIDER_ATTRIBUTION_ORIGINATOR = {provider_attribution_originator};
export const PROVIDER_ATTRIBUTION_REFERER_URL = {provider_attribution_referer_url};
export const OPENROUTER_ATTRIBUTION_DOCS_URL = {openrouter_attribution_docs_url};
export const OPENROUTER_ATTRIBUTION_CATEGORY = {openrouter_attribution_category};
export const OPENAI_COMPLETIONS_API = {openai_completions_api};
export const OPENAI_RESPONSES_API = {openai_responses_api};
export const OPENAI_CODEX_RESPONSES_API = {openai_codex_responses_api};
export const OPENAI_AUDIO_TRANSCRIPTIONS_API = {openai_audio_transcriptions_api};
export const ANTHROPIC_MESSAGES_API = {anthropic_messages_api};
export const MODEL_COMPAT_THINKING_FORMATS = {model_compat_thinking_formats} as const;
export const MODEL_COMPAT_MAX_TOKENS_FIELDS = {model_compat_max_tokens_fields} as const;
export const MINIMAX_VLM_MODEL_ID = {minimax_vlm_model_id};
export const MINIMAX_API_HOST_ENV = {minimax_api_host_env};
export const MINIMAX_DEFAULT_API_HOST = {minimax_default_api_host};
export const MINIMAX_VLM_API_PATH = {minimax_vlm_api_path};
export const LOCAL_ENDPOINT_HOSTS = {local_endpoint_hosts} as const;
export const MOONSHOT_NATIVE_BASE_URLS = {moonshot_native_base_urls} as const;
export const MODELSTUDIO_NATIVE_BASE_URLS = {modelstudio_native_base_urls} as const;
export const OPENAI_RESPONSES_APIS = {openai_responses_apis} as const;
export const OPENAI_RESPONSES_PROVIDERS = {openai_responses_providers} as const;
export const MOONSHOT_COMPAT_PROVIDERS = {moonshot_compat_providers} as const;
export const TRANSCRIPT_OPENAI_MODEL_APIS = {transcript_openai_model_apis} as const;
export const TRANSCRIPT_ANTHROPIC_MODEL_APIS = {transcript_anthropic_model_apis} as const;
export const GOOGLE_MODEL_APIS = {google_model_apis} as const;
export const OPENAI_COMPATIBLE_TURN_VALIDATION_API = {openai_compatible_turn_validation_api};
export const OPENAI_COMPATIBLE_TOOL_ID_SANITIZATION_APIS = {openai_compatible_tool_id_sanitization_apis} as const;
export const OPENROUTER_MODELS_API_URL = {openrouter_models_api_url};
export const OPENROUTER_DEFAULT_MODEL_REF = {openrouter_default_model_ref};
export const MODEL_CATALOG_CONFIGURED_PROVIDER_IDS = {model_catalog_configured_provider_ids} as const;
export const OPENROUTER_PRICING_PROVIDER_ALIASES = {openrouter_pricing_provider_aliases} as const satisfies Readonly<Record<string, string>>;
export const OPENROUTER_WRAPPER_PROVIDERS = {openrouter_wrapper_providers} as const;
export const KNOWN_PROVIDER_FAMILIES = {known_provider_families} as const satisfies Readonly<Record<string, string>>;
export const MISTRAL_SAFE_MAX_TOKENS_BY_MODEL = {mistral_safe_max_tokens_by_model} as const satisfies Readonly<Record<string, number>>;
export const DEFAULT_CLAUDE_CLI_MODEL = {default_claude_cli_model};
export const ANTHROPIC_VERTEX_DEFAULT_REGION = {anthropic_vertex_default_region};
export const ANTHROPIC_VERTEX_CREDENTIALS_MARKER = {anthropic_vertex_credentials_marker};
export const OLLAMA_DEFAULT_BASE_URL = {ollama_default_base_url};
export const OLLAMA_DEFAULT_CONTEXT_WINDOW = {ollama_default_context_window};
export const OLLAMA_DEFAULT_MAX_TOKENS = {ollama_default_max_tokens};
export const OLLAMA_DEFAULT_MODEL = {ollama_default_model};
export const OLLAMA_DEFAULT_EMBEDDING_MODEL = {ollama_default_embedding_model};
export const OPENAI_DEFAULT_MODEL = {openai_default_model};
export const OPENAI_CODEX_DEFAULT_MODEL = {openai_codex_default_model};
export const OPENAI_DEFAULT_IMAGE_MODEL = {openai_default_image_model};
export const OPENAI_DEFAULT_AUDIO_TRANSCRIPTION_MODEL = {openai_default_audio_transcription_model};
export const OPENAI_DEFAULT_EMBEDDING_MODEL = {openai_default_embedding_model};
export const GOOGLE_GEMINI_DEFAULT_MODEL = {google_gemini_default_model};
export const OPENCODE_GO_DEFAULT_MODEL_REF = {opencode_go_default_model_ref};
export const OPENCODE_ZEN_DEFAULT_MODEL = {opencode_zen_default_model};
export const LEGACY_OPENCODE_ZEN_DEFAULT_MODELS = {legacy_opencode_zen_default_models} as const;
"#,
        claude_cli_backend_id = json_string(crawclaw_providers::CLAUDE_CLI_BACKEND_ID),
        agent_default_provider = json_string(crawclaw_providers::AGENT_DEFAULT_PROVIDER),
        agent_default_model = json_string(crawclaw_providers::AGENT_DEFAULT_MODEL),
        agent_default_context_tokens = crawclaw_providers::AGENT_DEFAULT_CONTEXT_TOKENS,
        agent_default_model_aliases =
            render_static_string_record(crawclaw_providers::AGENT_DEFAULT_MODEL_ALIASES),
        provider_id_aliases = render_static_string_record(crawclaw_providers::PROVIDER_ID_ALIASES),
        provider_auth_id_aliases =
            render_static_string_record(crawclaw_providers::PROVIDER_AUTH_ID_ALIASES),
        anthropic_adaptive_thinking_model_pattern =
            json_string(crawclaw_providers::ANTHROPIC_ADAPTIVE_THINKING_MODEL_PATTERN),
        amazon_bedrock_adaptive_thinking_model_pattern =
            json_string(crawclaw_providers::AMAZON_BEDROCK_ADAPTIVE_THINKING_MODEL_PATTERN),
        openai_xhigh_thinking_model_ids =
            render_static_string_array(crawclaw_providers::OPENAI_XHIGH_THINKING_MODEL_IDS),
        openai_codex_xhigh_thinking_model_ids =
            render_static_string_array(crawclaw_providers::OPENAI_CODEX_XHIGH_THINKING_MODEL_IDS),
        github_copilot_xhigh_thinking_model_ids = render_static_string_array_inline(
            crawclaw_providers::GITHUB_COPILOT_XHIGH_THINKING_MODEL_IDS,
        ),
        default_model_cost =
            render_provider_model_default_cost(crawclaw_providers::PROVIDER_MODEL_DEFAULT_COST),
        default_model_input = render_static_string_array_inline(
            crawclaw_providers::PROVIDER_MODEL_DEFAULT_INPUT_TYPES
        ),
        default_model_max_tokens = crawclaw_providers::PROVIDER_MODEL_DEFAULT_MAX_TOKENS,
        provider_default_api_by_provider =
            render_static_string_record(crawclaw_providers::PROVIDER_DEFAULT_API_BY_PROVIDER),
        model_apis = render_static_string_array(crawclaw_providers::MODEL_APIS),
        anthropic_context_1m_model_prefixes = render_static_string_array_inline(
            crawclaw_providers::ANTHROPIC_CONTEXT_1M_MODEL_PREFIXES,
        ),
        anthropic_context_1m_tokens = crawclaw_providers::ANTHROPIC_CONTEXT_1M_TOKENS,
        default_provider_capabilities =
            render_default_provider_capabilities(crawclaw_providers::DEFAULT_PROVIDER_CAPABILITIES),
        provider_capability_fallbacks =
            render_provider_capability_fallbacks(crawclaw_providers::PROVIDER_CAPABILITY_FALLBACKS),
        core_provider_auth_env_var_candidates = render_provider_auth_env_var_record(
            crawclaw_providers::CORE_PROVIDER_AUTH_ENV_VAR_CANDIDATES,
        ),
        core_provider_setup_env_var_overrides = render_provider_auth_env_var_record(
            crawclaw_providers::CORE_PROVIDER_SETUP_ENV_VAR_OVERRIDES,
        ),
        extra_provider_auth_env_vars =
            render_static_string_array_inline(crawclaw_providers::EXTRA_PROVIDER_AUTH_ENV_VARS),
        minimax_oauth_marker = json_string(crawclaw_providers::MINIMAX_OAUTH_MARKER),
        oauth_api_key_marker_prefix = json_string(crawclaw_providers::OAUTH_API_KEY_MARKER_PREFIX),
        ollama_local_auth_marker = json_string(crawclaw_providers::OLLAMA_LOCAL_AUTH_MARKER),
        custom_local_auth_marker = json_string(crawclaw_providers::CUSTOM_LOCAL_AUTH_MARKER),
        gcp_vertex_credentials_marker =
            json_string(crawclaw_providers::GCP_VERTEX_CREDENTIALS_MARKER),
        non_env_secretref_marker = json_string(crawclaw_providers::NON_ENV_SECRETREF_MARKER),
        secretref_env_header_marker_prefix =
            json_string(crawclaw_providers::SECRETREF_ENV_HEADER_MARKER_PREFIX),
        aws_bedrock_bearer_token_env =
            json_string(crawclaw_providers::AWS_BEDROCK_BEARER_TOKEN_ENV),
        aws_access_key_id_env = json_string(crawclaw_providers::AWS_ACCESS_KEY_ID_ENV),
        aws_secret_access_key_env = json_string(crawclaw_providers::AWS_SECRET_ACCESS_KEY_ENV),
        aws_profile_env = json_string(crawclaw_providers::AWS_PROFILE_ENV),
        aws_sdk_env_markers = render_static_string_array(crawclaw_providers::AWS_SDK_ENV_MARKERS),
        legacy_env_api_key_markers =
            render_static_string_array(crawclaw_providers::LEGACY_ENV_API_KEY_MARKERS),
        anthropic_provider_id = json_string(crawclaw_providers::ANTHROPIC_PROVIDER_ID),
        amazon_bedrock_provider_id = json_string(crawclaw_providers::AMAZON_BEDROCK_PROVIDER_ID),
        github_copilot_provider_id = json_string(crawclaw_providers::GITHUB_COPILOT_PROVIDER_ID),
        google_provider_id = json_string(crawclaw_providers::GOOGLE_PROVIDER_ID),
        google_vertex_provider_id = json_string(crawclaw_providers::GOOGLE_VERTEX_PROVIDER_ID),
        groq_provider_id = json_string(crawclaw_providers::GROQ_PROVIDER_ID),
        minimax_provider_id = json_string(crawclaw_providers::MINIMAX_PROVIDER_ID),
        minimax_portal_provider_id = json_string(crawclaw_providers::MINIMAX_PORTAL_PROVIDER_ID),
        mistral_provider_id = json_string(crawclaw_providers::MISTRAL_PROVIDER_ID),
        modelstudio_provider_id = json_string(crawclaw_providers::MODELSTUDIO_PROVIDER_ID),
        moonshot_provider_id = json_string(crawclaw_providers::MOONSHOT_PROVIDER_ID),
        ollama_provider_id = json_string(crawclaw_providers::OLLAMA_PROVIDER_ID),
        openai_provider_id = json_string(crawclaw_providers::OPENAI_PROVIDER_ID),
        openai_codex_provider_id = json_string(crawclaw_providers::OPENAI_CODEX_PROVIDER_ID),
        openrouter_provider_id = json_string(crawclaw_providers::OPENROUTER_PROVIDER_ID),
        together_provider_id = json_string(crawclaw_providers::TOGETHER_PROVIDER_ID),
        vercel_ai_gateway_provider_id =
            json_string(crawclaw_providers::VERCEL_AI_GATEWAY_PROVIDER_ID),
        xai_provider_id = json_string(crawclaw_providers::XAI_PROVIDER_ID),
        zai_provider_id = json_string(crawclaw_providers::ZAI_PROVIDER_ID),
        anthropic_api_key_env = json_string(crawclaw_providers::ANTHROPIC_API_KEY_ENV),
        anthropic_oauth_token_env = json_string(crawclaw_providers::ANTHROPIC_OAUTH_TOKEN_ENV),
        provider_usage_labels =
            render_static_string_record(crawclaw_providers::PROVIDER_USAGE_LABELS),
        provider_attribution_product =
            json_string(crawclaw_providers::PROVIDER_ATTRIBUTION_PRODUCT),
        provider_attribution_originator =
            json_string(crawclaw_providers::PROVIDER_ATTRIBUTION_ORIGINATOR),
        provider_attribution_referer_url =
            json_string(crawclaw_providers::PROVIDER_ATTRIBUTION_REFERER_URL),
        openrouter_attribution_docs_url =
            json_string(crawclaw_providers::OPENROUTER_ATTRIBUTION_DOCS_URL),
        openrouter_attribution_category =
            json_string(crawclaw_providers::OPENROUTER_ATTRIBUTION_CATEGORY),
        openai_completions_api = json_string(crawclaw_providers::OPENAI_COMPLETIONS_API),
        openai_responses_api = json_string(crawclaw_providers::OPENAI_RESPONSES_API),
        openai_codex_responses_api =
            json_string(crawclaw_providers::OPENAI_CODEX_RESPONSES_API),
        openai_audio_transcriptions_api =
            json_string(crawclaw_providers::OPENAI_AUDIO_TRANSCRIPTIONS_API),
        anthropic_messages_api = json_string(crawclaw_providers::ANTHROPIC_MESSAGES_API),
        model_compat_thinking_formats =
            render_static_string_array(crawclaw_providers::MODEL_COMPAT_THINKING_FORMATS),
        model_compat_max_tokens_fields =
            render_static_string_array_inline(crawclaw_providers::MODEL_COMPAT_MAX_TOKENS_FIELDS),
        minimax_vlm_model_id = json_string(crawclaw_providers::MINIMAX_VLM_MODEL_ID),
        minimax_api_host_env = json_string(crawclaw_providers::MINIMAX_API_HOST_ENV),
        minimax_default_api_host = json_string(crawclaw_providers::MINIMAX_DEFAULT_API_HOST),
        minimax_vlm_api_path = json_string(crawclaw_providers::MINIMAX_VLM_API_PATH),
        local_endpoint_hosts =
            render_static_string_array_inline(crawclaw_providers::LOCAL_ENDPOINT_HOSTS),
        moonshot_native_base_urls =
            render_static_string_array(crawclaw_providers::MOONSHOT_NATIVE_BASE_URLS),
        modelstudio_native_base_urls =
            render_static_string_array(crawclaw_providers::MODELSTUDIO_NATIVE_BASE_URLS),
        openai_responses_apis =
            render_static_string_array_inline(crawclaw_providers::OPENAI_RESPONSES_APIS),
        openai_responses_providers =
            render_static_string_array(crawclaw_providers::OPENAI_RESPONSES_PROVIDERS),
        moonshot_compat_providers =
            render_static_string_array_inline(crawclaw_providers::MOONSHOT_COMPAT_PROVIDERS),
        transcript_openai_model_apis =
            render_static_string_array(crawclaw_providers::TRANSCRIPT_OPENAI_MODEL_APIS),
        transcript_anthropic_model_apis =
            render_static_string_array(crawclaw_providers::TRANSCRIPT_ANTHROPIC_MODEL_APIS),
        google_model_apis =
            render_static_string_array_inline(crawclaw_providers::GOOGLE_MODEL_APIS),
        openai_compatible_turn_validation_api =
            json_string(crawclaw_providers::OPENAI_COMPATIBLE_TURN_VALIDATION_API),
        openai_compatible_tool_id_sanitization_apis = render_static_string_array(
            crawclaw_providers::OPENAI_COMPATIBLE_TOOL_ID_SANITIZATION_APIS,
        ),
        openrouter_models_api_url = json_string(crawclaw_providers::OPENROUTER_MODELS_API_URL),
        openrouter_default_model_ref =
            json_string(crawclaw_providers::OPENROUTER_DEFAULT_MODEL_REF),
        model_catalog_configured_provider_ids = render_static_string_array_inline(
            crawclaw_providers::MODEL_CATALOG_CONFIGURED_PROVIDER_IDS
        ),
        openrouter_pricing_provider_aliases =
            render_static_string_record(crawclaw_providers::OPENROUTER_PRICING_PROVIDER_ALIASES),
        openrouter_wrapper_providers =
            render_static_string_array(crawclaw_providers::OPENROUTER_WRAPPER_PROVIDERS),
        known_provider_families =
            render_static_string_record(crawclaw_providers::KNOWN_PROVIDER_FAMILIES),
        mistral_safe_max_tokens_by_model =
            render_static_u32_record(crawclaw_providers::MISTRAL_SAFE_MAX_TOKENS_BY_MODEL),
        default_claude_cli_model = json_string(crawclaw_providers::DEFAULT_CLAUDE_CLI_MODEL),
        anthropic_vertex_default_region =
            json_string(crawclaw_providers::ANTHROPIC_VERTEX_DEFAULT_REGION),
        anthropic_vertex_credentials_marker =
            json_string(crawclaw_providers::ANTHROPIC_VERTEX_CREDENTIALS_MARKER),
        ollama_default_base_url = json_string(crawclaw_providers::OLLAMA_DEFAULT_BASE_URL),
        ollama_default_context_window = crawclaw_providers::OLLAMA_DEFAULT_CONTEXT_WINDOW,
        ollama_default_max_tokens = crawclaw_providers::OLLAMA_DEFAULT_MAX_TOKENS,
        ollama_default_model = json_string(crawclaw_providers::OLLAMA_DEFAULT_MODEL),
        ollama_default_embedding_model =
            json_string(crawclaw_providers::OLLAMA_DEFAULT_EMBEDDING_MODEL),
        openai_default_model = json_string(crawclaw_providers::OPENAI_DEFAULT_MODEL_REF),
        openai_codex_default_model =
            json_string(crawclaw_providers::OPENAI_CODEX_DEFAULT_MODEL_REF),
        openai_default_image_model = json_string(crawclaw_providers::OPENAI_DEFAULT_IMAGE_MODEL),
        openai_default_audio_transcription_model =
            json_string(crawclaw_providers::OPENAI_DEFAULT_AUDIO_TRANSCRIPTION_MODEL),
        openai_default_embedding_model =
            json_string(crawclaw_providers::OPENAI_DEFAULT_EMBEDDING_MODEL),
        google_gemini_default_model =
            json_string(crawclaw_providers::GOOGLE_GEMINI_DEFAULT_MODEL_REF),
        opencode_go_default_model_ref =
            json_string(crawclaw_providers::OPENCODE_GO_DEFAULT_MODEL_REF),
        opencode_zen_default_model =
            json_string(crawclaw_providers::OPENCODE_ZEN_DEFAULT_MODEL_REF),
        legacy_opencode_zen_default_models =
            render_static_string_array(crawclaw_providers::LEGACY_OPENCODE_ZEN_DEFAULT_MODEL_REFS),
    )
}

pub fn write_provider_runtime_constants_module(
    output_path: impl AsRef<Path>,
    check: bool,
) -> Result<GeneratedModuleWriteResult, String> {
    let output_path = output_path.as_ref().to_path_buf();
    let next = render_provider_runtime_constants_module();
    let current = match fs::read_to_string(&output_path) {
        Ok(value) => Some(value),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => None,
        Err(error) => return Err(format!("failed to read {}: {error}", output_path.display())),
    };
    let changed = current.as_deref() != Some(next.as_str());
    if check {
        return Ok(GeneratedModuleWriteResult {
            changed,
            wrote: false,
            output_path,
        });
    }
    if changed {
        if let Some(parent) = output_path.parent() {
            fs::create_dir_all(parent)
                .map_err(|error| format!("failed to create {}: {error}", parent.display()))?;
        }
        fs::write(&output_path, next)
            .map_err(|error| format!("failed to write {}: {error}", output_path.display()))?;
    }
    Ok(GeneratedModuleWriteResult {
        changed,
        wrote: changed,
        output_path,
    })
}

fn bundled_capability_metadata_payload() -> (
    Vec<BundledCapabilityMetadataEntry>,
    BTreeMap<String, String>,
    BTreeMap<String, String>,
) {
    let mut entries = BTreeMap::<String, BundledCapabilityMetadataEntryBuilder>::new();
    let mut legacy_aliases = BTreeMap::<String, String>::new();
    let mut auto_enable_provider_plugins = BTreeMap::<String, String>::new();

    for metadata in crawclaw_providers::bundled_provider_plugin_contract_metadata() {
        let entry = entries.entry(metadata.plugin_id.clone()).or_default();
        entry.provider_ids.extend(metadata.provider_ids);
        for legacy_plugin_id in metadata.legacy_plugin_ids {
            legacy_aliases.insert(legacy_plugin_id, metadata.plugin_id.clone());
        }
        for provider_id in metadata.auto_enable_when_configured_providers {
            auto_enable_provider_plugins.insert(provider_id, metadata.plugin_id.clone());
        }
    }

    for descriptor in crawclaw_native_plugins::registry::builtin_native_plugin_descriptors() {
        let entry = entries.entry(descriptor.plugin_id.clone()).or_default();
        entry.provider_ids.extend(
            descriptor
                .model_providers
                .into_iter()
                .map(|provider| provider.id),
        );
        entry.web_fetch_provider_ids.extend(
            descriptor
                .web_fetch_providers
                .into_iter()
                .map(|provider| provider.id),
        );
        entry.web_search_provider_ids.extend(
            descriptor
                .web_search_providers
                .into_iter()
                .map(|provider| provider.id),
        );
        entry
            .tool_names
            .extend(descriptor.tools.into_iter().map(|tool| tool.name));
    }

    let snapshots = entries
        .into_iter()
        .map(|(plugin_id, entry)| entry.into_entry(plugin_id))
        .filter(|entry| !entry.is_empty())
        .collect();

    (snapshots, legacy_aliases, auto_enable_provider_plugins)
}

#[derive(Clone, Debug, Default, PartialEq, Eq)]
struct BundledNativeProviderMetadataPayload {
    web_search_providers: Vec<BundledNativeWebProviderMetadataEntry>,
    web_fetch_providers: Vec<BundledNativeWebProviderMetadataEntry>,
    speech_providers: Vec<BundledNativeSpeechProviderMetadataEntry>,
}

fn bundled_native_provider_metadata_payload() -> BundledNativeProviderMetadataPayload {
    let mut payload = BundledNativeProviderMetadataPayload::default();
    for descriptor in crawclaw_native_plugins::registry::builtin_native_plugin_descriptors() {
        let plugin_id = descriptor.plugin_id;
        payload
            .web_search_providers
            .extend(descriptor.web_search_providers.into_iter().map(|provider| {
                BundledNativeWebProviderMetadataEntry {
                    plugin_id: plugin_id.clone(),
                    hint: native_web_provider_hint(&provider.id, &provider.label),
                    onboarding_scopes: vec!["text-inference".to_string()],
                    requires_credential: false,
                    env_vars: native_web_provider_env_vars(&provider.id),
                    placeholder: String::new(),
                    signup_url: WEB_DOCS_URL.to_string(),
                    docs_url: WEB_DOCS_URL.to_string(),
                    invocation: BundledNativeProviderInvocation {
                        plugin_id: provider.invocation.plugin_id,
                        operation: provider.invocation.operation,
                    },
                    id: provider.id,
                    label: provider.label,
                }
            }));
        payload
            .web_fetch_providers
            .extend(descriptor.web_fetch_providers.into_iter().map(|provider| {
                BundledNativeWebProviderMetadataEntry {
                    plugin_id: plugin_id.clone(),
                    hint: native_web_provider_hint(&provider.id, &provider.label),
                    onboarding_scopes: Vec::new(),
                    requires_credential: false,
                    env_vars: native_web_provider_env_vars(&provider.id),
                    placeholder: String::new(),
                    signup_url: WEB_DOCS_URL.to_string(),
                    docs_url: WEB_DOCS_URL.to_string(),
                    invocation: BundledNativeProviderInvocation {
                        plugin_id: provider.invocation.plugin_id,
                        operation: provider.invocation.operation,
                    },
                    id: provider.id,
                    label: provider.label,
                }
            }));
        payload
            .speech_providers
            .extend(descriptor.speech_providers.into_iter().map(|provider| {
                BundledNativeSpeechProviderMetadataEntry {
                    plugin_id: plugin_id.clone(),
                    id: provider.id,
                    label: provider.label,
                    voices: provider.voices,
                    synthesize: BundledNativeProviderInvocation {
                        plugin_id: provider.synthesize.plugin_id,
                        operation: provider.synthesize.operation,
                    },
                }
            }));
    }
    payload.web_search_providers.sort_by(|left, right| {
        left.id
            .cmp(&right.id)
            .then_with(|| left.plugin_id.cmp(&right.plugin_id))
    });
    payload.web_fetch_providers.sort_by(|left, right| {
        left.id
            .cmp(&right.id)
            .then_with(|| left.plugin_id.cmp(&right.plugin_id))
    });
    payload.speech_providers.sort_by(|left, right| {
        left.id
            .cmp(&right.id)
            .then_with(|| left.plugin_id.cmp(&right.plugin_id))
    });
    payload
}

fn native_web_provider_hint(id: &str, label: &str) -> String {
    match id {
        "searxng" => "Use the bundled managed local SearXNG web search provider".to_string(),
        "spider" => {
            "Use the bundled native static HTTP and browser-rendered fetch provider".to_string()
        }
        _ => format!("Use the bundled native {label} provider"),
    }
}

fn native_web_provider_env_vars(id: &str) -> Vec<String> {
    match id {
        "searxng" => vec!["SEARXNG_BASE_URL".to_string()],
        _ => Vec::new(),
    }
}

fn render_bundled_capability_snapshots(entries: &[BundledCapabilityMetadataEntry]) -> String {
    if entries.is_empty() {
        return "[]".to_string();
    }
    let rendered_entries = entries
        .iter()
        .map(|entry| {
            format!(
                "  {{\n    pluginId: {plugin_id},\n    providerIds: {provider_ids},\n    webFetchProviderIds: {web_fetch_provider_ids},\n    webSearchProviderIds: {web_search_provider_ids},\n    toolNames: {tool_names},\n  }},",
                plugin_id = json_string(&entry.plugin_id),
                provider_ids = render_string_array(&entry.provider_ids),
                web_fetch_provider_ids = render_string_array(&entry.web_fetch_provider_ids),
                web_search_provider_ids = render_string_array(&entry.web_search_provider_ids),
                tool_names = render_string_array(&entry.tool_names),
            )
        })
        .collect::<Vec<_>>()
        .join("\n");
    format!("[\n{rendered_entries}\n]")
}

fn render_bundled_native_provider_invocation(
    invocation: &BundledNativeProviderInvocation,
) -> String {
    format!(
        "{{ pluginId: {plugin_id}, operation: {operation} }}",
        plugin_id = json_string(&invocation.plugin_id),
        operation = json_string(&invocation.operation),
    )
}

fn render_bundled_native_web_provider_metadata(
    entries: &[BundledNativeWebProviderMetadataEntry],
) -> String {
    if entries.is_empty() {
        return "[]".to_string();
    }
    let rendered_entries = entries
        .iter()
        .map(|entry| {
            format!(
                "  {{\n    pluginId: {plugin_id},\n    id: {id},\n    label: {label},\n    hint: {hint},\n    onboardingScopes: {onboarding_scopes},\n    requiresCredential: {requires_credential},\n    envVars: {env_vars},\n    placeholder: {placeholder},\n    signupUrl: {signup_url},\n    docsUrl: {docs_url},\n    invocation: {invocation},\n  }},",
                plugin_id = json_string(&entry.plugin_id),
                id = json_string(&entry.id),
                label = json_string(&entry.label),
                hint = json_string(&entry.hint),
                onboarding_scopes = render_string_array(&entry.onboarding_scopes),
                requires_credential = entry.requires_credential,
                env_vars = render_string_array(&entry.env_vars),
                placeholder = json_string(&entry.placeholder),
                signup_url = json_string(&entry.signup_url),
                docs_url = json_string(&entry.docs_url),
                invocation = render_bundled_native_provider_invocation(&entry.invocation),
            )
        })
        .collect::<Vec<_>>()
        .join("\n");
    format!("[\n{rendered_entries}\n]")
}

fn render_bundled_native_speech_provider_metadata(
    entries: &[BundledNativeSpeechProviderMetadataEntry],
) -> String {
    if entries.is_empty() {
        return "[]".to_string();
    }
    let rendered_entries = entries
        .iter()
        .map(|entry| {
            format!(
                "  {{\n    pluginId: {plugin_id},\n    id: {id},\n    label: {label},\n    voices: {voices},\n    synthesize: {synthesize},\n  }},",
                plugin_id = json_string(&entry.plugin_id),
                id = json_string(&entry.id),
                label = json_string(&entry.label),
                voices = render_string_array(&entry.voices),
                synthesize = render_bundled_native_provider_invocation(&entry.synthesize),
            )
        })
        .collect::<Vec<_>>()
        .join("\n");
    format!("[\n{rendered_entries}\n]")
}

fn render_string_record(entries: &BTreeMap<String, String>) -> String {
    if entries.is_empty() {
        return "{}".to_string();
    }
    let rendered_entries = entries
        .iter()
        .map(|(key, value)| {
            format!(
                "  {key}: {value},",
                key = render_javascript_property_key(key),
                value = json_string(value),
            )
        })
        .collect::<Vec<_>>()
        .join("\n");
    format!("{{\n{rendered_entries}\n}}")
}

fn render_static_string_record(entries: &[(&str, &str)]) -> String {
    let entries = entries
        .iter()
        .map(|(key, value)| ((*key).to_string(), (*value).to_string()))
        .collect::<BTreeMap<_, _>>();
    render_string_record(&entries)
}

fn render_provider_auth_env_var_record(
    entries: &[crawclaw_providers::ProviderAuthEnvVars],
) -> String {
    if entries.is_empty() {
        return "{}".to_string();
    }
    let mut entries = entries.to_vec();
    entries.sort_by(|left, right| left.provider.cmp(right.provider));
    let rendered_entries = entries
        .iter()
        .map(|entry| {
            let rendered_key = render_javascript_property_key(entry.provider);
            let rendered_env_vars = entry
                .env_vars
                .iter()
                .map(|value| serde_json::to_string(value).expect("env var encodes as JSON"))
                .collect::<Vec<_>>()
                .join(", ");
            format!("  {rendered_key}: [{rendered_env_vars}],")
        })
        .collect::<Vec<_>>()
        .join("\n");
    format!("{{\n{rendered_entries}\n}}")
}

fn render_u32_record(entries: &BTreeMap<String, u32>) -> String {
    if entries.is_empty() {
        return "{}".to_string();
    }
    let rendered_entries = entries
        .iter()
        .map(|(key, value)| {
            format!(
                "  {key}: {value},",
                key = render_javascript_property_key(key),
            )
        })
        .collect::<Vec<_>>()
        .join("\n");
    format!("{{\n{rendered_entries}\n}}")
}

fn render_static_u32_record(entries: &[(&str, u32)]) -> String {
    let entries = entries
        .iter()
        .map(|(key, value)| ((*key).to_string(), *value))
        .collect::<BTreeMap<_, _>>();
    render_u32_record(&entries)
}

fn render_provider_model_default_cost(
    cost: crawclaw_providers::ProviderModelDefaultCost,
) -> String {
    format!(
        "{{\n  input: {input},\n  output: {output},\n  cacheRead: {cache_read},\n  cacheWrite: {cache_write},\n}}",
        input = cost.input,
        output = cost.output,
        cache_read = cost.cache_read,
        cache_write = cost.cache_write,
    )
}

fn render_default_provider_capabilities(
    capabilities: crawclaw_providers::ProviderCapabilitiesDefault,
) -> String {
    format!(
        "{{\n  anthropicToolSchemaMode: {anthropic_tool_schema_mode},\n  anthropicToolChoiceMode: {anthropic_tool_choice_mode},\n  openAiPayloadNormalizationMode: {open_ai_payload_normalization_mode},\n  providerFamily: {provider_family},\n  preserveAnthropicThinkingSignatures: {preserve_anthropic_thinking_signatures},\n  openAiCompatTurnValidation: {open_ai_compat_turn_validation},\n  geminiThoughtSignatureSanitization: {gemini_thought_signature_sanitization},\n  transcriptToolCallIdMode: {transcript_tool_call_id_mode},\n  transcriptToolCallIdModelHints: {transcript_tool_call_id_model_hints},\n  geminiThoughtSignatureModelHints: {gemini_thought_signature_model_hints},\n  dropThinkingBlockModelHints: {drop_thinking_block_model_hints},\n}}",
        anthropic_tool_schema_mode = json_string(capabilities.anthropic_tool_schema_mode),
        anthropic_tool_choice_mode = json_string(capabilities.anthropic_tool_choice_mode),
        open_ai_payload_normalization_mode =
            json_string(capabilities.open_ai_payload_normalization_mode),
        provider_family = json_string(capabilities.provider_family),
        preserve_anthropic_thinking_signatures =
            capabilities.preserve_anthropic_thinking_signatures,
        open_ai_compat_turn_validation = capabilities.open_ai_compat_turn_validation,
        gemini_thought_signature_sanitization = capabilities.gemini_thought_signature_sanitization,
        transcript_tool_call_id_mode = json_string(capabilities.transcript_tool_call_id_mode),
        transcript_tool_call_id_model_hints =
            render_static_string_array_inline(capabilities.transcript_tool_call_id_model_hints),
        gemini_thought_signature_model_hints =
            render_static_string_array_inline(capabilities.gemini_thought_signature_model_hints),
        drop_thinking_block_model_hints =
            render_static_string_array_inline(capabilities.drop_thinking_block_model_hints),
    )
}

fn render_provider_capability_fallbacks(
    entries: &[crawclaw_providers::ProviderCapabilityFallback],
) -> String {
    if entries.is_empty() {
        return "{}".to_string();
    }
    let mut rendered_by_provider = BTreeMap::new();
    for entry in entries {
        rendered_by_provider.insert(
            entry.provider.to_string(),
            render_provider_capability(entry),
        );
    }
    let rendered_entries = rendered_by_provider
        .iter()
        .map(|(provider, rendered)| {
            format!(
                "  {provider}: {rendered},",
                provider = render_javascript_property_key(provider),
            )
        })
        .collect::<Vec<_>>()
        .join("\n");
    format!("{{\n{rendered_entries}\n}}")
}

fn render_provider_capability(entry: &crawclaw_providers::ProviderCapabilityFallback) -> String {
    let mut fields = Vec::new();
    push_optional_string_field(
        &mut fields,
        "anthropicToolSchemaMode",
        entry.anthropic_tool_schema_mode,
    );
    push_optional_string_field(
        &mut fields,
        "anthropicToolChoiceMode",
        entry.anthropic_tool_choice_mode,
    );
    push_optional_string_field(
        &mut fields,
        "openAiPayloadNormalizationMode",
        entry.open_ai_payload_normalization_mode,
    );
    push_optional_string_field(&mut fields, "providerFamily", entry.provider_family);
    push_optional_bool_field(
        &mut fields,
        "preserveAnthropicThinkingSignatures",
        entry.preserve_anthropic_thinking_signatures,
    );
    push_optional_bool_field(
        &mut fields,
        "openAiCompatTurnValidation",
        entry.open_ai_compat_turn_validation,
    );
    push_optional_bool_field(
        &mut fields,
        "geminiThoughtSignatureSanitization",
        entry.gemini_thought_signature_sanitization,
    );
    push_optional_string_field(
        &mut fields,
        "transcriptToolCallIdMode",
        entry.transcript_tool_call_id_mode,
    );
    push_non_empty_string_array_field(
        &mut fields,
        "transcriptToolCallIdModelHints",
        entry.transcript_tool_call_id_model_hints,
    );
    push_non_empty_string_array_field(
        &mut fields,
        "geminiThoughtSignatureModelHints",
        entry.gemini_thought_signature_model_hints,
    );
    push_non_empty_string_array_field(
        &mut fields,
        "dropThinkingBlockModelHints",
        entry.drop_thinking_block_model_hints,
    );
    let rendered_fields = fields.join("\n");
    format!("{{\n{rendered_fields}\n  }}")
}

fn push_optional_string_field(fields: &mut Vec<String>, name: &str, value: Option<&str>) {
    if let Some(value) = value {
        fields.push(format!("    {name}: {},", json_string(value)));
    }
}

fn push_optional_bool_field(fields: &mut Vec<String>, name: &str, value: Option<bool>) {
    if let Some(value) = value {
        fields.push(format!("    {name}: {value},"));
    }
}

fn push_non_empty_string_array_field(fields: &mut Vec<String>, name: &str, values: &[&str]) {
    if values.is_empty() {
        return;
    }
    fields.push(format!(
        "    {name}: {},",
        render_provider_capability_string_array(values)
    ));
}

fn render_provider_capability_string_array(values: &[&str]) -> String {
    let inline = render_static_string_array_inline(values);
    if values.len() <= 2 && inline.len() <= 48 {
        return inline;
    }
    let rendered_values = values
        .iter()
        .map(|value| format!("      {},", json_string(value)))
        .collect::<Vec<_>>()
        .join("\n");
    format!("[\n{rendered_values}\n    ]")
}

fn render_string_array(values: &[String]) -> String {
    if values.is_empty() {
        return "[]".to_string();
    }
    let rendered_values = values
        .iter()
        .map(|value| json_string(value))
        .collect::<Vec<_>>()
        .join(", ");
    format!("[{rendered_values}]")
}

fn render_static_string_array(values: &[&str]) -> String {
    if values.is_empty() {
        return "[]".to_string();
    }
    if values.len() > 1 {
        let rendered_values = values
            .iter()
            .map(|value| format!("  {},", json_string(value)))
            .collect::<Vec<_>>()
            .join("\n");
        return format!("[\n{rendered_values}\n]");
    }
    let rendered_values = values
        .iter()
        .map(|value| json_string(value))
        .collect::<Vec<_>>()
        .join(", ");
    format!("[{rendered_values}]")
}

fn render_static_string_array_inline(values: &[&str]) -> String {
    let rendered_values = values
        .iter()
        .map(|value| json_string(value))
        .collect::<Vec<_>>()
        .join(", ");
    format!("[{rendered_values}]")
}

fn render_javascript_property_key(value: &str) -> String {
    if is_javascript_identifier(value) {
        value.to_string()
    } else {
        json_string(value)
    }
}

fn json_string(value: &str) -> String {
    serde_json::to_string(value).expect("string literal encodes as JSON")
}

fn is_javascript_identifier(value: &str) -> bool {
    let mut chars = value.chars();
    let Some(first) = chars.next() else {
        return false;
    };
    if !(first == '$' || first == '_' || first.is_ascii_alphabetic()) {
        return false;
    }
    chars.all(|ch| ch == '$' || ch == '_' || ch.is_ascii_alphanumeric())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bundled_provider_auth_env_var_module_uses_rust_provider_metadata() {
        let source = render_bundled_provider_auth_env_var_module();
        assert!(source.contains("anthropic: [\"ANTHROPIC_OAUTH_TOKEN\", \"ANTHROPIC_API_KEY\"],"));
        assert!(source.contains(
            "\"github-copilot\": [\"COPILOT_GITHUB_TOKEN\", \"GH_TOKEN\", \"GITHUB_TOKEN\"],"
        ));
        assert!(source.contains("openai: [\"OPENAI_API_KEY\"],"));
        assert!(!source.contains("openai-codex"));
    }

    #[test]
    fn bundled_capability_metadata_module_uses_rust_plugin_metadata() {
        let source = render_bundled_capability_metadata_module();
        assert!(source.contains(r#"pluginId: "openai""#));
        assert!(source.contains(r#"providerIds: ["openai", "openai-codex"]"#));
        assert!(source.contains(r#"pluginId: "searxng""#));
        assert!(source.contains(r#"webSearchProviderIds: ["searxng"]"#));
        assert!(source.contains(r#"pluginId: "spider-fetch""#));
        assert!(source.contains(r#"webFetchProviderIds: ["spider"]"#));
        assert!(source.contains(r#"pluginId: "comfyui""#));
        assert!(source.contains(r#"toolNames: ["comfyui_workflow"]"#));
        assert!(source.contains(r#""minimax-portal-auth": "minimax""#));
        assert!(source.contains(r#""google-gemini-cli": "google""#));
    }

    #[test]
    fn bundled_capability_metadata_module_emits_native_provider_descriptors_from_rust() {
        let source = render_bundled_capability_metadata_module();
        assert!(source.contains("export const BUNDLED_NATIVE_WEB_SEARCH_PROVIDERS"));
        assert!(source.contains("export const BUNDLED_NATIVE_WEB_FETCH_PROVIDERS"));
        assert!(source.contains("export const BUNDLED_NATIVE_SPEECH_PROVIDERS"));
        assert!(source.contains(r#"id: "searxng""#));
        assert!(source.contains(r#"label: "SearXNG""#));
        assert!(
            source.contains(r#"hint: "Use the bundled managed local SearXNG web search provider""#)
        );
        assert!(source.contains(r#"onboardingScopes: ["text-inference"]"#));
        assert!(source.contains(r#"envVars: ["SEARXNG_BASE_URL"]"#));
        assert!(source.contains(r#"invocation: { pluginId: "searxng", operation: "search" }"#));
        assert!(source.contains(r#"id: "spider""#));
        assert!(source.contains(
            r#"hint: "Use the bundled native static HTTP and browser-rendered fetch provider""#
        ));
        assert!(source.contains(r#"docsUrl: "https://docs.crawclaw.ai/tools/web""#));
        assert!(source.contains(r#"invocation: { pluginId: "spider-fetch", operation: "fetch" }"#));
        assert!(source.contains(r#"id: "qwen3-tts""#));
        assert!(source.contains(r#"voices: ["assistant"]"#));
        assert!(
            source.contains(r#"synthesize: { pluginId: "qwen3-tts", operation: "synthesize" }"#)
        );
    }

    #[test]
    fn provider_runtime_constants_module_uses_rust_provider_metadata() {
        let source = render_provider_runtime_constants_module();
        assert!(source.contains("export const CLAUDE_CLI_BACKEND_ID = \"claude-cli\";"));
        assert!(source.contains("export const AGENT_DEFAULT_PROVIDER = \"anthropic\";"));
        assert!(source.contains("export const AGENT_DEFAULT_MODEL = \"claude-opus-4-6\";"));
        assert!(source.contains("export const AGENT_DEFAULT_CONTEXT_TOKENS = 200000;"));
        assert!(source.contains("opus: \"anthropic/claude-opus-4-6\""));
        assert!(source.contains("\"gpt-mini\": \"openai/gpt-5-mini\""));
        assert!(source.contains("\"gemini-flash-lite\": \"google/gemini-3.1-flash-lite-preview\""));
        assert!(source.contains("\"z.ai\": \"zai\""));
        assert!(source.contains("\"aws-bedrock\": \"amazon-bedrock\""));
        assert!(source.contains("doubao: \"volcengine\""));
        assert!(source.contains("\"volcengine-plan\": \"volcengine\""));
        assert!(source.contains("\"byteplus-plan\": \"byteplus\""));
        assert!(source.contains("export const ANTHROPIC_ADAPTIVE_THINKING_MODEL_PATTERN ="));
        assert!(source.contains("\"^claude-(?:opus|sonnet)-4"));
        assert!(source.contains("export const AMAZON_BEDROCK_ADAPTIVE_THINKING_MODEL_PATTERN ="));
        assert!(source.contains("\"claude-(?:opus|sonnet)-4"));
        assert!(source.contains("export const OPENAI_XHIGH_THINKING_MODEL_IDS = ["));
        assert!(source.contains("\"gpt-5.3-codex-spark\""));
        assert!(source.contains("\"gpt-5.2-codex\""));
        assert!(source.contains("export const DEFAULT_MODEL_COST = {"));
        assert!(source.contains("cacheWrite: 0"));
        assert!(source.contains("export const DEFAULT_MODEL_INPUT = [\"text\"] as const;"));
        assert!(source.contains("export const DEFAULT_MODEL_MAX_TOKENS = 8192;"));
        assert!(source.contains("export const PROVIDER_DEFAULT_API_BY_PROVIDER = {"));
        assert!(source.contains("anthropic: \"anthropic-messages\""));
        assert!(source.contains("export const MODEL_APIS = ["));
        assert!(source.contains("\"openai-codex-responses\""));
        assert!(source.contains("\"azure-openai-responses\""));
        assert!(source.contains("export const ANTHROPIC_CONTEXT_1M_MODEL_PREFIXES = ["));
        assert!(source.contains("\"claude-opus-4\""));
        assert!(source.contains("export const ANTHROPIC_CONTEXT_1M_TOKENS = 1048576;"));
        assert!(source.contains("export const DEFAULT_PROVIDER_CAPABILITIES = {"));
        assert!(source.contains("providerFamily: \"default\""));
        assert!(source.contains("export const PROVIDER_CAPABILITY_FALLBACKS = {"));
        assert!(source.contains("kimi: {"));
        assert!(source.contains("anthropicToolSchemaMode: \"openai-functions\""));
        assert!(source.contains("transcriptToolCallIdMode: \"strict9\""));
        assert!(source.contains("\"codestral\""));
        assert!(source.contains("export const CORE_PROVIDER_AUTH_ENV_VAR_CANDIDATES = {"));
        assert!(source.contains("voyage: [\"VOYAGE_API_KEY\"]"));
        assert!(source.contains("export const CORE_PROVIDER_SETUP_ENV_VAR_OVERRIDES = {"));
        assert!(source.contains("anthropic: [\"ANTHROPIC_API_KEY\", \"ANTHROPIC_OAUTH_TOKEN\"]"));
        assert!(source
            .contains("export const EXTRA_PROVIDER_AUTH_ENV_VARS = [\"MINIMAX_CODE_PLAN_KEY\"]"));
        assert!(source.contains("export const MINIMAX_OAUTH_MARKER = \"minimax-oauth\";"));
        assert!(source.contains("export const OAUTH_API_KEY_MARKER_PREFIX = \"oauth:\";"));
        assert!(source.contains("export const OLLAMA_LOCAL_AUTH_MARKER = \"ollama-local\";"));
        assert!(source.contains("export const CUSTOM_LOCAL_AUTH_MARKER = \"custom-local\";"));
        assert!(source
            .contains("export const GCP_VERTEX_CREDENTIALS_MARKER = \"gcp-vertex-credentials\";"));
        assert!(source.contains("export const NON_ENV_SECRETREF_MARKER = \"secretref-managed\";"));
        assert!(source
            .contains("export const SECRETREF_ENV_HEADER_MARKER_PREFIX = \"secretref-env:\";"));
        assert!(source
            .contains("export const AWS_BEDROCK_BEARER_TOKEN_ENV = \"AWS_BEARER_TOKEN_BEDROCK\";"));
        assert!(source.contains("export const AWS_SDK_ENV_MARKERS = ["));
        assert!(source.contains("\"AWS_PROFILE\""));
        assert!(source.contains("export const LEGACY_ENV_API_KEY_MARKERS = ["));
        assert!(source.contains("\"AZURE_OPENAI_API_KEY\""));
        assert!(source.contains("export const ANTHROPIC_PROVIDER_ID = \"anthropic\";"));
        assert!(source.contains("export const AMAZON_BEDROCK_PROVIDER_ID = \"amazon-bedrock\";"));
        assert!(source.contains("export const GITHUB_COPILOT_PROVIDER_ID = \"github-copilot\";"));
        assert!(source.contains("export const GOOGLE_PROVIDER_ID = \"google\";"));
        assert!(source.contains("export const GOOGLE_VERTEX_PROVIDER_ID = \"google-vertex\";"));
        assert!(source.contains("export const GROQ_PROVIDER_ID = \"groq\";"));
        assert!(source.contains("export const MINIMAX_PROVIDER_ID = \"minimax\";"));
        assert!(source.contains("export const MINIMAX_PORTAL_PROVIDER_ID = \"minimax-portal\";"));
        assert!(source.contains("export const MISTRAL_PROVIDER_ID = \"mistral\";"));
        assert!(source.contains("export const MODELSTUDIO_PROVIDER_ID = \"modelstudio\";"));
        assert!(source.contains("export const MOONSHOT_PROVIDER_ID = \"moonshot\";"));
        assert!(source.contains("export const OLLAMA_PROVIDER_ID = \"ollama\";"));
        assert!(source.contains("export const OPENAI_PROVIDER_ID = \"openai\";"));
        assert!(source.contains("export const OPENAI_CODEX_PROVIDER_ID = \"openai-codex\";"));
        assert!(source.contains("export const OPENROUTER_PROVIDER_ID = \"openrouter\";"));
        assert!(source.contains("export const TOGETHER_PROVIDER_ID = \"together\";"));
        assert!(
            source.contains("export const VERCEL_AI_GATEWAY_PROVIDER_ID = \"vercel-ai-gateway\";")
        );
        assert!(source.contains("export const XAI_PROVIDER_ID = \"xai\";"));
        assert!(source.contains("export const ZAI_PROVIDER_ID = \"zai\";"));
        assert!(source.contains("export const ANTHROPIC_API_KEY_ENV = \"ANTHROPIC_API_KEY\";"));
        assert!(
            source.contains("export const ANTHROPIC_OAUTH_TOKEN_ENV = \"ANTHROPIC_OAUTH_TOKEN\";")
        );
        assert!(source.contains("export const PROVIDER_USAGE_LABELS = {"));
        assert!(source.contains("\"openai-codex\": \"Codex\""));
        assert!(source.contains("zai: \"z.ai\""));
        assert!(source.contains("export const PROVIDER_ATTRIBUTION_PRODUCT = \"CrawClaw\";"));
        assert!(source.contains("export const PROVIDER_ATTRIBUTION_ORIGINATOR = \"crawclaw\";"));
        assert!(source.contains(
            "export const PROVIDER_ATTRIBUTION_REFERER_URL = \"https://docs.crawclaw.ai\";"
        ));
        assert!(source.contains(
            "export const OPENROUTER_ATTRIBUTION_DOCS_URL = \"https://openrouter.ai/docs/app-attribution\";"
        ));
        assert!(source.contains("export const OPENROUTER_ATTRIBUTION_CATEGORY = \"cli-agent\";"));
        assert!(source.contains("export const OPENAI_COMPLETIONS_API = \"openai-completions\";"));
        assert!(source.contains("export const OPENAI_RESPONSES_API = \"openai-responses\";"));
        assert!(
            source.contains("export const OPENAI_CODEX_RESPONSES_API = \"openai-codex-responses\";")
        );
        assert!(source.contains(
            "export const OPENAI_AUDIO_TRANSCRIPTIONS_API = \"openai-audio-transcriptions\";"
        ));
        assert!(source.contains("export const ANTHROPIC_MESSAGES_API = \"anthropic-messages\";"));
        assert!(source.contains("export const MODEL_COMPAT_THINKING_FORMATS = ["));
        assert!(source.contains("\"qwen-chat-template\""));
        assert!(source.contains(
            "export const MODEL_COMPAT_MAX_TOKENS_FIELDS = [\"max_completion_tokens\", \"max_tokens\"] as const;"
        ));
        assert!(source.contains("export const MINIMAX_VLM_MODEL_ID = \"MiniMax-VL-01\";"));
        assert!(source.contains("export const MINIMAX_API_HOST_ENV = \"MINIMAX_API_HOST\";"));
        assert!(
            source.contains("export const MINIMAX_DEFAULT_API_HOST = \"https://api.minimax.io\";")
        );
        assert!(source.contains("export const MINIMAX_VLM_API_PATH = \"/v1/coding_plan/vlm\";"));
        assert!(source
            .contains("export const LOCAL_ENDPOINT_HOSTS = [\"localhost\", \"127.0.0.1\", \"::1\", \"[::1]\"] as const;"));
        assert!(source.contains("export const MOONSHOT_NATIVE_BASE_URLS = ["));
        assert!(source.contains("\"https://api.moonshot.ai/v1\""));
        assert!(source.contains("export const MODELSTUDIO_NATIVE_BASE_URLS = ["));
        assert!(source.contains("\"https://dashscope.aliyuncs.com/compatible-mode/v1\""));
        assert!(source.contains(
            "export const OPENAI_RESPONSES_APIS = [\"openai-responses\", \"azure-openai-responses\"] as const;"
        ));
        assert!(source.contains("export const OPENAI_RESPONSES_PROVIDERS = ["));
        assert!(source.contains("\"azure-openai-responses\""));
        assert!(source.contains(
            "export const MOONSHOT_COMPAT_PROVIDERS = [\"moonshot\", \"kimi\"] as const;"
        ));
        assert!(source.contains("export const TRANSCRIPT_OPENAI_MODEL_APIS = ["));
        assert!(source.contains("\"openai-codex-responses\""));
        assert!(source.contains("export const TRANSCRIPT_ANTHROPIC_MODEL_APIS = ["));
        assert!(source.contains("\"bedrock-converse-stream\""));
        assert!(source.contains(
            "export const GOOGLE_MODEL_APIS = [\"google-gemini-cli\", \"google-generative-ai\"] as const;"
        ));
        assert!(source.contains(
            "export const OPENAI_COMPATIBLE_TURN_VALIDATION_API = \"openai-completions\";"
        ));
        assert!(source.contains("export const OPENAI_COMPATIBLE_TOOL_ID_SANITIZATION_APIS = ["));
        assert!(source.contains("\"azure-openai-responses\""));
        assert!(source.contains(
            "export const OPENROUTER_MODELS_API_URL = \"https://openrouter.ai/api/v1/models\";"
        ));
        assert!(source.contains(
            "export const OPENROUTER_DEFAULT_MODEL_REF = \"openrouter/auto\";"
        ));
        assert!(source.contains(
            "export const MODEL_CATALOG_CONFIGURED_PROVIDER_IDS = [\"deepseek\", \"kilocode\", \"ollama\"] as const;"
        ));
        assert!(source.contains("export const OPENROUTER_PRICING_PROVIDER_ALIASES = {"));
        assert!(source.contains("\"openai-codex\": \"openai\""));
        assert!(source.contains("zai: \"z-ai\""));
        assert!(source.contains("export const OPENROUTER_WRAPPER_PROVIDERS = ["));
        assert!(source.contains("\"vercel-ai-gateway\""));
        assert!(source.contains("export const KNOWN_PROVIDER_FAMILIES = {"));
        assert!(source.contains("\"openai-codex\": \"openai-family\""));
        assert!(source.contains("kimi: \"moonshot\""));
        assert!(source.contains("dashscope: \"modelstudio\""));
        assert!(source.contains("\"magistral-small\": 40000"));
        assert!(source.contains("\"mistral-medium-2508\": 8192"));
        assert!(source.contains("export const ANTHROPIC_VERTEX_DEFAULT_REGION = \"global\";"));
        assert!(
            source.contains("export const OLLAMA_DEFAULT_BASE_URL = \"http://127.0.0.1:11434\";")
        );
        assert!(source.contains("export const OLLAMA_DEFAULT_CONTEXT_WINDOW = 128000;"));
        assert!(source.contains("export const OPENAI_DEFAULT_MODEL = \"openai/gpt-5.4\";"));
        assert!(source.contains(
            "export const GOOGLE_GEMINI_DEFAULT_MODEL = \"google/gemini-3.1-pro-preview\";"
        ));
        assert!(source
            .contains("export const OPENCODE_ZEN_DEFAULT_MODEL = \"opencode/claude-opus-4-6\";"));
        assert!(source.contains(
            "export const LEGACY_OPENCODE_ZEN_DEFAULT_MODELS = [\n  \"opencode/claude-opus-4-5\",\n  \"opencode-zen/claude-opus-4-5\",\n] as const;"
        ));
    }
}
