import { i18n } from "../i18n/lib/translate.ts";

const ZH_CN_LITERALS: Record<string, string> = {
  "Chat settings": "聊天设置",
  "Chat model": "聊天模型",
  "Color mode": "颜色模式",
  "Navigation mode": "导航模式",
  Theme: "主题",
  Simple: "简单",
  Advanced: "高级",
  Claw: "Claw",
  Knot: "Knot",
  Dash: "Dash",
  System: "跟随系统",
  Light: "浅色",
  Dark: "深色",
  Telegram: "Telegram",
  Discord: "Discord",
  Signal: "Signal",
  Slack: "Slack",
  WhatsApp: "WhatsApp",
  Matrix: "Matrix",
  Email: "邮箱",
  SMS: "短信",
  "Main Session": "主会话",
  "Subagent:": "子代理：",
  "Cron:": "定时任务：",
  "Cron Job:": "定时任务：",
  "Other Sessions": "其他会话",
  Connected: "已连接",
  Channel: "渠道",
  "Built-in": "内置",
  core: "核心",
  optional: "可选",
  "Tool Access": "工具访问",
  Profile: "配置档",
  Source: "来源",
  Status: "状态",
  unsaved: "未保存",
  "Enable All": "全部启用",
  "Disable All": "全部禁用",
  "Reload Config": "重新加载配置",
  Save: "保存",
  "Saving…": "保存中…",
  "Load the gateway config to adjust tool profiles.": "先加载网关配置，才能调整工具配置档。",
  "This agent is using an explicit allowlist in config. Tool overrides are managed in the Config tab.":
    "这个智能体正在使用配置里的显式允许列表。工具覆盖请到“配置”页处理。",
  "Global tools.allow is set. Agent overrides cannot enable tools that are globally blocked.":
    "已设置全局 tools.allow。被全局阻止的工具不能在这里重新启用。",
  "Loading runtime tool catalog…": "正在加载运行时工具目录…",
  "Could not load runtime tool catalog. Showing built-in fallback list instead.":
    "无法加载运行时工具目录，当前显示内置回退列表。",
  "Available Right Now": "当前可用",
  "Agent Context": "智能体上下文",
  Workspace: "工作区",
  "Primary Model": "主模型",
  "Identity Name": "身份名称",
  "Identity Avatar": "身份头像",
  "Skills Filter": "技能过滤",
  Default: "默认",
  yes: "是",
  no: "否",
  Channels: "渠道",
  "Gateway-wide channel status snapshot.": "网关范围内的渠道状态快照。",
  "Workspace, identity, and model configuration.": "工作区、身份和模型配置。",
  "Refreshing…": "刷新中…",
  Refresh: "刷新",
  "Last refresh": "上次刷新",
  never: "从未",
  "Load channels to see live status.": "加载渠道后可查看实时状态。",
  "No channels found.": "未发现渠道。",
  "no accounts": "无账号",
  connected: "已连接",
  configured: "已配置",
  enabled: "已启用",
  disabled: "已禁用",
  "not configured": "未配置",
  "Setup guide": "设置指南",
  "Open Files tab": "打开文件页",
  Configured: "已配置",
  Linked: "已绑定",
  Running: "运行中",
  "Last start": "上次启动",
  "Last probe": "上次探测",
  "Last connect": "上次连接",
  "Last message": "上一条消息",
  "Auth age": "认证时长",
  "Bot status and channel configuration.": "机器人状态和渠道配置。",
  "Link WhatsApp Web and monitor connection health.": "连接 WhatsApp Web 并查看连接健康状态。",
  "macOS bridge status and channel configuration.": "macOS 桥接状态和渠道配置。",
  "signal-cli status and channel configuration.": "signal-cli 状态和渠道配置。",
  "Base URL": "基础 URL",
  Probe: "探测",
  ok: "正常",
  failed: "失败",
  "Show QR": "显示二维码",
  Relink: "重新绑定",
  "Wait for scan": "等待扫码",
  Logout: "退出登录",
  "Working…": "处理中…",
  "WhatsApp QR": "WhatsApp 二维码",
  Sessions: "会话",
  "Active session keys and per-session overrides.": "活动会话键及每会话覆盖设置。",
  "Global session overrides across the gateway.": "网关范围内的全局会话覆盖设置。",
  Active: "活跃",
  min: "分钟",
  Limit: "限制",
  Global: "全局",
  Unknown: "未知",
  "Loading…": "加载中…",
  "Filter by key, label, kind…": "按键、标签、类型过滤…",
  selected: "已选择",
  Unselect: "取消选择",
  Delete: "删除",
  "Select all on page": "选择本页全部",
  Key: "键",
  Label: "标签",
  Kind: "类型",
  Updated: "更新时间",
  Tokens: "令牌",
  Thinking: "思考",
  Fast: "快速",
  Verbose: "详细",
  Reasoning: "推理",
  "No sessions found.": "未找到会话。",
  "Schema unavailable. Use Raw.": "Schema 不可用，请切换到 Raw。",
  "Channel config schema unavailable.": "渠道配置 Schema 不可用。",
  "Loading config schema…": "正在加载配置 Schema…",
  "1. Start with the basics": "1. 先完成基础设置",
  "Only fill the fields needed to get this channel online.": "先只填写让这个渠道能上线的必要字段。",
  "2. Login and credentials": "2. 登录与凭据",
  "Paste tokens, secrets, app ids, or cookie paths here.":
    "把 token、secret、应用 ID 或 cookie 路径填在这里。",
  "3. Accounts and destinations": "3. 账号与目标位置",
  "Add accounts, pick the default one, and set the target chat or room here.":
    "在这里新增账号、设置默认账号，并填写目标会话或房间。",
  "4. Reply behavior": "4. 回复行为",
  "Adjust how replies stream, mention groups, and behave after delivery.":
    "这里调整流式回复、群组提及，以及消息发出后的行为。",
  "Advanced options (optional)": "高级选项（可选）",
  "Leave this alone unless you know a channel-specific setting needs to change.":
    "如果你不确定，不要动这里。只有明确知道某个渠道专用设置需要修改时再打开。",
  "Unsupported schema node. Use Raw mode.": "这个字段当前不支持可视化编辑，请切换到 Raw 模式处理。",
  "Unsupported array schema. Use Raw mode.":
    "这个数组字段当前不支持可视化编辑，请切换到 Raw 模式处理。",
  "Unsupported type": "不支持的类型",
  "Use Raw mode.": "请改用 Raw 模式。",
  "Structured value (SecretRef) - use Raw mode to edit":
    "这是结构化密文（SecretRef），请切换到 Raw 模式编辑。",
  "Structured value (SecretRef) - edit the config file directly":
    "这是结构化密文（SecretRef），请直接编辑配置文件。",
  "Reset to default": "恢复默认值",
  "Select...": "请选择…",
  "JSON value": "JSON 值",
  item: "项",
  items: "项",
  Add: "添加",
  'No items yet. Click "Add" to create one.': "还没有项目，点击“添加”创建。",
  "Remove item": "删除项目",
  "Custom entries": "自定义条目",
  "Add Entry": "添加条目",
  "No custom entries.": "没有自定义条目。",
  "Remove entry": "删除条目",
  "App Id": "应用 ID",
  "App Secret": "应用密钥",
  "Encrypt Key": "加密 Key",
  "Verification Token": "校验 Token",
  "Default Account": "默认账号",
  "Max Delay Ms": "最大延迟（毫秒）",
  "Min Delay Ms": "最小延迟（毫秒）",
  "Dm History Limit": "私聊历史条数",
  "Dm Policy": "私聊策略",
  "Group Policy": "群聊策略",
  "History Limit": "历史条数",
  "Table Mode": "表格模式",
  "Reply In Thread": "在线程中回复",
  "Require Mention": "需要提及",
  "Typing Indicator": "输入中提示",
  Reactions: "表情回应",
  "Allow From": "允许来源",
  Capabilities: "能力",
  "Chunk Mode": "分块模式",
  "Config Writes": "配置写入",
  "Connection Mode": "连接模式",
  Domain: "域名",
  "Agent Dir Template": "Agent 目录模板",
  "Max Agents": "最大 Agent 数",
  "Workspace Template": "工作区模板",
  "Group Allow From": "群聊允许来源",
  "Group Sender Allow From": "群发送者允许来源",
  "Group Session Scope": "群会话范围",
  "Interval Ms": "间隔（毫秒）",
  Visibility: "可见性",
  "Http Timeout Ms": "HTTP 超时（毫秒）",
  "Media Max Mb": "媒体大小上限（MB）",
  "Reaction Notifications": "表情通知",
  "Render Mode": "渲染模式",
  "Resolve Sender Names": "解析发送者名称",
  "Text Chunk Limit": "文本分块上限",
  Chat: "聊天",
  Doc: "文档",
  Drive: "云盘",
  Perm: "权限",
  Scopes: "作用域",
  Wiki: "知识库",
  "Webhook Host": "Webhook 主机",
  "Webhook Path": "Webhook 路径",
  "Webhook Port": "Webhook 端口",
  escape: "转义",
  strip: "去除",
  ascii: "ASCII",
  simple: "简单",
  open: "开放",
  pairing: "配对",
  allowlist: "白名单",
  length: "按长度",
  newline: "按换行",
  websocket: "WebSocket",
  webhook: "Webhook",
  group: "群级",
  group_sender: "群发送者级",
  group_topic: "群话题级",
  group_topic_sender: "群话题发送者级",
  visible: "可见",
  hidden: "隐藏",
  own: "仅自己",
  all: "全部",
  auto: "自动",
  raw: "原始",
  card: "卡片",
  Reload: "重新加载",
  inherit: "继承",
  "off (explicit)": "关闭（显式）",
  on: "开启",
  full: "完整",
  custom: "自定义",
  "Preview rendered markdown": "预览渲染后的 Markdown",
  "Toggle fullscreen": "切换全屏",
  "Gateway status": "网关状态",
  Workflows: "工作流",
  "Workflow registry, deployment, and execution timeline.": "工作流注册表、发布状态和执行时间线。",
  "Connect to the gateway to load workflows.": "连接网关后才能加载工作流。",
  Registry: "注册表",
  "Search workflows": "搜索工作流",
  "All workflows": "全部工作流",
  "Enabled only": "仅启用",
  "Disabled only": "仅停用",
  "Deployed only": "仅已发布",
  "Approval required only": "仅需审批",
  runs: "次运行",
  "Recent run": "最近运行",
  "Recent Runs": "最近运行",
  "No workflows have been saved yet.": "还没有已保存的工作流。",
  "No executions recorded yet.": "还没有执行记录。",
  Deploy: "发布",
  Republish: "重新发布",
  "Deploying…": "发布中…",
  "Running…": "运行中…",
  Disable: "停用",
  Enable: "启用",
  "Approval required": "需要审批",
  "Auto-run safe": "允许自动运行",
  workspace: "工作区",
  session: "会话",
  Inputs: "输入",
  Outputs: "输出",
  Steps: "步骤",
  "Last run": "最近运行",
  Tags: "标签",
  "No tags": "无标签",
  "Store paths": "存储路径",
  "Spec path": "Spec 路径",
  "Store root": "存储根目录",
  "Spec version": "Spec 版本",
  "Deployment version": "发布版本",
  "Basic changes": "基础变更",
  "Policy changes": "策略变更",
  "Steps added": "新增步骤",
  "Steps updated": "更新步骤",
  Basic: "基础",
  Policy: "策略",
  Before: "变更前",
  After: "变更后",
  added: "已新增",
  removed: "已删除",
  updated: "已更新",
  Compare: "对比",
  Rollback: "回滚",
  "Rollback + Republish": "回滚并重发",
  "Version Rail": "版本轨道",
  "Track spec history and deployment lineage before you change anything.":
    "在修改之前先看清 spec 历史和发布脉络。",
  "Spec Versions": "Spec 历史版本",
  "No versions recorded yet.": "还没有版本记录。",
  Deployments: "发布记录",
  "No deployments recorded yet.": "还没有发布记录。",
  "Change Summary": "变更摘要",
  "Comparing spec": "正在比较 spec",
  "Inspect what changed between the current spec and the selected baseline.":
    "查看当前 spec 与所选基线之间的变化。",
  "No diff loaded yet.": "还没有加载 diff。",
  "No changes detected.": "未检测到变更。",
  "Spec Workbench": "Spec 工作台",
  "Edit the source spec here, then republish to refresh the compiled n8n workflow.":
    "先在这里编辑源 spec，再重新发布刷新编译后的 n8n workflow。",
  "Select a workflow to inspect versions.": "选择一个工作流查看版本。",
  "Select a workflow to edit the source spec.": "选择一个工作流编辑源 spec。",
  Name: "名称",
  Goal: "目标",
  Description: "描述",
  Topology: "拓扑",
  "Inputs JSON": "输入 JSON",
  "Outputs JSON": "输出 JSON",
  "Steps JSON": "步骤 JSON",
  "Save spec": "保存 spec",
  "Reset editor": "重置编辑器",
  "Republishing…": "重新发布中…",
  "Workflow Steps": "工作流步骤",
  "No workflow steps recorded.": "还没有记录到工作流步骤。",
  Prompt: "提示词",
  Path: "路径",
  "Branch group": "分支组",
  Activation: "激活方式",
  "Max active branches": "最大活跃分支数",
  Compensation: "补偿",
  "Compensation status": "补偿状态",
  "Skipped reason": "跳过原因",
  sequential: "顺序",
  conditional: "条件",
  fan_in: "汇合",
  fan_out: "分发",
  skipped: "已跳过",
  "Execution Detail": "执行详情",
  "Resume workflow": "恢复工作流",
  "Resume URL available": "已拿到 Resume URL",
  "Resume is not available yet for this execution.": "当前执行还没有可用的 Resume URL。",
  "Paste plain text or JSON to resume a waiting workflow.":
    "输入纯文本或 JSON，恢复等待中的工作流。",
  "Resuming…": "恢复中…",
  "Refresh status": "刷新状态",
  "Cancel run": "取消运行",
  "Cancelling…": "取消中…",
  Started: "开始时间",
  Ended: "结束时间",
  "Step Timeline": "步骤时间线",
  "No step timeline recorded yet.": "还没有记录到步骤时间线。",
  "Current step": "当前步骤",
  "Waiting for your input or approval before this workflow can continue.":
    "该工作流正在等待你的输入或审批后继续。",
  "Waiting for an external event before this workflow can continue.":
    "该工作流正在等待外部事件后继续。",
  "CrawClaw agent is executing the current workflow step.":
    "CrawClaw 子代理正在执行当前工作流步骤。",
  "Select a run to inspect timeline and state.": "选择一条运行记录查看时间线和状态。",
  "Select a workflow to inspect deployment and runs.": "选择一个工作流查看发布状态和运行记录。",
  "Run Logs": "运行日志",
  "No run logs recorded yet.": "还没有记录到运行日志。",
  "No extra details": "没有额外细节",
  Type: "类型",
  draft: "草稿",
  deployed: "已发布",
  queued: "排队中",
  waiting_input: "等待输入",
  waiting_external: "等待外部事件",
  succeeded: "成功",
  local: "本地",
  "local+n8n": "本地+n8n",
  n8n: "n8n",
  native: "原生",
  service: "服务节点",
  crawclaw_agent: "CrawClaw 子代理",
  human_wait: "人工等待",
  n8n_wait: "n8n 等待",
  "Failed to set model": "设置模型失败",
  "Copy command": "复制命令",
  "Show token": "显示令牌",
  "Hide token": "隐藏令牌",
  "Show password": "显示密码",
  "Hide password": "隐藏密码",
  'No profile set. Click "Edit Profile" to add your name, bio, and avatar.':
    "尚未设置资料。点击“编辑资料”可添加名称、简介和头像。",
  "Profile picture": "资料头像",
  Accounts: "账号",
  unknown: "未知",
  None: "无",
  "No token usage recorded.": "没有记录到令牌使用情况。",
  "Relative share of estimated tokens in this request.": "本次请求中估算令牌占比。",
  "No memory recall diagnostics.": "没有记忆召回诊断信息。",
  "Hit reason": "命中原因",
  "Eviction reason": "淘汰原因",
  "Durable source": "持久来源",
  "Selected items": "选中项",
  "Omitted items": "省略项",
  "No channel streaming decisions recorded.": "没有记录到渠道流式决策。",
  streaming: "流式",
  fallback: "降级",
  account: "账号",
  chat: "聊天",
  span: "跨度",
  parent: "父级",
  "No metrics": "无指标",
  "No section order recorded.": "没有记录到分段顺序。",
  section: "段",
  sections: "段",
  "No hook mutations recorded.": "没有记录到 hook 变更。",
  user: "用户",
  system: "系统",
  replaceSystemPrompt: "替换系统提示",
  clearSystem: "清空系统",
  replaceUserPrompt: "替换用户提示",
  "Runtime Inspect": "运行检查",
  "Timeline, query context, and provider request diagnostics.":
    "时间线、查询上下文与提供方请求诊断。",
  "Use Current Run": "使用当前运行",
  "Load the current run to inspect runtime timeline and context.":
    "加载当前运行以查看时间线和上下文。",
  "No active run is available for agent": "智能体当前没有可用运行",
  "Run ID": "运行 ID",
  "Task ID": "任务 ID",
  "Runtime State": "运行状态",
  Completion: "完成情况",
  Warnings: "警告",
  "Archive Runs": "归档运行",
  Timeline: "时间线",
  "Structured lifecycle and provider/tool/subagent events.":
    "结构化生命周期与 provider/tool/subagent 事件。",
  All: "全部",
  Errors: "错误",
  Decisions: "决策",
  Phases: "阶段",
  "Top event groups in this run.": "本次运行的主要事件分组。",
  Statuses: "状态",
  "Outcome mix across lifecycle events.": "生命周期事件的结果分布。",
  "No explicit statuses.": "没有显式状态。",
  "No timeline events.": "没有时间线事件。",
  Showing: "显示",
  of: "共",
  "events.": "条事件。",
  "Query Context": "查询上下文",
  "Archive-backed context assembly diagnostics.": "基于归档的上下文组装诊断。",
  "Context Hash": "上下文哈希",
  "Archive Run ID": "归档运行 ID",
  "Event ID": "事件 ID",
  "System Sections": "系统分段",
  "Decision Codes": "决策代码",
  "Hook Mutations": "Hook 变更",
  "Memory Recall": "记忆召回",
  "Memory Recall Decision Codes": "记忆召回决策代码",
  "Provider Request": "提供方请求",
  "Final request snapshot derived from query context.": "由查询上下文推导出的最终请求快照。",
  "Prompt Chars": "提示字符数",
  "System Prompt Chars": "系统提示字符数",
  "Estimated Tokens": "估算令牌",
  "Section Tokens by Role": "按角色统计的分段令牌",
  "Tokens by Role": "按角色统计的令牌",
  "Tokens by Type": "按类型统计的令牌",
  "Provider Section Order": "提供方分段顺序",
  "Ordered sections sent into provider materialization.": "发送给 provider 实体化阶段的有序分段。",
  "Inspection and runtime warnings.": "检查与运行时警告。",
  "No warnings.": "没有警告。",
  Refs: "引用",
  "Runtime and archive references for deep debugging.": "供深度调试使用的运行时与归档引用。",
  "Channel Streaming": "渠道流式输出",
  "Recent per-channel streaming decisions captured during runtime.":
    "运行期间捕获的最近渠道流式决策。",
  "Provider model selected": "已选择提供方模型",
  "Auto compaction triggered": "已触发自动压缩",
  "Manual compaction triggered": "已触发手动压缩",
  "Retry compaction triggered": "已触发重试压缩",
  "Prompt cache hit": "提示缓存命中",
  "Prompt cache miss": "提示缓存未命中",
  "Prompt cache write skipped": "已跳过提示缓存写入",
  "Prompt cache written": "已写入提示缓存",
  "Session memory selected": "已选择会话记忆",
  "Durable memory selected": "已选择持久记忆",
  "Durable prefetch hit": "持久预取命中",
  "Durable wait hit": "持久等待命中",
  "Durable pending fallback": "持久等待回退",
  "disabled for thread reply": "线程回复场景已禁用",
  started: "已开始",
  running: "运行中",
  waiting: "等待中",
  done: "完成",
  blocked: "阻塞",
  cancelled: "已取消",
  Details: "详情",
  "Action Feed": "动作流",
  "Inspect current run": "查看当前运行",
  "Inspect run": "查看运行",
  Logs: "日志",
  "Gateway file logs (JSONL).": "网关文件日志（JSONL）。",
  Export: "导出",
  Filter: "筛选",
  "Search logs": "搜索日志",
  "Auto-follow": "自动跟随",
  File: "文件",
  "Log output truncated; showing latest chunk.": "日志输出已截断，当前显示最新片段。",
  "No log entries.": "没有日志条目。",
  Nodes: "节点",
  "Paired devices and live links.": "已配对设备与实时连接。",
  "No nodes found.": "未找到节点。",
  Devices: "设备",
  "Pairing requests + role tokens.": "配对请求与角色令牌。",
  Pending: "待处理",
  Paired: "已配对",
  "No paired devices.": "没有已配对设备。",
  "n/a": "无",
  repair: "修复",
  role: "角色",
  scopes: "作用域",
  requested: "请求于",
  Approve: "批准",
  Reject: "拒绝",
  none: "无",
  revoked: "已吊销",
  active: "激活",
  Rotate: "轮换",
  Revoke: "吊销",
  Streaming: "流式",
  Fallback: "降级",
  Yes: "是",
  No: "否",
  "Last inbound": "最近入站",
  Mode: "模式",
  critical: "严重",
  warnings: "警告",
  "No critical issues": "没有严重问题",
  Snapshots: "快照",
  "Status, health, and heartbeat data.": "状态、健康和心跳数据。",
  "Security audit": "安全审计",
  Run: "运行",
  "for details.": "查看详情。",
  Health: "健康",
  "Last heartbeat": "最近心跳",
  "Manual RPC": "手动 RPC",
  "Send a raw gateway method with JSON params.": "发送带 JSON 参数的原始网关方法。",
  Method: "方法",
  "Select a method…": "选择一个方法…",
  "Params (JSON)": "参数（JSON）",
  Call: "调用",
  Models: "模型",
  "Catalog from models.list.": "来自 models.list 的目录。",
  "Event Log": "事件日志",
  "Latest gateway events.": "最新网关事件。",
  "No events yet.": "还没有事件。",
  "Google Chat": "Google Chat",
  "Chat API webhook status and channel configuration.": "Chat API webhook 状态与渠道配置。",
  Credential: "凭据",
  Audience: "受众",
  "Public Key": "公钥",
  default: "默认",
  "Edit Profile": "编辑资料",
  "Display Name": "显示名称",
  About: "简介",
  Nostr: "Nostr",
  "Decentralized DMs via Nostr relays (NIP-04).": "通过 Nostr relay 的去中心化私信（NIP-04）。",
  iMessage: "iMessage",
  "Socket mode status and channel configuration.": "Socket 模式状态与渠道配置。",
  "Profile picture preview": "资料头像预览",
  Account: "账号",
  Username: "用户名",
  satoshi: "satoshi",
  "Short username (e.g., satoshi)": "简短用户名（例如 satoshi）",
  "Satoshi Nakamoto": "Satoshi Nakamoto",
  "Your full display name": "你的完整显示名称",
  Bio: "简介",
  "Tell people about yourself...": "向别人介绍一下你自己…",
  "A brief bio or description": "简短简介或描述",
  "Avatar URL": "头像 URL",
  "HTTPS URL to your profile picture": "你的头像图片 HTTPS 地址",
  "Banner URL": "横幅 URL",
  "HTTPS URL to a banner image": "横幅图片的 HTTPS 地址",
  Website: "网站",
  "Your personal website": "你的个人网站",
  "NIP-05 Identifier": "NIP-05 标识",
  "you@example.com": "you@example.com",
  "Verifiable identifier (e.g., you@domain.com)": "可验证标识（例如 you@domain.com）",
  "Lightning Address": "闪电地址",
  "you@getalby.com": "you@getalby.com",
  "Lightning address for tips (LUD-16)": "用于打赏的闪电地址（LUD-16）",
  "Saving...": "保存中…",
  "Save & Publish": "保存并发布",
  "Importing...": "导入中…",
  "Import from Relays": "从 Relay 导入",
  "Hide Advanced": "隐藏高级项",
  "Show Advanced": "显示高级项",
  Cancel: "取消",
  "You have unsaved changes": "你有未保存的修改",
  "Exec approvals": "执行审批",
  "Allowlist and approval policy for": "用于以下模式的允许列表与审批策略",
  "Load exec approvals to edit allowlists.": "加载执行审批配置后才能编辑允许列表。",
  "Load approvals": "加载审批",
  Target: "目标",
  "Gateway edits local approvals; node edits the selected node.":
    "Gateway 编辑本地审批，node 编辑所选节点。",
  Host: "宿主",
  Gateway: "网关",
  Node: "节点",
  "Select node": "选择节点",
  "No nodes advertise exec approvals yet.": "还没有节点宣告执行审批能力。",
  Scope: "范围",
  Defaults: "默认值",
  Security: "安全",
  "Default security mode.": "默认安全模式。",
  "Default prompt policy.": "默认提示策略。",
  "Use default": "使用默认值",
  Ask: "询问",
  "Ask fallback": "询问回退",
  "Applied when the UI prompt is unavailable.": "当 UI 提示不可用时应用。",
  "Auto-allow skill CLIs": "自动放行技能 CLI",
  "Allow skill executables listed by the Gateway.": "允许 Gateway 列出的技能可执行文件。",
  "Using default": "使用默认值",
  Override: "覆盖",
  off: "关闭",
  Deny: "拒绝",
  Allowlist: "允许列表",
  Full: "完全开放",
  Off: "关闭",
  "On miss": "未命中时",
  Always: "总是",
  Enabled: "已启用",
  "Case-insensitive glob patterns.": "不区分大小写的 glob 模式。",
  "Add pattern": "添加模式",
  "No allowlist entries yet.": "还没有允许列表条目。",
  "New pattern": "新模式",
  "Last used": "最近使用",
  Pattern: "模式",
};

export function uiLiteral(text: string): string {
  if (i18n.getLocale() !== "zh-CN") {
    return text;
  }
  return ZH_CN_LITERALS[text] ?? text;
}
