import type { TSchema } from "@sinclair/typebox";
import {
  AgentRuntimeCancelParamsSchema,
  AgentRuntimeCancelResultSchema,
  AgentRuntimeCategorySchema,
  AgentRuntimeDetailResultSchema,
  AgentRuntimeGetParamsSchema,
  AgentRuntimeListParamsSchema,
  AgentRuntimeListResultSchema,
  AgentRuntimeRunSchema,
  AgentRuntimeSummaryParamsSchema,
  AgentRuntimeSummaryResultSchema,
} from "./agent-runtime.js";
import {
  AgentEventSchema,
  AgentObservationsListParamsSchema,
  AgentObservationsListResultSchema,
  AgentInspectionSnapshotSchema,
  AgentInspectionTimelineEntrySchema,
  AgentInspectParamsSchema,
  AgentIdentityParamsSchema,
  AgentIdentityResultSchema,
  AgentParamsSchema,
  AgentWaitParamsSchema,
  PollParamsSchema,
  SendParamsSchema,
  WakeParamsSchema,
} from "./agent.js";
import {
  AgentSummarySchema,
  AgentsCreateParamsSchema,
  AgentsCreateResultSchema,
  AgentsDeleteParamsSchema,
  AgentsDeleteResultSchema,
  AgentsFileEntrySchema,
  AgentsFilesGetParamsSchema,
  AgentsFilesGetResultSchema,
  AgentsFilesListParamsSchema,
  AgentsFilesListResultSchema,
  AgentsFilesSetParamsSchema,
  AgentsFilesSetResultSchema,
  AgentsListParamsSchema,
  AgentsListResultSchema,
  AgentsUpdateParamsSchema,
  AgentsUpdateResultSchema,
  ModelChoiceSchema,
  ModelsListParamsSchema,
  ModelsListResultSchema,
  SkillsBinsParamsSchema,
  SkillsBinsResultSchema,
  SkillsInstallParamsSchema,
  SkillsStatusParamsSchema,
  SkillsUpdateParamsSchema,
  ToolCatalogEntrySchema,
  ToolCatalogGroupSchema,
  ToolCatalogProfileSchema,
  ToolsCatalogParamsSchema,
  ToolsCatalogResultSchema,
  ToolsEffectiveEntrySchema,
  ToolsEffectiveGroupSchema,
  ToolsEffectiveParamsSchema,
  ToolsEffectiveResultSchema,
} from "./agents-models-skills.js";
import {
  ChannelsAccountLoginStartParamsSchema,
  ChannelsAccountLoginStartResultSchema,
  ChannelsAccountLoginWaitParamsSchema,
  ChannelsAccountLoginWaitResultSchema,
  ChannelsAccountReconnectParamsSchema,
  ChannelsAccountReconnectResultSchema,
  ChannelsSetupSurfaceParamsSchema,
  ChannelsSetupSurfaceResultSchema,
  ChannelsConfigApplyParamsSchema,
  ChannelsConfigGetParamsSchema,
  ChannelsConfigSchemaParamsSchema,
  ChannelsConfigSchemaResultSchema,
  ChannelsConfigSnapshotSchema,
  ChannelsConfigPatchParamsSchema,
  ChannelsConfigWriteResultSchema,
  ChannelsAccountLogoutParamsSchema,
  ChannelsAccountLogoutResultSchema,
  ChannelsAccountTargetParamsSchema,
  ChannelsAccountVerifyParamsSchema,
  ChannelsAccountVerifyResultSchema,
  ChannelsLogoutParamsSchema,
  TalkConfigParamsSchema,
  TalkConfigResultSchema,
  TalkSpeakParamsSchema,
  TalkSpeakResultSchema,
  ChannelsStatusParamsSchema,
  ChannelsStatusResultSchema,
  TalkModeParamsSchema,
  WebLoginStartParamsSchema,
  WebLoginWaitParamsSchema,
} from "./channels.js";
import {
  ConfigApplyParamsSchema,
  ConfigGetParamsSchema,
  ConfigPatchParamsSchema,
  ConfigSchemaLookupParamsSchema,
  ConfigSchemaLookupResultSchema,
  ConfigSchemaParamsSchema,
  ConfigSchemaResponseSchema,
  ConfigSetParamsSchema,
  UpdateRunParamsSchema,
} from "./config.js";
import {
  CronAddParamsSchema,
  CronJobSchema,
  CronListParamsSchema,
  CronRemoveParamsSchema,
  CronRunLogEntrySchema,
  CronRunParamsSchema,
  CronRunsParamsSchema,
  CronStatusParamsSchema,
  CronUpdateParamsSchema,
} from "./cron.js";
import {
  DevicePairApproveParamsSchema,
  DevicePairListParamsSchema,
  DevicePairRemoveParamsSchema,
  DevicePairRejectParamsSchema,
  DevicePairRequestedEventSchema,
  DevicePairResolvedEventSchema,
  DeviceTokenRevokeParamsSchema,
  DeviceTokenRotateParamsSchema,
} from "./devices.js";
import {
  ExecApprovalsGetParamsSchema,
  ExecApprovalsNodeGetParamsSchema,
  ExecApprovalsNodeSetParamsSchema,
  ExecApprovalsSetParamsSchema,
  ExecApprovalsSnapshotSchema,
  ExecApprovalRequestParamsSchema,
  ExecApprovalResolveParamsSchema,
} from "./exec-approvals.js";
import {
  ConnectParamsSchema,
  ErrorShapeSchema,
  EventFrameSchema,
  GatewayFrameSchema,
  HelloOkSchema,
  RequestFrameSchema,
  ResponseFrameSchema,
  ShutdownEventSchema,
  TickEventSchema,
} from "./frames.js";
import {
  ImprovementDetailResultSchema,
  ImprovementDetailViewSchema,
  ImprovementGetParamsSchema,
  ImprovementListParamsSchema,
  ImprovementListResultSchema,
  ImprovementListViewItemSchema,
  ImprovementMetricsParamsSchema,
  ImprovementMetricsResultSchema,
  ImprovementMutationParamsSchema,
  ImprovementReviewParamsSchema,
  ImprovementRunParamsSchema,
  ImprovementRunResultSchema,
} from "./improvement.js";
import {
  ChatAbortParamsSchema,
  ChatEventSchema,
  ChatHistoryParamsSchema,
  ChatInjectParamsSchema,
  ChatSendParamsSchema,
  LogsTailParamsSchema,
  LogsTailResultSchema,
} from "./logs-chat.js";
import {
  MemoryDreamHistoryResultSchema,
  MemoryDreamRunParamsSchema,
  MemoryDreamRunResultSchema,
  MemoryDreamStatusParamsSchema,
  MemoryDreamStatusResultSchema,
  MemoryDurableIndexEntrySchema,
  MemoryDurableIndexGetParamsSchema,
  MemoryDurableIndexGetResultSchema,
  MemoryDurableIndexListParamsSchema,
  MemoryDurableIndexListResultSchema,
  MemoryLoginParamsSchema,
  MemoryLoginResultSchema,
  MemoryPromptJournalSummaryParamsSchema,
  MemoryPromptJournalSummaryResultSchema,
  MemoryProviderStatusSchema,
  MemoryRefreshParamsSchema,
  MemorySessionSummaryRefreshParamsSchema,
  MemorySessionSummaryRefreshResultSchema,
  MemorySessionSummaryStatusParamsSchema,
  MemorySessionSummaryStatusResultSchema,
  MemoryStatusParamsSchema,
} from "./memory.js";
import {
  NodeDescribeParamsSchema,
  NodeEventParamsSchema,
  NodePendingDrainParamsSchema,
  NodePendingDrainResultSchema,
  NodePendingEnqueueParamsSchema,
  NodePendingEnqueueResultSchema,
  NodeInvokeParamsSchema,
  NodeInvokeResultParamsSchema,
  NodeInvokeRequestEventSchema,
  NodeListParamsSchema,
  NodePendingAckParamsSchema,
  NodePairApproveParamsSchema,
  NodePairListParamsSchema,
  NodePairRejectParamsSchema,
  NodePairRequestParamsSchema,
  NodePairVerifyParamsSchema,
  NodeRenameParamsSchema,
} from "./nodes.js";
import {
  PluginApprovalRequestParamsSchema,
  PluginApprovalResolveParamsSchema,
} from "./plugin-approvals.js";
import {
  PluginsDisableParamsSchema,
  PluginsEnableParamsSchema,
  PluginsInstallParamsSchema,
  PluginsListParamsSchema,
} from "./plugins.js";
import { PushTestParamsSchema, PushTestResultSchema } from "./push.js";
import {
  SecretsReloadParamsSchema,
  SecretsResolveAssignmentSchema,
  SecretsResolveParamsSchema,
  SecretsResolveResultSchema,
} from "./secrets.js";
import {
  SessionsAbortParamsSchema,
  SessionsCompactParamsSchema,
  SessionsCreateParamsSchema,
  SessionsDeleteParamsSchema,
  SessionsListParamsSchema,
  SessionsMessagesSubscribeParamsSchema,
  SessionsMessagesUnsubscribeParamsSchema,
  SessionsPatchParamsSchema,
  SessionsPreviewParamsSchema,
  SessionsResetParamsSchema,
  SessionsResolveParamsSchema,
  SessionsSendParamsSchema,
  SessionsUsageParamsSchema,
} from "./sessions.js";
import { PresenceEntrySchema, SnapshotSchema, StateVersionSchema } from "./snapshot.js";
import {
  CostUsageDailyEntrySchema,
  CostUsageSummarySchema,
  CostUsageTotalsSchema,
  ProviderUsageSnapshotSchema,
  SessionDailyLatencySchema,
  SessionDailyModelUsageSchema,
  SessionLatencyStatsSchema,
  SessionLogEntrySchema,
  SessionMessageCountsSchema,
  SessionModelUsageSchema,
  SessionOriginSchema,
  SessionUsageEntrySchema,
  SessionUsageTimePointSchema,
  SessionToolUsageSchema,
  SessionsUsageAggregatesSchema,
  SessionsUsageLogsParamsSchema,
  SessionsUsageLogsResultSchema,
  SessionsUsageResultSchema,
  SessionsUsageTimeSeriesParamsSchema,
  SessionsUsageTimeSeriesResultSchema,
  UsageCostParamsSchema,
  UsageStatusResultSchema,
  UsageWindowSchema,
} from "./usage.js";
import {
  WizardCancelParamsSchema,
  WizardNextParamsSchema,
  WizardNextResultSchema,
  WizardStartParamsSchema,
  WizardStartResultSchema,
  WizardStatusParamsSchema,
  WizardStatusResultSchema,
  WizardStepSchema,
} from "./wizard.js";
import {
  WorkflowDefinitionDiffSchema,
  WorkflowDeploymentRecordSchema,
  WorkflowDiffParamsSchema,
  WorkflowDiffResultSchema,
  WorkflowExecutionActionResultSchema,
  WorkflowExecutionControlParamsSchema,
  WorkflowExecutionEventRecordSchema,
  WorkflowExecutionStepRecordSchema,
  WorkflowExecutionViewSchema,
  WorkflowExecutionWaitStateSchema,
  WorkflowFieldSpecSchema,
  WorkflowGetParamsSchema,
  WorkflowGetResultSchema,
  WorkflowListEntrySchema,
  WorkflowListParamsSchema,
  WorkflowListResultSchema,
  WorkflowMatchParamsSchema,
  WorkflowMutationParamsSchema,
  WorkflowMutationResultSchema,
  WorkflowN8nGetParamsSchema,
  WorkflowN8nGetResultSchema,
  WorkflowRepublishParamsSchema,
  WorkflowResumeParamsSchema,
  WorkflowRollbackParamsSchema,
  WorkflowRunParamsSchema,
  WorkflowRunsParamsSchema,
  WorkflowRunsResultSchema,
  WorkflowSpecSchema,
  WorkflowStepSpecSchema,
  WorkflowUpdateParamsSchema,
  WorkflowVersionSummarySchema,
  WorkflowVersionsParamsSchema,
  WorkflowVersionsResultSchema,
  WorkflowDeleteParamsSchema,
  WorkflowDeleteResultSchema,
  WorkflowDeployParamsSchema,
} from "./workflow.js";

export const ProtocolSchemas = {
  ConnectParams: ConnectParamsSchema,
  HelloOk: HelloOkSchema,
  RequestFrame: RequestFrameSchema,
  ResponseFrame: ResponseFrameSchema,
  EventFrame: EventFrameSchema,
  GatewayFrame: GatewayFrameSchema,
  PresenceEntry: PresenceEntrySchema,
  StateVersion: StateVersionSchema,
  Snapshot: SnapshotSchema,
  ErrorShape: ErrorShapeSchema,
  AgentEvent: AgentEventSchema,
  AgentObservationsListParams: AgentObservationsListParamsSchema,
  AgentObservationsListResult: AgentObservationsListResultSchema,
  AgentRuntimeCategory: AgentRuntimeCategorySchema,
  AgentRuntimeSummaryParams: AgentRuntimeSummaryParamsSchema,
  AgentRuntimeSummaryResult: AgentRuntimeSummaryResultSchema,
  AgentRuntimeListParams: AgentRuntimeListParamsSchema,
  AgentRuntimeRun: AgentRuntimeRunSchema,
  AgentRuntimeListResult: AgentRuntimeListResultSchema,
  AgentRuntimeGetParams: AgentRuntimeGetParamsSchema,
  AgentRuntimeDetailResult: AgentRuntimeDetailResultSchema,
  AgentRuntimeCancelParams: AgentRuntimeCancelParamsSchema,
  AgentRuntimeCancelResult: AgentRuntimeCancelResultSchema,
  AgentInspectParams: AgentInspectParamsSchema,
  AgentInspectionTimelineEntry: AgentInspectionTimelineEntrySchema,
  AgentInspectionSnapshot: AgentInspectionSnapshotSchema,
  SendParams: SendParamsSchema,
  PollParams: PollParamsSchema,
  AgentParams: AgentParamsSchema,
  AgentIdentityParams: AgentIdentityParamsSchema,
  AgentIdentityResult: AgentIdentityResultSchema,
  AgentWaitParams: AgentWaitParamsSchema,
  WakeParams: WakeParamsSchema,
  NodePairRequestParams: NodePairRequestParamsSchema,
  NodePairListParams: NodePairListParamsSchema,
  NodePairApproveParams: NodePairApproveParamsSchema,
  NodePairRejectParams: NodePairRejectParamsSchema,
  NodePairVerifyParams: NodePairVerifyParamsSchema,
  NodeRenameParams: NodeRenameParamsSchema,
  NodeListParams: NodeListParamsSchema,
  NodePendingAckParams: NodePendingAckParamsSchema,
  NodeDescribeParams: NodeDescribeParamsSchema,
  NodeInvokeParams: NodeInvokeParamsSchema,
  NodeInvokeResultParams: NodeInvokeResultParamsSchema,
  NodeEventParams: NodeEventParamsSchema,
  NodePendingDrainParams: NodePendingDrainParamsSchema,
  NodePendingDrainResult: NodePendingDrainResultSchema,
  NodePendingEnqueueParams: NodePendingEnqueueParamsSchema,
  NodePendingEnqueueResult: NodePendingEnqueueResultSchema,
  NodeInvokeRequestEvent: NodeInvokeRequestEventSchema,
  PushTestParams: PushTestParamsSchema,
  PushTestResult: PushTestResultSchema,
  ImprovementListParams: ImprovementListParamsSchema,
  ImprovementGetParams: ImprovementGetParamsSchema,
  ImprovementRunParams: ImprovementRunParamsSchema,
  ImprovementReviewParams: ImprovementReviewParamsSchema,
  ImprovementMutationParams: ImprovementMutationParamsSchema,
  ImprovementMetricsParams: ImprovementMetricsParamsSchema,
  ImprovementListViewItem: ImprovementListViewItemSchema,
  ImprovementDetailView: ImprovementDetailViewSchema,
  ImprovementListResult: ImprovementListResultSchema,
  ImprovementDetailResult: ImprovementDetailResultSchema,
  ImprovementRunResult: ImprovementRunResultSchema,
  ImprovementMetricsResult: ImprovementMetricsResultSchema,
  SecretsReloadParams: SecretsReloadParamsSchema,
  SecretsResolveParams: SecretsResolveParamsSchema,
  SecretsResolveAssignment: SecretsResolveAssignmentSchema,
  SecretsResolveResult: SecretsResolveResultSchema,
  SessionsListParams: SessionsListParamsSchema,
  SessionsPreviewParams: SessionsPreviewParamsSchema,
  SessionsResolveParams: SessionsResolveParamsSchema,
  SessionsCreateParams: SessionsCreateParamsSchema,
  SessionsSendParams: SessionsSendParamsSchema,
  SessionsMessagesSubscribeParams: SessionsMessagesSubscribeParamsSchema,
  SessionsMessagesUnsubscribeParams: SessionsMessagesUnsubscribeParamsSchema,
  SessionsAbortParams: SessionsAbortParamsSchema,
  SessionsPatchParams: SessionsPatchParamsSchema,
  SessionsResetParams: SessionsResetParamsSchema,
  SessionsDeleteParams: SessionsDeleteParamsSchema,
  SessionsCompactParams: SessionsCompactParamsSchema,
  SessionsUsageParams: SessionsUsageParamsSchema,
  SessionsUsageEntry: SessionUsageEntrySchema,
  SessionsUsageAggregates: SessionsUsageAggregatesSchema,
  SessionsUsageResult: SessionsUsageResultSchema,
  SessionsUsageTimeSeriesParams: SessionsUsageTimeSeriesParamsSchema,
  SessionsUsageTimePoint: SessionUsageTimePointSchema,
  SessionsUsageTimeSeriesResult: SessionsUsageTimeSeriesResultSchema,
  SessionsUsageLogsParams: SessionsUsageLogsParamsSchema,
  SessionLogEntry: SessionLogEntrySchema,
  SessionsUsageLogsResult: SessionsUsageLogsResultSchema,
  ConfigGetParams: ConfigGetParamsSchema,
  ConfigSetParams: ConfigSetParamsSchema,
  ConfigApplyParams: ConfigApplyParamsSchema,
  ConfigPatchParams: ConfigPatchParamsSchema,
  ConfigSchemaParams: ConfigSchemaParamsSchema,
  ConfigSchemaLookupParams: ConfigSchemaLookupParamsSchema,
  ConfigSchemaResponse: ConfigSchemaResponseSchema,
  ConfigSchemaLookupResult: ConfigSchemaLookupResultSchema,
  WizardStartParams: WizardStartParamsSchema,
  WizardNextParams: WizardNextParamsSchema,
  WizardCancelParams: WizardCancelParamsSchema,
  WizardStatusParams: WizardStatusParamsSchema,
  WizardStep: WizardStepSchema,
  WizardNextResult: WizardNextResultSchema,
  WizardStartResult: WizardStartResultSchema,
  WizardStatusResult: WizardStatusResultSchema,
  TalkModeParams: TalkModeParamsSchema,
  TalkConfigParams: TalkConfigParamsSchema,
  TalkConfigResult: TalkConfigResultSchema,
  TalkSpeakParams: TalkSpeakParamsSchema,
  TalkSpeakResult: TalkSpeakResultSchema,
  ChannelsStatusParams: ChannelsStatusParamsSchema,
  ChannelsStatusResult: ChannelsStatusResultSchema,
  ChannelsSetupSurfaceParams: ChannelsSetupSurfaceParamsSchema,
  ChannelsSetupSurfaceResult: ChannelsSetupSurfaceResultSchema,
  ChannelsLogoutParams: ChannelsLogoutParamsSchema,
  ChannelsAccountTargetParams: ChannelsAccountTargetParamsSchema,
  ChannelsAccountLoginStartParams: ChannelsAccountLoginStartParamsSchema,
  ChannelsAccountLoginStartResult: ChannelsAccountLoginStartResultSchema,
  ChannelsAccountLoginWaitParams: ChannelsAccountLoginWaitParamsSchema,
  ChannelsAccountLoginWaitResult: ChannelsAccountLoginWaitResultSchema,
  ChannelsAccountReconnectParams: ChannelsAccountReconnectParamsSchema,
  ChannelsAccountReconnectResult: ChannelsAccountReconnectResultSchema,
  ChannelsConfigGetParams: ChannelsConfigGetParamsSchema,
  ChannelsConfigSnapshot: ChannelsConfigSnapshotSchema,
  ChannelsConfigSchemaParams: ChannelsConfigSchemaParamsSchema,
  ChannelsConfigSchemaResult: ChannelsConfigSchemaResultSchema,
  ChannelsConfigPatchParams: ChannelsConfigPatchParamsSchema,
  ChannelsConfigApplyParams: ChannelsConfigApplyParamsSchema,
  ChannelsConfigWriteResult: ChannelsConfigWriteResultSchema,
  ChannelsAccountVerifyParams: ChannelsAccountVerifyParamsSchema,
  ChannelsAccountVerifyResult: ChannelsAccountVerifyResultSchema,
  ChannelsAccountLogoutParams: ChannelsAccountLogoutParamsSchema,
  ChannelsAccountLogoutResult: ChannelsAccountLogoutResultSchema,
  WebLoginStartParams: WebLoginStartParamsSchema,
  WebLoginWaitParams: WebLoginWaitParamsSchema,
  AgentSummary: AgentSummarySchema,
  AgentsCreateParams: AgentsCreateParamsSchema,
  AgentsCreateResult: AgentsCreateResultSchema,
  AgentsUpdateParams: AgentsUpdateParamsSchema,
  AgentsUpdateResult: AgentsUpdateResultSchema,
  AgentsDeleteParams: AgentsDeleteParamsSchema,
  AgentsDeleteResult: AgentsDeleteResultSchema,
  AgentsFileEntry: AgentsFileEntrySchema,
  AgentsFilesListParams: AgentsFilesListParamsSchema,
  AgentsFilesListResult: AgentsFilesListResultSchema,
  AgentsFilesGetParams: AgentsFilesGetParamsSchema,
  AgentsFilesGetResult: AgentsFilesGetResultSchema,
  AgentsFilesSetParams: AgentsFilesSetParamsSchema,
  AgentsFilesSetResult: AgentsFilesSetResultSchema,
  AgentsListParams: AgentsListParamsSchema,
  AgentsListResult: AgentsListResultSchema,
  ModelChoice: ModelChoiceSchema,
  ModelsListParams: ModelsListParamsSchema,
  ModelsListResult: ModelsListResultSchema,
  SkillsStatusParams: SkillsStatusParamsSchema,
  ToolsCatalogParams: ToolsCatalogParamsSchema,
  ToolCatalogProfile: ToolCatalogProfileSchema,
  ToolCatalogEntry: ToolCatalogEntrySchema,
  ToolCatalogGroup: ToolCatalogGroupSchema,
  ToolsCatalogResult: ToolsCatalogResultSchema,
  ToolsEffectiveParams: ToolsEffectiveParamsSchema,
  ToolsEffectiveEntry: ToolsEffectiveEntrySchema,
  ToolsEffectiveGroup: ToolsEffectiveGroupSchema,
  ToolsEffectiveResult: ToolsEffectiveResultSchema,
  UsageWindow: UsageWindowSchema,
  ProviderUsageSnapshot: ProviderUsageSnapshotSchema,
  UsageStatusResult: UsageStatusResultSchema,
  UsageCostParams: UsageCostParamsSchema,
  CostUsageTotals: CostUsageTotalsSchema,
  CostUsageDailyEntry: CostUsageDailyEntrySchema,
  CostUsageSummary: CostUsageSummarySchema,
  SessionOrigin: SessionOriginSchema,
  SessionMessageCounts: SessionMessageCountsSchema,
  SessionToolUsage: SessionToolUsageSchema,
  SessionModelUsage: SessionModelUsageSchema,
  SessionLatencyStats: SessionLatencyStatsSchema,
  SessionDailyLatency: SessionDailyLatencySchema,
  SessionDailyModelUsage: SessionDailyModelUsageSchema,
  WorkflowFieldSpec: WorkflowFieldSpecSchema,
  WorkflowStepSpec: WorkflowStepSpecSchema,
  WorkflowSpec: WorkflowSpecSchema,
  WorkflowListEntry: WorkflowListEntrySchema,
  WorkflowExecutionStepRecord: WorkflowExecutionStepRecordSchema,
  WorkflowExecutionEventRecord: WorkflowExecutionEventRecordSchema,
  WorkflowExecutionWaitState: WorkflowExecutionWaitStateSchema,
  WorkflowExecutionView: WorkflowExecutionViewSchema,
  WorkflowDeploymentRecord: WorkflowDeploymentRecordSchema,
  WorkflowDefinitionDiff: WorkflowDefinitionDiffSchema,
  WorkflowVersionSummary: WorkflowVersionSummarySchema,
  WorkflowListParams: WorkflowListParamsSchema,
  WorkflowListResult: WorkflowListResultSchema,
  WorkflowGetParams: WorkflowGetParamsSchema,
  WorkflowGetResult: WorkflowGetResultSchema,
  WorkflowMatchParams: WorkflowMatchParamsSchema,
  WorkflowVersionsParams: WorkflowVersionsParamsSchema,
  WorkflowVersionsResult: WorkflowVersionsResultSchema,
  WorkflowDiffParams: WorkflowDiffParamsSchema,
  WorkflowDiffResult: WorkflowDiffResultSchema,
  WorkflowUpdateParams: WorkflowUpdateParamsSchema,
  WorkflowRunsParams: WorkflowRunsParamsSchema,
  WorkflowRunsResult: WorkflowRunsResultSchema,
  WorkflowN8nGetParams: WorkflowN8nGetParamsSchema,
  WorkflowN8nGetResult: WorkflowN8nGetResultSchema,
  WorkflowMutationParams: WorkflowMutationParamsSchema,
  WorkflowMutationResult: WorkflowMutationResultSchema,
  WorkflowDeleteParams: WorkflowDeleteParamsSchema,
  WorkflowDeleteResult: WorkflowDeleteResultSchema,
  WorkflowDeployParams: WorkflowDeployParamsSchema,
  WorkflowRepublishParams: WorkflowRepublishParamsSchema,
  WorkflowRollbackParams: WorkflowRollbackParamsSchema,
  WorkflowRunParams: WorkflowRunParamsSchema,
  WorkflowExecutionControlParams: WorkflowExecutionControlParamsSchema,
  WorkflowExecutionActionResult: WorkflowExecutionActionResultSchema,
  WorkflowResumeParams: WorkflowResumeParamsSchema,
  SkillsBinsParams: SkillsBinsParamsSchema,
  SkillsBinsResult: SkillsBinsResultSchema,
  SkillsInstallParams: SkillsInstallParamsSchema,
  SkillsUpdateParams: SkillsUpdateParamsSchema,
  CronJob: CronJobSchema,
  CronListParams: CronListParamsSchema,
  CronStatusParams: CronStatusParamsSchema,
  CronAddParams: CronAddParamsSchema,
  CronUpdateParams: CronUpdateParamsSchema,
  CronRemoveParams: CronRemoveParamsSchema,
  CronRunParams: CronRunParamsSchema,
  CronRunsParams: CronRunsParamsSchema,
  CronRunLogEntry: CronRunLogEntrySchema,
  LogsTailParams: LogsTailParamsSchema,
  LogsTailResult: LogsTailResultSchema,
  ExecApprovalsGetParams: ExecApprovalsGetParamsSchema,
  ExecApprovalsSetParams: ExecApprovalsSetParamsSchema,
  ExecApprovalsNodeGetParams: ExecApprovalsNodeGetParamsSchema,
  ExecApprovalsNodeSetParams: ExecApprovalsNodeSetParamsSchema,
  ExecApprovalsSnapshot: ExecApprovalsSnapshotSchema,
  MemoryStatusParams: MemoryStatusParamsSchema,
  MemoryRefreshParams: MemoryRefreshParamsSchema,
  MemoryProviderStatus: MemoryProviderStatusSchema,
  MemoryLoginParams: MemoryLoginParamsSchema,
  MemoryLoginResult: MemoryLoginResultSchema,
  MemoryDurableIndexEntry: MemoryDurableIndexEntrySchema,
  MemoryDurableIndexListParams: MemoryDurableIndexListParamsSchema,
  MemoryDurableIndexListResult: MemoryDurableIndexListResultSchema,
  MemoryDurableIndexGetParams: MemoryDurableIndexGetParamsSchema,
  MemoryDurableIndexGetResult: MemoryDurableIndexGetResultSchema,
  MemoryDreamStatusParams: MemoryDreamStatusParamsSchema,
  MemoryDreamStatusResult: MemoryDreamStatusResultSchema,
  MemoryDreamHistoryResult: MemoryDreamHistoryResultSchema,
  MemoryDreamRunParams: MemoryDreamRunParamsSchema,
  MemoryDreamRunResult: MemoryDreamRunResultSchema,
  MemorySessionSummaryStatusParams: MemorySessionSummaryStatusParamsSchema,
  MemorySessionSummaryStatusResult: MemorySessionSummaryStatusResultSchema,
  MemorySessionSummaryRefreshParams: MemorySessionSummaryRefreshParamsSchema,
  MemorySessionSummaryRefreshResult: MemorySessionSummaryRefreshResultSchema,
  MemoryPromptJournalSummaryParams: MemoryPromptJournalSummaryParamsSchema,
  MemoryPromptJournalSummaryResult: MemoryPromptJournalSummaryResultSchema,
  ExecApprovalRequestParams: ExecApprovalRequestParamsSchema,
  ExecApprovalResolveParams: ExecApprovalResolveParamsSchema,
  PluginApprovalRequestParams: PluginApprovalRequestParamsSchema,
  PluginApprovalResolveParams: PluginApprovalResolveParamsSchema,
  PluginsListParams: PluginsListParamsSchema,
  PluginsEnableParams: PluginsEnableParamsSchema,
  PluginsDisableParams: PluginsDisableParamsSchema,
  PluginsInstallParams: PluginsInstallParamsSchema,
  DevicePairListParams: DevicePairListParamsSchema,
  DevicePairApproveParams: DevicePairApproveParamsSchema,
  DevicePairRejectParams: DevicePairRejectParamsSchema,
  DevicePairRemoveParams: DevicePairRemoveParamsSchema,
  DeviceTokenRotateParams: DeviceTokenRotateParamsSchema,
  DeviceTokenRevokeParams: DeviceTokenRevokeParamsSchema,
  DevicePairRequestedEvent: DevicePairRequestedEventSchema,
  DevicePairResolvedEvent: DevicePairResolvedEventSchema,
  ChatHistoryParams: ChatHistoryParamsSchema,
  ChatSendParams: ChatSendParamsSchema,
  ChatAbortParams: ChatAbortParamsSchema,
  ChatInjectParams: ChatInjectParamsSchema,
  ChatEvent: ChatEventSchema,
  UpdateRunParams: UpdateRunParamsSchema,
  TickEvent: TickEventSchema,
  ShutdownEvent: ShutdownEventSchema,
} satisfies Record<string, TSchema>;

export const PROTOCOL_VERSION = 3 as const;
