import PROVIDER_RUNTIME_CONSTANTS_JSON from "../generated/providers/runtime-constants.generated.json" with { type: "json" };

const PROVIDER_RUNTIME_CONSTANTS = PROVIDER_RUNTIME_CONSTANTS_JSON;

export const CLAUDE_CLI_BACKEND_ID = PROVIDER_RUNTIME_CONSTANTS.CLAUDE_CLI_BACKEND_ID;
export const AGENT_DEFAULT_PROVIDER = PROVIDER_RUNTIME_CONSTANTS.AGENT_DEFAULT_PROVIDER;
export const AGENT_DEFAULT_MODEL = PROVIDER_RUNTIME_CONSTANTS.AGENT_DEFAULT_MODEL;
export const AGENT_DEFAULT_CONTEXT_TOKENS = PROVIDER_RUNTIME_CONSTANTS.AGENT_DEFAULT_CONTEXT_TOKENS;
export const AGENT_DEFAULT_MODEL_ALIASES = PROVIDER_RUNTIME_CONSTANTS.AGENT_DEFAULT_MODEL_ALIASES;
export const PROVIDER_ID_ALIASES = PROVIDER_RUNTIME_CONSTANTS.PROVIDER_ID_ALIASES;
export const PROVIDER_AUTH_ID_ALIASES = PROVIDER_RUNTIME_CONSTANTS.PROVIDER_AUTH_ID_ALIASES;
export const ANTHROPIC_ADAPTIVE_THINKING_MODEL_PATTERN =
  PROVIDER_RUNTIME_CONSTANTS.ANTHROPIC_ADAPTIVE_THINKING_MODEL_PATTERN;
export const AMAZON_BEDROCK_ADAPTIVE_THINKING_MODEL_PATTERN =
  PROVIDER_RUNTIME_CONSTANTS.AMAZON_BEDROCK_ADAPTIVE_THINKING_MODEL_PATTERN;
export const OPENAI_XHIGH_THINKING_MODEL_IDS =
  PROVIDER_RUNTIME_CONSTANTS.OPENAI_XHIGH_THINKING_MODEL_IDS;
export const OPENAI_CODEX_XHIGH_THINKING_MODEL_IDS =
  PROVIDER_RUNTIME_CONSTANTS.OPENAI_CODEX_XHIGH_THINKING_MODEL_IDS;
export const GITHUB_COPILOT_XHIGH_THINKING_MODEL_IDS =
  PROVIDER_RUNTIME_CONSTANTS.GITHUB_COPILOT_XHIGH_THINKING_MODEL_IDS;
export const DEFAULT_MODEL_COST = PROVIDER_RUNTIME_CONSTANTS.DEFAULT_MODEL_COST;
export const DEFAULT_MODEL_INPUT = PROVIDER_RUNTIME_CONSTANTS.DEFAULT_MODEL_INPUT as Array<
  "text" | "image"
>;
export const DEFAULT_MODEL_MAX_TOKENS = PROVIDER_RUNTIME_CONSTANTS.DEFAULT_MODEL_MAX_TOKENS;
export const PROVIDER_DEFAULT_API_BY_PROVIDER =
  PROVIDER_RUNTIME_CONSTANTS.PROVIDER_DEFAULT_API_BY_PROVIDER;
export const MODEL_APIS = PROVIDER_RUNTIME_CONSTANTS.MODEL_APIS as [
  "openai-completions",
  "openai-responses",
  "openai-codex-responses",
  "anthropic-messages",
  "google-generative-ai",
  "github-copilot",
  "bedrock-converse-stream",
  "ollama",
  "azure-openai-responses",
];
export const ANTHROPIC_CONTEXT_1M_MODEL_PREFIXES =
  PROVIDER_RUNTIME_CONSTANTS.ANTHROPIC_CONTEXT_1M_MODEL_PREFIXES;
export const ANTHROPIC_CONTEXT_1M_TOKENS = PROVIDER_RUNTIME_CONSTANTS.ANTHROPIC_CONTEXT_1M_TOKENS;
export const DEFAULT_PROVIDER_CAPABILITIES =
  PROVIDER_RUNTIME_CONSTANTS.DEFAULT_PROVIDER_CAPABILITIES;
export const PROVIDER_CAPABILITY_FALLBACKS =
  PROVIDER_RUNTIME_CONSTANTS.PROVIDER_CAPABILITY_FALLBACKS;
export const CORE_PROVIDER_AUTH_ENV_VAR_CANDIDATES =
  PROVIDER_RUNTIME_CONSTANTS.CORE_PROVIDER_AUTH_ENV_VAR_CANDIDATES;
export const CORE_PROVIDER_SETUP_ENV_VAR_OVERRIDES =
  PROVIDER_RUNTIME_CONSTANTS.CORE_PROVIDER_SETUP_ENV_VAR_OVERRIDES;
export const EXTRA_PROVIDER_AUTH_ENV_VARS = PROVIDER_RUNTIME_CONSTANTS.EXTRA_PROVIDER_AUTH_ENV_VARS;
export const MINIMAX_OAUTH_MARKER = PROVIDER_RUNTIME_CONSTANTS.MINIMAX_OAUTH_MARKER;
export const OAUTH_API_KEY_MARKER_PREFIX = PROVIDER_RUNTIME_CONSTANTS.OAUTH_API_KEY_MARKER_PREFIX;
export const OLLAMA_LOCAL_AUTH_MARKER = PROVIDER_RUNTIME_CONSTANTS.OLLAMA_LOCAL_AUTH_MARKER;
export const CUSTOM_LOCAL_AUTH_MARKER = PROVIDER_RUNTIME_CONSTANTS.CUSTOM_LOCAL_AUTH_MARKER;
export const GCP_VERTEX_CREDENTIALS_MARKER =
  PROVIDER_RUNTIME_CONSTANTS.GCP_VERTEX_CREDENTIALS_MARKER;
export const NON_ENV_SECRETREF_MARKER = PROVIDER_RUNTIME_CONSTANTS.NON_ENV_SECRETREF_MARKER;
export const SECRETREF_ENV_HEADER_MARKER_PREFIX =
  PROVIDER_RUNTIME_CONSTANTS.SECRETREF_ENV_HEADER_MARKER_PREFIX;
export const AWS_BEDROCK_BEARER_TOKEN_ENV = PROVIDER_RUNTIME_CONSTANTS.AWS_BEDROCK_BEARER_TOKEN_ENV;
export const AWS_ACCESS_KEY_ID_ENV = PROVIDER_RUNTIME_CONSTANTS.AWS_ACCESS_KEY_ID_ENV;
export const AWS_SECRET_ACCESS_KEY_ENV = PROVIDER_RUNTIME_CONSTANTS.AWS_SECRET_ACCESS_KEY_ENV;
export const AWS_PROFILE_ENV = PROVIDER_RUNTIME_CONSTANTS.AWS_PROFILE_ENV;
export const AWS_SDK_ENV_MARKERS = PROVIDER_RUNTIME_CONSTANTS.AWS_SDK_ENV_MARKERS;
export const LEGACY_ENV_API_KEY_MARKERS = PROVIDER_RUNTIME_CONSTANTS.LEGACY_ENV_API_KEY_MARKERS;
export const ANTHROPIC_PROVIDER_ID = PROVIDER_RUNTIME_CONSTANTS.ANTHROPIC_PROVIDER_ID;
export const ANTHROPIC_VERTEX_PROVIDER_ID = PROVIDER_RUNTIME_CONSTANTS.ANTHROPIC_VERTEX_PROVIDER_ID;
export const AMAZON_BEDROCK_PROVIDER_ID = PROVIDER_RUNTIME_CONSTANTS.AMAZON_BEDROCK_PROVIDER_ID;
export const GITHUB_COPILOT_PROVIDER_ID = PROVIDER_RUNTIME_CONSTANTS.GITHUB_COPILOT_PROVIDER_ID;
export const GOOGLE_PROVIDER_ID = PROVIDER_RUNTIME_CONSTANTS.GOOGLE_PROVIDER_ID;
export const GOOGLE_VERTEX_PROVIDER_ID = PROVIDER_RUNTIME_CONSTANTS.GOOGLE_VERTEX_PROVIDER_ID;
export const GROQ_PROVIDER_ID = PROVIDER_RUNTIME_CONSTANTS.GROQ_PROVIDER_ID;
export const KILOCODE_PROVIDER_ID = PROVIDER_RUNTIME_CONSTANTS.KILOCODE_PROVIDER_ID;
export const MINIMAX_PROVIDER_ID = PROVIDER_RUNTIME_CONSTANTS.MINIMAX_PROVIDER_ID;
export const MINIMAX_PORTAL_PROVIDER_ID = PROVIDER_RUNTIME_CONSTANTS.MINIMAX_PORTAL_PROVIDER_ID;
export const MISTRAL_PROVIDER_ID = PROVIDER_RUNTIME_CONSTANTS.MISTRAL_PROVIDER_ID;
export const MODELSTUDIO_PROVIDER_ID = PROVIDER_RUNTIME_CONSTANTS.MODELSTUDIO_PROVIDER_ID;
export const MOONSHOT_PROVIDER_ID = PROVIDER_RUNTIME_CONSTANTS.MOONSHOT_PROVIDER_ID;
export const OLLAMA_PROVIDER_ID = PROVIDER_RUNTIME_CONSTANTS.OLLAMA_PROVIDER_ID;
export const OPENAI_PROVIDER_ID = PROVIDER_RUNTIME_CONSTANTS.OPENAI_PROVIDER_ID;
export const OPENAI_CODEX_PROVIDER_ID = PROVIDER_RUNTIME_CONSTANTS.OPENAI_CODEX_PROVIDER_ID;
export const OPENROUTER_PROVIDER_ID =
  PROVIDER_RUNTIME_CONSTANTS.OPENROUTER_PROVIDER_ID as "openrouter";
export const TOGETHER_PROVIDER_ID = PROVIDER_RUNTIME_CONSTANTS.TOGETHER_PROVIDER_ID;
export const VERCEL_AI_GATEWAY_PROVIDER_ID =
  PROVIDER_RUNTIME_CONSTANTS.VERCEL_AI_GATEWAY_PROVIDER_ID;
export const XAI_PROVIDER_ID = PROVIDER_RUNTIME_CONSTANTS.XAI_PROVIDER_ID;
export const ZAI_PROVIDER_ID = PROVIDER_RUNTIME_CONSTANTS.ZAI_PROVIDER_ID;
export const ANTHROPIC_API_KEY_ENV = PROVIDER_RUNTIME_CONSTANTS.ANTHROPIC_API_KEY_ENV;
export const ANTHROPIC_OAUTH_TOKEN_ENV = PROVIDER_RUNTIME_CONSTANTS.ANTHROPIC_OAUTH_TOKEN_ENV;
export const ANTHROPIC_VERTEX_USE_GCP_METADATA_ENV =
  PROVIDER_RUNTIME_CONSTANTS.ANTHROPIC_VERTEX_USE_GCP_METADATA_ENV;
export const GOOGLE_APPLICATION_CREDENTIALS_ENV =
  PROVIDER_RUNTIME_CONSTANTS.GOOGLE_APPLICATION_CREDENTIALS_ENV;
export const OAUTH_PROVIDER_AUTH_ENV_VARS = PROVIDER_RUNTIME_CONSTANTS.OAUTH_PROVIDER_AUTH_ENV_VARS;
export const AUTH_COOLDOWN_BYPASS_PROVIDER_IDS =
  PROVIDER_RUNTIME_CONSTANTS.AUTH_COOLDOWN_BYPASS_PROVIDER_IDS;
export const AUTH_WHAM_COOLDOWN_PROBE_PROVIDER_ID =
  PROVIDER_RUNTIME_CONSTANTS.AUTH_WHAM_COOLDOWN_PROBE_PROVIDER_ID;
export const PROVIDER_USAGE_LABELS = PROVIDER_RUNTIME_CONSTANTS.PROVIDER_USAGE_LABELS;
export const PROVIDER_ATTRIBUTION_PRODUCT = PROVIDER_RUNTIME_CONSTANTS.PROVIDER_ATTRIBUTION_PRODUCT;
export const PROVIDER_ATTRIBUTION_ORIGINATOR =
  PROVIDER_RUNTIME_CONSTANTS.PROVIDER_ATTRIBUTION_ORIGINATOR;
export const PROVIDER_ATTRIBUTION_REFERER_URL =
  PROVIDER_RUNTIME_CONSTANTS.PROVIDER_ATTRIBUTION_REFERER_URL;
export const OPENROUTER_ATTRIBUTION_DOCS_URL =
  PROVIDER_RUNTIME_CONSTANTS.OPENROUTER_ATTRIBUTION_DOCS_URL;
export const OPENROUTER_ATTRIBUTION_CATEGORY =
  PROVIDER_RUNTIME_CONSTANTS.OPENROUTER_ATTRIBUTION_CATEGORY;
export const OPENAI_COMPLETIONS_API = PROVIDER_RUNTIME_CONSTANTS.OPENAI_COMPLETIONS_API;
export const OPENAI_RESPONSES_API = PROVIDER_RUNTIME_CONSTANTS.OPENAI_RESPONSES_API;
export const OPENAI_CODEX_RESPONSES_API = PROVIDER_RUNTIME_CONSTANTS.OPENAI_CODEX_RESPONSES_API;
export const OPENAI_AUDIO_TRANSCRIPTIONS_API =
  PROVIDER_RUNTIME_CONSTANTS.OPENAI_AUDIO_TRANSCRIPTIONS_API;
export const ANTHROPIC_MESSAGES_API = PROVIDER_RUNTIME_CONSTANTS.ANTHROPIC_MESSAGES_API;
export const MODEL_COMPAT_THINKING_FORMATS =
  PROVIDER_RUNTIME_CONSTANTS.MODEL_COMPAT_THINKING_FORMATS as [
    "openai",
    "openrouter",
    "zai",
    "zai",
    "qwen",
    "qwen-chat-template",
  ];
export const MODEL_COMPAT_MAX_TOKENS_FIELDS =
  PROVIDER_RUNTIME_CONSTANTS.MODEL_COMPAT_MAX_TOKENS_FIELDS as [
    "max_completion_tokens",
    "max_tokens",
  ];
export const MINIMAX_VLM_MODEL_ID = PROVIDER_RUNTIME_CONSTANTS.MINIMAX_VLM_MODEL_ID;
export const MINIMAX_API_HOST_ENV = PROVIDER_RUNTIME_CONSTANTS.MINIMAX_API_HOST_ENV;
export const MINIMAX_DEFAULT_API_HOST = PROVIDER_RUNTIME_CONSTANTS.MINIMAX_DEFAULT_API_HOST;
export const MINIMAX_VLM_API_PATH = PROVIDER_RUNTIME_CONSTANTS.MINIMAX_VLM_API_PATH;
export const LOCAL_ENDPOINT_HOSTS = PROVIDER_RUNTIME_CONSTANTS.LOCAL_ENDPOINT_HOSTS;
export const MOONSHOT_NATIVE_BASE_URLS = PROVIDER_RUNTIME_CONSTANTS.MOONSHOT_NATIVE_BASE_URLS;
export const MODELSTUDIO_NATIVE_BASE_URLS = PROVIDER_RUNTIME_CONSTANTS.MODELSTUDIO_NATIVE_BASE_URLS;
export const OPENAI_RESPONSES_APIS = PROVIDER_RUNTIME_CONSTANTS.OPENAI_RESPONSES_APIS;
export const OPENAI_RESPONSES_PROVIDERS = PROVIDER_RUNTIME_CONSTANTS.OPENAI_RESPONSES_PROVIDERS;
export const MOONSHOT_COMPAT_PROVIDERS = PROVIDER_RUNTIME_CONSTANTS.MOONSHOT_COMPAT_PROVIDERS;
export const TRANSCRIPT_OPENAI_MODEL_APIS = PROVIDER_RUNTIME_CONSTANTS.TRANSCRIPT_OPENAI_MODEL_APIS;
export const TRANSCRIPT_ANTHROPIC_MODEL_APIS =
  PROVIDER_RUNTIME_CONSTANTS.TRANSCRIPT_ANTHROPIC_MODEL_APIS;
export const GOOGLE_MODEL_APIS = PROVIDER_RUNTIME_CONSTANTS.GOOGLE_MODEL_APIS;
export const OPENAI_COMPATIBLE_TURN_VALIDATION_API =
  PROVIDER_RUNTIME_CONSTANTS.OPENAI_COMPATIBLE_TURN_VALIDATION_API;
export const OPENAI_COMPATIBLE_TOOL_ID_SANITIZATION_APIS =
  PROVIDER_RUNTIME_CONSTANTS.OPENAI_COMPATIBLE_TOOL_ID_SANITIZATION_APIS;
export const OPENROUTER_MODELS_API_URL = PROVIDER_RUNTIME_CONSTANTS.OPENROUTER_MODELS_API_URL;
export const OPENROUTER_DEFAULT_MODEL_REF =
  PROVIDER_RUNTIME_CONSTANTS.OPENROUTER_DEFAULT_MODEL_REF as "openrouter/auto";
export const MODEL_CATALOG_CONFIGURED_PROVIDER_IDS =
  PROVIDER_RUNTIME_CONSTANTS.MODEL_CATALOG_CONFIGURED_PROVIDER_IDS;
export const OPENROUTER_PRICING_PROVIDER_ALIASES =
  PROVIDER_RUNTIME_CONSTANTS.OPENROUTER_PRICING_PROVIDER_ALIASES;
export const OPENROUTER_WRAPPER_PROVIDERS = PROVIDER_RUNTIME_CONSTANTS.OPENROUTER_WRAPPER_PROVIDERS;
export const KNOWN_PROVIDER_FAMILIES = PROVIDER_RUNTIME_CONSTANTS.KNOWN_PROVIDER_FAMILIES;
export const MISTRAL_SAFE_MAX_TOKENS_BY_MODEL =
  PROVIDER_RUNTIME_CONSTANTS.MISTRAL_SAFE_MAX_TOKENS_BY_MODEL;
export const DEFAULT_CLAUDE_CLI_MODEL = PROVIDER_RUNTIME_CONSTANTS.DEFAULT_CLAUDE_CLI_MODEL;
export const ANTHROPIC_VERTEX_DEFAULT_REGION =
  PROVIDER_RUNTIME_CONSTANTS.ANTHROPIC_VERTEX_DEFAULT_REGION;
export const ANTHROPIC_VERTEX_CREDENTIALS_MARKER =
  PROVIDER_RUNTIME_CONSTANTS.ANTHROPIC_VERTEX_CREDENTIALS_MARKER;
export const OLLAMA_DEFAULT_BASE_URL = PROVIDER_RUNTIME_CONSTANTS.OLLAMA_DEFAULT_BASE_URL;
export const OLLAMA_DEFAULT_CONTEXT_WINDOW =
  PROVIDER_RUNTIME_CONSTANTS.OLLAMA_DEFAULT_CONTEXT_WINDOW;
export const OLLAMA_DEFAULT_MAX_TOKENS = PROVIDER_RUNTIME_CONSTANTS.OLLAMA_DEFAULT_MAX_TOKENS;
export const OLLAMA_DEFAULT_MODEL = PROVIDER_RUNTIME_CONSTANTS.OLLAMA_DEFAULT_MODEL;
export const OLLAMA_DEFAULT_EMBEDDING_MODEL =
  PROVIDER_RUNTIME_CONSTANTS.OLLAMA_DEFAULT_EMBEDDING_MODEL;
export const OPENAI_DEFAULT_MODEL = PROVIDER_RUNTIME_CONSTANTS.OPENAI_DEFAULT_MODEL;
export const OPENAI_CODEX_DEFAULT_MODEL = PROVIDER_RUNTIME_CONSTANTS.OPENAI_CODEX_DEFAULT_MODEL;
export const OPENAI_DEFAULT_IMAGE_MODEL = PROVIDER_RUNTIME_CONSTANTS.OPENAI_DEFAULT_IMAGE_MODEL;
export const OPENAI_DEFAULT_AUDIO_TRANSCRIPTION_MODEL =
  PROVIDER_RUNTIME_CONSTANTS.OPENAI_DEFAULT_AUDIO_TRANSCRIPTION_MODEL;
export const OPENAI_DEFAULT_EMBEDDING_MODEL =
  PROVIDER_RUNTIME_CONSTANTS.OPENAI_DEFAULT_EMBEDDING_MODEL;
export const GOOGLE_GEMINI_DEFAULT_MODEL = PROVIDER_RUNTIME_CONSTANTS.GOOGLE_GEMINI_DEFAULT_MODEL;
export const OPENCODE_GO_DEFAULT_MODEL_REF =
  PROVIDER_RUNTIME_CONSTANTS.OPENCODE_GO_DEFAULT_MODEL_REF;
export const OPENCODE_ZEN_DEFAULT_MODEL = PROVIDER_RUNTIME_CONSTANTS.OPENCODE_ZEN_DEFAULT_MODEL;
export const LEGACY_OPENCODE_ZEN_DEFAULT_MODELS =
  PROVIDER_RUNTIME_CONSTANTS.LEGACY_OPENCODE_ZEN_DEFAULT_MODELS;
