#!/usr/bin/env bash
# Install CrawClaw's local Hindsight service from the GitHub-hosted deploy files.

set -euo pipefail

REPO="${CRAWCLAW_REPO:-qianleigood/crawclaw}"
REF="${CRAWCLAW_REF:-main}"
SERVICE_DIR="${CRAWCLAW_HINDSIGHT_HOME:-${HOME}/.crawclaw/hindsight-service}"
API_PORT="${CRAWCLAW_HINDSIGHT_PORT:-8888}"
WEB_PORT="${CRAWCLAW_HINDSIGHT_WEB_PORT:-9999}"
RAW_BASE="https://raw.githubusercontent.com/${REPO}/${REF}"

log() {
  printf '[crawclaw-hindsight] %s\n' "$*"
}

need_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    log "ERROR: missing required command: $1"
    exit 1
  fi
}

download() {
  local path="$1"
  local dest="$2"
  curl -fsSL "${RAW_BASE}/${path}" -o "${dest}"
}

compose() {
  docker compose "$@"
}

wait_for_health() {
  local health_url="http://127.0.0.1:${API_PORT}/health"
  local elapsed=0
  local timeout="${CRAWCLAW_HINDSIGHT_HEALTH_TIMEOUT:-180}"

  log "waiting for Hindsight health at ${health_url}"
  while [ "${elapsed}" -lt "${timeout}" ]; do
    if curl -fsS "${health_url}" >/dev/null 2>&1; then
      log "Hindsight is ready"
      return 0
    fi
    sleep 5
    elapsed=$((elapsed + 5))
  done

  log "ERROR: Hindsight did not become ready within ${timeout}s"
  compose -f "${SERVICE_DIR}/docker-compose.yml" --env-file "${SERVICE_DIR}/.env" logs hindsight | tail -40 || true
  exit 1
}

write_env() {
  local env_path="${SERVICE_DIR}/.env"
  if [ -f "${env_path}" ] && [ "${CRAWCLAW_HINDSIGHT_OVERWRITE_ENV:-0}" != "1" ]; then
    log "keeping existing ${env_path}"
    return
  fi

  cat >"${env_path}" <<EOF
# CrawClaw local Hindsight service.
# Generated by scripts/install-hindsight-service.sh from ${REPO}@${REF}.

HINDSIGHT_API_PORT=${API_PORT}
HINDSIGHT_API_HOST=0.0.0.0
HINDSIGHT_WEB_PORT=${WEB_PORT}

# Chinese-ready defaults that avoid a slow first-run reranker download.
HINDSIGHT_API_EMBEDDINGS_LOCAL_MODEL=${CRAWCLAW_HINDSIGHT_EMBEDDINGS_MODEL:-BAAI/bge-small-en-v1.5}
HINDSIGHT_API_RERANKER_PROVIDER=${CRAWCLAW_HINDSIGHT_RERANKER_PROVIDER:-rrf}
HINDSIGHT_API_TEXT_SEARCH_EXTENSION=${CRAWCLAW_HINDSIGHT_TEXT_SEARCH_EXTENSION:-native}
HINDSIGHT_API_TEXT_SEARCH_EXTENSION_NATIVE_LANGUAGE=${CRAWCLAW_HINDSIGHT_TEXT_SEARCH_LANGUAGE:-simple}

# Optional LLM settings for memory extraction. Export these before running the
# installer or edit this file after installation.
HINDSIGHT_API_LLM_PROVIDER=${CRAWCLAW_HINDSIGHT_LLM_PROVIDER:-}
HINDSIGHT_API_LLM_API_KEY=${CRAWCLAW_HINDSIGHT_LLM_API_KEY:-}
HINDSIGHT_API_LLM_MODEL=${CRAWCLAW_HINDSIGHT_LLM_MODEL:-}
HINDSIGHT_API_LLM_BASE_URL=${CRAWCLAW_HINDSIGHT_LLM_BASE_URL:-}
EOF
  chmod 600 "${env_path}"
}

main() {
  need_command curl
  need_command docker
  if ! docker compose version >/dev/null 2>&1; then
    log "ERROR: Docker Compose v2 is required"
    exit 1
  fi

  mkdir -p "${SERVICE_DIR}"
  log "installing service files into ${SERVICE_DIR}"
  download "deploy/hindsight/docker-compose.yml" "${SERVICE_DIR}/docker-compose.yml"
  write_env

  log "starting Hindsight"
  compose -f "${SERVICE_DIR}/docker-compose.yml" --env-file "${SERVICE_DIR}/.env" up -d
  wait_for_health

  cat <<EOF

CrawClaw Hindsight local service is running.

API: http://127.0.0.1:${API_PORT}
Web: http://127.0.0.1:${WEB_PORT}
Service directory: ${SERVICE_DIR}

Desktop memory policy:
{
  "hindsightEnabled": true,
  "hindsightBaseUrl": "http://127.0.0.1:${API_PORT}",
  "hindsightMode": "local",
  "hindsightManaged": false,
  "hindsightLifecycleStatus": "external"
}

EOF
}

main "$@"
