#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SMOKE_IMAGE="${CRAWCLAW_INSTALL_SMOKE_IMAGE:-${CRAWCLAW_INSTALL_SMOKE_IMAGE:-crawclaw-install-smoke:local}}"
NONROOT_IMAGE="${CRAWCLAW_INSTALL_NONROOT_IMAGE:-${CRAWCLAW_INSTALL_NONROOT_IMAGE:-crawclaw-install-nonroot:local}}"
INSTALL_URL="${CRAWCLAW_INSTALL_URL:-${CRAWCLAW_INSTALL_URL:-https://crawclaw.ai/install.sh}}"
CLI_INSTALL_URL="${CRAWCLAW_INSTALL_CLI_URL:-${CRAWCLAW_INSTALL_CLI_URL:-https://crawclaw.ai/install-cli.sh}}"
SKIP_NONROOT="${CRAWCLAW_INSTALL_SMOKE_SKIP_NONROOT:-${CRAWCLAW_INSTALL_SMOKE_SKIP_NONROOT:-0}}"
SKIP_SMOKE_IMAGE_BUILD="${CRAWCLAW_INSTALL_SMOKE_SKIP_IMAGE_BUILD:-${CRAWCLAW_INSTALL_SMOKE_SKIP_IMAGE_BUILD:-0}}"
SKIP_NONROOT_IMAGE_BUILD="${CRAWCLAW_INSTALL_NONROOT_SKIP_IMAGE_BUILD:-${CRAWCLAW_INSTALL_NONROOT_SKIP_IMAGE_BUILD:-0}}"
DOCKER_NETWORK="${CRAWCLAW_INSTALL_SMOKE_DOCKER_NETWORK:-${CRAWCLAW_INSTALL_SMOKE_DOCKER_NETWORK:-}}"
LOCAL_INSTALL_SCRIPT="${CRAWCLAW_INSTALL_LOCAL_SCRIPT:-${CRAWCLAW_INSTALL_LOCAL_SCRIPT:-}}"
LATEST_DIR="$(mktemp -d)"
LATEST_FILE="${LATEST_DIR}/latest"
DOCKER_NETWORK_ARGS=()
if [[ -n "$DOCKER_NETWORK" ]]; then
  DOCKER_NETWORK_ARGS=(--network "$DOCKER_NETWORK")
fi
DOCKER_INSTALL_MOUNTS=()
if [[ -n "$LOCAL_INSTALL_SCRIPT" ]]; then
  LOCAL_INSTALL_SCRIPT_PATH="$ROOT_DIR/$LOCAL_INSTALL_SCRIPT"
  if [[ ! -f "$LOCAL_INSTALL_SCRIPT_PATH" ]]; then
    echo "local installer script not found: $LOCAL_INSTALL_SCRIPT_PATH" >&2
    exit 1
  fi
  DOCKER_INSTALL_MOUNTS=(-v "$LOCAL_INSTALL_SCRIPT_PATH:/tmp/crawclaw-install.sh:ro")
fi

if [[ "$SKIP_SMOKE_IMAGE_BUILD" == "1" ]]; then
  echo "==> Reuse prebuilt smoke image: $SMOKE_IMAGE"
else
  echo "==> Build smoke image (upgrade, root): $SMOKE_IMAGE"
  docker build \
    -t "$SMOKE_IMAGE" \
    -f "$ROOT_DIR/scripts/docker/install-sh-smoke/Dockerfile" \
    "$ROOT_DIR/scripts/docker"
fi

echo "==> Run installer smoke test (root): $INSTALL_URL"
docker run --rm -t \
  "${DOCKER_NETWORK_ARGS[@]}" \
  "${DOCKER_INSTALL_MOUNTS[@]}" \
  -v "${LATEST_DIR}:/out" \
  -e CRAWCLAW_INSTALL_URL="$INSTALL_URL" \
  -e CRAWCLAW_INSTALL_URL="$INSTALL_URL" \
  -e CRAWCLAW_INSTALL_METHOD=npm \
  -e CRAWCLAW_INSTALL_METHOD=npm \
  -e CRAWCLAW_INSTALL_LATEST_OUT="/out/latest" \
  -e CRAWCLAW_INSTALL_LATEST_OUT="/out/latest" \
  -e CRAWCLAW_INSTALL_SMOKE_PREVIOUS="${CRAWCLAW_INSTALL_SMOKE_PREVIOUS:-${CRAWCLAW_INSTALL_SMOKE_PREVIOUS:-}}" \
  -e CRAWCLAW_INSTALL_SMOKE_PREVIOUS="${CRAWCLAW_INSTALL_SMOKE_PREVIOUS:-${CRAWCLAW_INSTALL_SMOKE_PREVIOUS:-}}" \
  -e CRAWCLAW_INSTALL_SMOKE_SKIP_PREVIOUS="${CRAWCLAW_INSTALL_SMOKE_SKIP_PREVIOUS:-${CRAWCLAW_INSTALL_SMOKE_SKIP_PREVIOUS:-0}}" \
  -e CRAWCLAW_INSTALL_SMOKE_SKIP_PREVIOUS="${CRAWCLAW_INSTALL_SMOKE_SKIP_PREVIOUS:-${CRAWCLAW_INSTALL_SMOKE_SKIP_PREVIOUS:-0}}" \
  -e CRAWCLAW_DISABLE_RUNTIME_POSTINSTALL="${CRAWCLAW_DISABLE_RUNTIME_POSTINSTALL:-${CRAWCLAW_DISABLE_RUNTIME_POSTINSTALL:-}}" \
  -e CRAWCLAW_NPM_SILENT="${CRAWCLAW_NPM_SILENT:-${CRAWCLAW_NPM_SILENT:-1}}" \
  -e CRAWCLAW_NO_ONBOARD=1 \
  -e CRAWCLAW_NO_ONBOARD=1 \
  -e DEBIAN_FRONTEND=noninteractive \
  "$SMOKE_IMAGE"

LATEST_VERSION=""
if [[ -f "$LATEST_FILE" ]]; then
  LATEST_VERSION="$(cat "$LATEST_FILE")"
fi

if [[ "$SKIP_NONROOT" == "1" ]]; then
  echo "==> Skip non-root installer smoke (CRAWCLAW_INSTALL_SMOKE_SKIP_NONROOT=1)"
else
  if [[ "$SKIP_NONROOT_IMAGE_BUILD" == "1" ]]; then
    echo "==> Reuse prebuilt non-root image: $NONROOT_IMAGE"
  else
    echo "==> Build non-root image: $NONROOT_IMAGE"
    docker build \
      -t "$NONROOT_IMAGE" \
      -f "$ROOT_DIR/scripts/docker/install-sh-nonroot/Dockerfile" \
      "$ROOT_DIR/scripts/docker"
  fi

  echo "==> Run installer non-root test: $INSTALL_URL"
  docker run --rm -t \
    "${DOCKER_NETWORK_ARGS[@]}" \
    "${DOCKER_INSTALL_MOUNTS[@]}" \
    -e CRAWCLAW_INSTALL_URL="$INSTALL_URL" \
    -e CRAWCLAW_INSTALL_URL="$INSTALL_URL" \
    -e CRAWCLAW_INSTALL_METHOD=npm \
    -e CRAWCLAW_INSTALL_METHOD=npm \
    -e CRAWCLAW_INSTALL_EXPECT_VERSION="$LATEST_VERSION" \
    -e CRAWCLAW_INSTALL_EXPECT_VERSION="$LATEST_VERSION" \
    -e CRAWCLAW_DISABLE_RUNTIME_POSTINSTALL="${CRAWCLAW_DISABLE_RUNTIME_POSTINSTALL:-${CRAWCLAW_DISABLE_RUNTIME_POSTINSTALL:-}}" \
    -e CRAWCLAW_NPM_SILENT="${CRAWCLAW_NPM_SILENT:-${CRAWCLAW_NPM_SILENT:-1}}" \
    -e CRAWCLAW_NO_ONBOARD=1 \
    -e CRAWCLAW_NO_ONBOARD=1 \
    -e DEBIAN_FRONTEND=noninteractive \
    "$NONROOT_IMAGE"
fi

if [[ "${CRAWCLAW_INSTALL_SMOKE_SKIP_CLI:-${CRAWCLAW_INSTALL_SMOKE_SKIP_CLI:-0}}" == "1" ]]; then
  echo "==> Skip CLI installer smoke (CRAWCLAW_INSTALL_SMOKE_SKIP_CLI=1)"
  exit 0
fi

if [[ "$SKIP_NONROOT" == "1" ]]; then
  echo "==> Skip CLI installer smoke (non-root image skipped)"
  exit 0
fi

echo "==> Run CLI installer non-root test (same image)"
docker run --rm -t \
  "${DOCKER_NETWORK_ARGS[@]}" \
  "${DOCKER_INSTALL_MOUNTS[@]}" \
  --entrypoint /bin/bash \
  -e CRAWCLAW_INSTALL_URL="$INSTALL_URL" \
  -e CRAWCLAW_INSTALL_URL="$INSTALL_URL" \
  -e CRAWCLAW_INSTALL_CLI_URL="$CLI_INSTALL_URL" \
  -e CRAWCLAW_INSTALL_CLI_URL="$CLI_INSTALL_URL" \
  -e CRAWCLAW_DISABLE_RUNTIME_POSTINSTALL="${CRAWCLAW_DISABLE_RUNTIME_POSTINSTALL:-${CRAWCLAW_DISABLE_RUNTIME_POSTINSTALL:-}}" \
  -e CRAWCLAW_NPM_SILENT="${CRAWCLAW_NPM_SILENT:-${CRAWCLAW_NPM_SILENT:-1}}" \
  -e CRAWCLAW_NO_ONBOARD=1 \
  -e CRAWCLAW_NO_ONBOARD=1 \
  -e DEBIAN_FRONTEND=noninteractive \
  "$NONROOT_IMAGE" -lc "curl --retry 5 --retry-delay 3 --retry-all-errors --connect-timeout 20 -fsSL \"$CLI_INSTALL_URL\" | bash -s -- --set-npm-prefix --no-onboard"
