use std::fs;
use std::path::{Path, PathBuf};

pub struct DesktopContractWriteResult {
    pub changed: bool,
    pub output_path: PathBuf,
    pub wrote: bool,
}

pub fn desktop_api_contract_source() -> &'static str {
    DESKTOP_API_CONTRACT_SOURCE
}

pub fn write_desktop_api_contract(
    output_path: &Path,
    check: bool,
) -> Result<DesktopContractWriteResult, String> {
    let next = desktop_api_contract_source();
    let current = fs::read_to_string(output_path).unwrap_or_default();
    let changed = current != next;

    if changed && !check {
        if let Some(parent) = output_path.parent() {
            fs::create_dir_all(parent)
                .map_err(|error| format!("failed to create {}: {error}", parent.display()))?;
        }
        fs::write(output_path, next)
            .map_err(|error| format!("failed to write {}: {error}", output_path.display()))?;
    }

    Ok(DesktopContractWriteResult {
        changed,
        output_path: output_path.to_path_buf(),
        wrote: changed && !check,
    })
}

const DESKTOP_API_CONTRACT_SOURCE: &str = r#"// Generated by `crawclaw-desktop emit-desktop-api-contract`.
// Source of truth: apps/crawclaw-desktop/src-tauri/src/models.rs and Rust desktop API request DTOs.
// Do not edit by hand.

export type RuntimeStatusValue = 'missing' | 'checking' | 'ready' | 'error'
export type PermissionStatus = 'pending' | 'approved' | 'denied'
export type BadgeTone = 'danger' | 'idle' | 'neutral' | 'ok'
export type DesktopIconKey =
  | 'blocks'
  | 'bot'
  | 'brain'
  | 'clock3'
  | 'fileText'
  | 'image'
  | 'messageCircle'
  | 'search'
  | 'sparkles'
  | 'squarePen'
  | 'wrench'

export interface RuntimeStatus {
  status: RuntimeStatusValue
  detail: string
  runtimeRoot: string
  binaryPath?: string
  compat?: {
    mode: 'none'
    detail: string
  }
}

export interface DesktopAppInfo {
  name: string
  version: string
}

export interface DesktopApiInfo {
  baseUrl: string
  eventsUrl: string
  sessionToken: string
}

export interface DesktopState {
  activeNavId: string
  sidebar: SidebarState
  conversation: ConversationState
  agentWorkspace: AgentWorkspaceState
  memoryWorkspace: MemoryWorkspaceState
  pluginsWorkspace: PluginsWorkspaceState
  preferences: DesktopPreferences
  permissionRequest: PermissionRequest
  searchSuggestions: SearchSuggestion[]
}

export interface SidebarState {
  navItems: NavItemData[]
  pinnedThreads: SidebarThreadData[]
  threads: SidebarThreadData[]
  discussionThreads: SidebarThreadData[]
}

export interface NavItemData {
  id: string
  label: string
  icon: DesktopIconKey
}

export interface SidebarThreadData {
  id: string
  title: string
  time: string
  active: boolean
  agentAvatar: boolean
}

export type ConversationMessage =
  | { kind: 'user'; id: string; text: string; createdAt: string }
  | { kind: 'assistant'; id: string; text: string; status?: 'running' | 'done' | 'cancelled' | 'failed'; runId?: string; errorCode?: string; createdAt: string }
  | { kind: 'toolCall'; id: string; toolId: string; title: string; detail?: string; createdAt: string }
  | { kind: 'toolResult'; id: string; toolId: string; title: string; ok: boolean; text: string; createdAt: string }
  | { kind: 'permission'; id: string; requestId: string; title: string; detail: string; status: PermissionStatus; createdAt: string }
  | { kind: 'status'; id: string; title: string; detail: string; tone: BadgeTone; createdAt: string }
  | { kind: 'attachment'; id: string; title: string; fileName: string; mediaType: string; assetId?: string; sizeBytes?: number; status?: string; errorCode?: string; detail?: string; createdAt: string }
  | { kind: 'media'; id: string; mediaType: string; title: string; items: ConversationMediaItem[]; status?: string; errorCode?: string; createdAt: string }
  | { kind: 'workflow'; id: string; workflowKind: string; title: string; status: string; detail: string; steps: ConversationWorkflowStep[]; workflowId?: string; runId?: string; errorCode?: string; createdAt: string }
  | { kind: 'voice'; id: string; direction: string; title: string; durationLabel: string; assetId?: string; mimeType?: string; sizeBytes?: number; status?: string; errorCode?: string; transcript?: string; createdAt: string }
  | { kind: 'skillCall'; id: string; skillId: string; title: string; status: string; executionId?: string; errorCode?: string; detail?: string; createdAt: string }
  | { kind: 'error'; id: string; code: string; title: string; detail: string; createdAt: string }

export interface ConversationMediaItem {
  id: string
  label: string
  kind: string
  assetId?: string
  mimeType?: string
  sizeBytes?: number
  status?: string
  detail?: string
}

export interface ConversationWorkflowStep {
  id: string
  label: string
  status: string
}

export interface ConversationState {
  messages: ConversationMessage[]
  resultItems: string[]
  runtimeChecks: RuntimeCheck[]
  slashCommands: CommandSuggestion[]
  skillCommands: SkillSuggestion[]
  draftMessages: DraftMessage[]
  contextSummary?: ConversationContextSummary
}

export interface ConversationContextSummary {
  profileKind: string
  parentContextPolicy: string
  agentDefinition?: string
  projectedMessageCount: number
  projectedHistoryEstimatedTokens: number
  projectedToolResultCount: number
  projectedToolResultOmittedChars: number
  projectionReason: string
  budgetState: string
  overflowRetryEnabled: boolean
  includedTools: string[]
  deferredTools: string[]
  deferredToolCount: number
  activatedTools: string[]
  surfacedSkills: ConversationContextSkillSummary[]
  loadedSkills: string[]
  loadedSkillCount: number
  memorySnippets: string[]
  memorySnippetCount: number
  compactionActive: boolean
  compactSummaryApplied: boolean
  compactedThrough?: string
  firstKeptMessageId?: string
  tailStartMessageId?: string
  retainedMessageCount: number
  warnings: string[]
  messageCount: number
  estimatedTokens: number
}

export interface ConversationContextSkillSummary {
  name: string
  description: string
}

export interface RuntimeCheck {
  label: string
  value: string
  tone: BadgeTone
}

export interface CommandSuggestion {
  id: string
  label: string
  command: string
  detail: string
  icon: DesktopIconKey
}

export interface SkillSuggestion {
  id: string
  label: string
  mention: string
  detail: string
  icon: DesktopIconKey
}

export interface DraftMessage {
  id: string
  text: string
}

export interface AgentWorkspaceState {
  selectedAgentId: string
  agents: AgentProfile[]
}

export interface AgentProfile {
  id: string
  name: string
  role: string
  description: string
  status: string
  model: string
  thinking: string
  permissionMode: string
  emotion: AgentEmotionProfile
  voice: AgentVoiceConfig
  channels: AgentChannelBinding[]
  avatar: AgentAvatarProfile
  tools: AgentTool[]
  skills: AgentSkill[]
}

export interface AgentEmotionProfile {
  style: string
  tone: string
  boundaries: string[]
  promptMd: string
}

export interface AgentVoiceConfig {
  enabled: boolean
  inputEnabled: boolean
  outputEnabled: boolean
  wakeEnabled: boolean
  source: string
  presetVoice: string
  designPrompt: string
  cloneVoiceName: string
  cloneSampleName: string
  style: string
  pace: string
}

export interface AgentChannelBinding {
  id: string
  label: string
  enabled: boolean
  config?: AgentChannelConfig
}

export interface AgentChannelConfig {
  accountId: string
  dmPolicy: string
  fields: AgentChannelConfigField[]
  groupPolicy: string
  target: string
}

export interface AgentChannelConfigField {
  id: string
  label: string
  secret: boolean
  value: string
}

export interface AgentAvatarProfile {
  initials: string
  gradient: string
  imageDataUrl?: string
  source?: string
}

export interface AgentTool {
  id: string
  name: string
  description: string
  status: string
  permission: string
  icon: DesktopIconKey
  open: boolean
  enabled: boolean
}

export interface AgentSkill {
  id: string
  name: string
  trigger: string
  description: string
  status: string
  source: string
  icon: DesktopIconKey
  open: boolean
  enabled: boolean
}

export type MemoryCategory = '偏好' | '项目' | '经验' | '其他'
export type MemoryFilter = '全部' | MemoryCategory

export interface MemoryWorkspaceState {
  selectedAgentId: string
  selectedItemId: string
  filter: MemoryFilter
  query: string
  dream: MemoryDreamState
  items: MemoryItem[]
}

export interface MemoryDreamState {
  status: 'idle' | 'running' | 'completed' | 'failed'
  agentId: string
  message: string
  lastRunAt: string
}

export interface MemoryItem {
  id: string
  agentId: string
  title: string
  summary: string
  content: string
  category: MemoryCategory
  tags: string[]
  source: string
  updatedAt: string
  archived: boolean
}

export interface CreateMemoryItemInput {
  title: string
  summary: string
  content: string
  category: MemoryCategory
  tags: string[]
  agentId?: string
  source?: string
}

export interface UpdateMemoryItemPatch {
  title?: string
  summary?: string
  content?: string
  category?: MemoryCategory
  tags?: string[]
  source?: string
}

export interface ArchiveMemoryItemInput {
  confirmed?: boolean
}

export interface SendMessageInput {
  text: string
  agentId?: string
}

export type SteerMessageMode = 'restart' | 'followUp'

export interface SteerMessageInput {
  text: string
  mode: SteerMessageMode
}

export type ModelProfileSource = 'builtin' | 'custom'
export type ModelProfileAuthMethod = 'api-key' | 'local' | 'custom'

export interface ModelProfileSetupInput {
  source?: ModelProfileSource
  provider: string
  model: string
  label?: string
  baseUrl?: string
  api?: string
  apiVersion?: string
  apiKey?: string
  authMethod?: ModelProfileAuthMethod
}

export interface AddAttachmentMessageInput {
  title: string
  fileName: string
  mediaType: string
  confirm?: boolean
  detail?: string
  source?: DesktopAssetSource
}

export interface AddMediaMessageInput {
  mediaType: string
  title: string
  confirm?: boolean
  items?: ConversationMediaItem[]
  source?: DesktopAssetSource
  providerConfig?: unknown
}

export interface AddVoiceMessageInput {
  direction: string
  title: string
  durationLabel: string
  prompt?: string
  language?: string
  transcript?: string
  source?: DesktopAssetSource
  providerConfig?: unknown
}

export interface AddWorkflowMessageInput {
  workflowKind: string
  action?: string
  title: string
  confirm?: boolean
  status?: string
  detail?: string
  steps?: ConversationWorkflowStep[]
  input?: unknown
}

export interface AddSkillCallMessageInput {
  skillId: string
  title: string
  status?: string
  detail?: string
  text?: string
  execute?: boolean
}

export interface DesktopAssetSource {
  kind: 'tauriPath' | 'browserFile'
  path?: string
  fileName?: string
  mimeType?: string
  dataBase64?: string
}

export interface CreateAgentInput {
  name: string
  role: string
  description?: string
  model?: string
  thinking?: string
  permissionMode?: string
  emotion?: AgentEmotionProfile
  voice?: AgentVoiceConfig
  channels?: AgentChannelBinding[]
  avatar?: AgentAvatarProfile
  toolIds?: string[]
  skillIds?: string[]
}

export interface UpdateAgentInput {
  name?: string
  role?: string
  description?: string
  status?: string
  model?: string
  thinking?: string
  permissionMode?: string
  emotion?: AgentEmotionProfile
  voice?: AgentVoiceConfig
  channels?: AgentChannelBinding[]
  avatar?: AgentAvatarProfile
  toolIds?: string[]
  skillIds?: string[]
}

export interface AddAgentSkillInput {
  name: string
  trigger: string
  description: string
}

export interface PluginsWorkspaceState {
  tools: PluginTool[]
  skills: PluginSkill[]
  installed: InstalledPlugin[]
}

export interface PluginTool {
  id: string
  pluginId: string
  name: string
  description: string
  status: string
  permission: string
  icon: DesktopIconKey
  enabled: boolean
  source: string
  installStatus: string
  open: boolean
}

export interface PluginSkill {
  id: string
  skillKey: string
  name: string
  trigger: string
  description: string
  status: string
  source: string
  icon: DesktopIconKey
  enabled: boolean
  installStatus: string
  open: boolean
}

export interface InstalledPlugin {
  id: string
  name: string
  status: string
  source: string
  installStatus: string
  enabled: boolean
  version?: string
  manifestPath?: string
  open: boolean
}

export interface AddPluginSkillInput {
  name: string
  trigger: string
  description: string
}

export interface PluginInstallInput {
  source: string
  marketplacePlugin?: string
  link: boolean
  pin: boolean
}

export interface TaskDefaults {
  selectedModel: string
  selectedThinking: string
  permissionMode: string
  responseSpeed: string
  allowTools: boolean
}

export interface ConfirmationDefaults {
  confirmFileChanges: boolean
  confirmCommands: boolean
  confirmExternalApps: boolean
  confirmHighRisk: boolean
}

export interface NotificationDefaults {
  notifyTaskDone: boolean
  notifyConfirmNeeded: boolean
  notifyDreamDone: boolean
  notifyAutomationFailed: boolean
  notificationSound: boolean
}

export interface UiDefaults {
  defaultPage: string
  language: string
  appearance: string
  launchAtLogin: boolean
  showInMenuBar: boolean
}

export interface MemoryDefaults {
  rememberPreferences: boolean
  rememberProjectContext: boolean
  memoryDreamEnabled: boolean
  memoryDreamFrequency: string
  memoryCleanupConfirmation: string
}

export interface PrivacyDefaults {
  dataLocation: string
}

export interface AdvancedDefaults {
  logLevel: string
}

export interface DesktopModelProfileSummary {
  id: string
  label: string
  modelRef: string
  source: ModelProfileSource
  provider: string
  model: string
  authMethod: ModelProfileAuthMethod
  hasCredential: boolean
  baseUrl?: string
  api?: string
  apiVersion?: string
  lastConnectionStatus: string
  lastConnectionDetail?: string
  lastConnectedAt?: string
}

export interface DesktopPreferences {
  selectedModel: string
  selectedThinking: string
  permissionMode: string
  taskDefaults: TaskDefaults
  confirmationDefaults: ConfirmationDefaults
  notificationDefaults: NotificationDefaults
  uiDefaults: UiDefaults
  memoryDefaults: MemoryDefaults
  privacyDefaults: PrivacyDefaults
  advancedDefaults: AdvancedDefaults
  modelOptions: string[]
  modelProfiles: DesktopModelProfileSummary[]
  providerDescriptors: unknown[]
  providerSetupOptions: unknown[]
  providerModelPickerEntries: unknown[]
  webProviderBoundaries: unknown[]
  thinkingOptions: string[]
  permissionModeOptions: string[]
}

export interface PermissionRequest {
  id: string
  title: string
  detail: string
  status: PermissionStatus
}

export interface SearchSuggestion {
  id: string
  label: string
  meta: string
  icon: DesktopIconKey
  targetNavId: string
  targetItemId?: string
}

export type DesktopEvent =
  | { type: 'runtime'; status: RuntimeStatusValue; detail: string }
  | { type: 'runtimeChanged'; runtime: RuntimeStatus }
  | { type: 'sessionStarted'; threadId: string }
  | { type: 'messageDelta'; threadId: string; text: string }
  | { type: 'toolCall'; threadId: string; toolId: string }
  | { type: 'toolResult'; threadId: string; toolId: string; ok: boolean }
  | { type: 'messageFinal'; threadId: string; text: string }
  | { type: 'permissionRequested'; permissionRequest: PermissionRequest }
  | { type: 'operationFailed'; code: string; message: string }
  | { type: 'stateChanged'; desktopState: DesktopState }
  | { type: 'permissionChanged'; permissionRequest: PermissionRequest }

export interface DesktopSessionSummary {
  key: string
  title: string
  pinned: boolean
  status: string
  messageCount: number
  spawnedBy?: string
  yielded: boolean
}

export interface DesktopSessionMessage {
  role: string
  content: string
  source?: string
}

export interface DesktopSessionsResponse {
  sessions: DesktopSessionSummary[]
}

export interface DesktopSessionHistoryResponse {
  sessionKey: string
  messages: DesktopSessionMessage[]
}

export interface DesktopSessionMutationResponse {
  status: string
  session: DesktopSessionSummary
}

export interface DesktopSubagentsResponse {
  subagents: DesktopSessionSummary[]
}

export interface BootstrapResponse {
  app: DesktopAppInfo
  api: DesktopApiInfo
  runtime: RuntimeStatus
  desktopState: DesktopState
}
"#;
