import type { RouteRecordRaw } from 'vue-router'

export const routes: RouteRecordRaw[] = [
  {
    path: '/login',
    name: 'Login',
    component: () => import('@/views/Login.vue'),
    meta: { titleKey: 'routes.login', public: true },
  },
  {
    path: '/',
    component: () => import('@/layouts/DefaultLayout.vue'),
    meta: { requiresAuth: true },
    children: [
      {
        path: '',
        name: 'Dashboard',
        component: () => import('@/views/Dashboard.vue'),
        meta: { titleKey: 'routes.dashboard', icon: 'GridOutline', gateway: 'crawclaw' },
      },
      {
        path: 'chat',
        name: 'Chat',
        component: () => import('@/views/chat/ChatPage.vue'),
        meta: { titleKey: 'routes.chat', icon: 'ChatboxEllipsesOutline', gateway: 'crawclaw' },
      },
      {
        path: 'sessions',
        name: 'Sessions',
        component: () => import('@/views/sessions/SessionsPage.vue'),
        meta: { titleKey: 'routes.sessions', icon: 'ChatbubblesOutline', gateway: 'crawclaw' },
      },
      {
        path: 'sessions/:key',
        name: 'SessionDetail',
        component: () => import('@/views/sessions/SessionDetailPage.vue'),
        meta: { titleKey: 'routes.sessionDetail', hidden: true },
      },
      {
        path: 'memory',
        name: 'Memory',
        component: () => import('@/views/memory/MemoryPage.vue'),
        meta: { titleKey: 'routes.memory', icon: 'BookOutline', gateway: 'crawclaw' },
      },
      {
        path: 'cron',
        name: 'Cron',
        component: () => import('@/views/cron/CronPage.vue'),
        meta: { titleKey: 'routes.cron', icon: 'CalendarOutline', gateway: 'crawclaw' },
      },
      {
        path: 'workflows',
        name: 'Workflows',
        component: () => import('@/views/workflows/WorkflowsPage.vue'),
        meta: { titleKey: 'routes.workflows', icon: 'GitNetworkOutline', gateway: 'crawclaw' },
      },
      {
        path: 'comfyui',
        name: 'ComfyUI',
        component: () => import('@/views/comfyui/ComfyUiPage.vue'),
        meta: { titleKey: 'routes.comfyui', icon: 'ImagesOutline', gateway: 'crawclaw' },
      },
      {
        path: 'models',
        name: 'Models',
        component: () => import('@/views/models/ModelsPage.vue'),
        meta: { titleKey: 'routes.models', icon: 'SparklesOutline', gateway: 'crawclaw' },
      },
      {
        path: 'channels',
        name: 'Channels',
        component: () => import('@/views/channels/ChannelsPage.vue'),
        meta: { titleKey: 'routes.channels', icon: 'GitNetworkOutline', gateway: 'crawclaw' },
      },
      {
        path: 'config',
        redirect: { name: 'Models' },
        meta: { hidden: true },
      },
      {
        path: 'skills',
        name: 'Skills',
        component: () => import('@/views/skills/SkillsPage.vue'),
        meta: { titleKey: 'routes.skills', icon: 'ExtensionPuzzleOutline', gateway: 'crawclaw' },
      },
      {
        path: 'tools',
        redirect: { name: 'Skills' },
        meta: { hidden: true },
      },
      {
        path: 'system',
        name: 'System',
        component: () => import('@/views/system/SystemPage.vue'),
        meta: { titleKey: 'routes.system', icon: 'PulseOutline', gateway: 'crawclaw' },
      },
      {
        path: 'terminal',
        name: 'Terminal',
        component: () => import('@/views/terminal/TerminalPage.vue'),
        meta: { titleKey: 'routes.terminal', icon: 'TerminalOutline', gateway: 'crawclaw' },
      },
      {
        path: 'remote-desktop',
        name: 'RemoteDesktop',
        component: () => import('@/views/remote-desktop/RemoteDesktopPage.vue'),
        meta: { titleKey: 'routes.remoteDesktop', icon: 'DesktopOutline', gateway: 'crawclaw' },
      },
      {
        path: 'files',
        name: 'Files',
        component: () => import('@/views/files/FilesPage.vue'),
        meta: { titleKey: 'routes.files', icon: 'FolderOutline', gateway: 'crawclaw' },
      },
      {
        path: 'agents',
        name: 'Agents',
        component: () => import('@/views/agents/AgentsPage.vue'),
        meta: { titleKey: 'routes.agents', icon: 'PeopleOutline', gateway: 'crawclaw' },
      },
      {
        path: 'office',
        name: 'Office',
        component: () => import('@/views/office/OfficePage.vue'),
        meta: { titleKey: 'routes.office', icon: 'ConstructOutline', gateway: 'crawclaw' },
      },
      {
        path: 'myworld',
        name: 'MyWorld',
        component: () => import('@/views/myworld/MyWorldPage.vue'),
        meta: { titleKey: 'routes.myworld', icon: 'StorefrontOutline', gateway: 'crawclaw' },
      },
      {
        path: 'backup',
        name: 'Backup',
        component: () => import('@/views/backup/BackupPage.vue'),
        meta: { titleKey: 'routes.backup', icon: 'ArchiveOutline', gateway: 'crawclaw' },
      },
      {
        path: 'monitor',
        name: 'Monitor',
        component: () => import('@/views/monitor/MonitorPage.vue'),
        meta: { titleKey: 'routes.monitor', icon: 'PulseOutline', hidden: true },
      },
      {
        path: 'hermes',
        name: 'HermesDashboard',
        component: () => import('@/views/hermes/HermesDashboard.vue'),
        meta: { titleKey: 'routes.hermesDashboard', icon: 'GridOutline', gateway: 'hermes' },
      },
      {
        path: 'hermes/chat',
        name: 'HermesChat',
        component: () => import('@/views/hermes/HermesChatPage.vue'),
        meta: { titleKey: 'routes.hermesChat', icon: 'ChatboxEllipsesOutline', gateway: 'hermes' },
      },
      {
        path: 'hermes/sessions',
        name: 'HermesSessions',
        component: () => import('@/views/hermes/HermesSessionsPage.vue'),
        meta: { titleKey: 'routes.hermesSessions', icon: 'ChatbubblesOutline', gateway: 'hermes' },
      },
      {
        path: 'hermes/models',
        name: 'HermesModels',
        component: () => import('@/views/hermes/HermesModelsPage.vue'),
        meta: { titleKey: 'routes.hermesModels', icon: 'SparklesOutline', gateway: 'hermes' },
      },
      {
        path: 'hermes/channels',
        name: 'HermesChannels',
        component: () => import('@/views/hermes/HermesChannelsPage.vue'),
        meta: { titleKey: 'routes.hermesChannels', icon: 'GitNetworkOutline', gateway: 'hermes' },
      },
      {
        path: 'hermes/skills',
        name: 'HermesSkills',
        component: () => import('@/views/hermes/HermesSkillsPage.vue'),
        meta: { titleKey: 'routes.hermesSkills', icon: 'ExtensionPuzzleOutline', gateway: 'hermes' },
      },
      {
        path: 'hermes/cron',
        name: 'HermesCron',
        component: () => import('@/views/hermes/HermesCronPage.vue'),
        meta: { titleKey: 'routes.hermesCron', icon: 'CalendarOutline', gateway: 'hermes' },
      },
      {
        path: 'hermes/memory',
        name: 'HermesMemory',
        component: () => import('@/views/hermes/HermesMemoryPage.vue'),
        meta: { titleKey: 'routes.hermesMemory', icon: 'BookOutline', gateway: 'hermes' },
      },
      {
        path: 'hermes/cli',
        name: 'HermesCli',
        component: () => import('@/views/hermes/HermesCliPage.vue'),
        meta: { titleKey: 'routes.hermesCli', icon: 'CodeSlashOutline', gateway: 'hermes' },
      },
      {
        path: 'hermes/terminal',
        name: 'HermesTerminal',
        component: () => import('@/views/hermes/HermesTerminalPage.vue'),
        meta: { titleKey: 'routes.hermesTerminal', icon: 'TerminalOutline', gateway: 'hermes' },
      },
      {
        path: 'hermes/remote-desktop',
        name: 'HermesRemoteDesktop',
        component: () => import('@/views/hermes/HermesRemoteDesktopPage.vue'),
        meta: { titleKey: 'routes.hermesRemoteDesktop', icon: 'DesktopOutline', gateway: 'hermes' },
      },
      {
        path: 'hermes/files',
        name: 'HermesFiles',
        component: () => import('@/views/hermes/HermesFilesPage.vue'),
        meta: { titleKey: 'routes.hermesFiles', icon: 'FolderOutline', gateway: 'hermes' },
      },
      {
        path: 'hermes/system',
        name: 'HermesSystem',
        component: () => import('@/views/hermes/HermesSystemPage.vue'),
        meta: { titleKey: 'routes.hermesSystem', icon: 'SettingsOutline', gateway: 'hermes' },
      },
      {
        path: 'settings',
        name: 'Settings',
        component: () => import('@/views/settings/SettingsPage.vue'),
        meta: { titleKey: 'routes.settings', icon: 'CogOutline', gateway: 'crawclaw' },
      },
    ],
  },
]
