// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["browser"];
type FacadeModule = FacadeEntry["module"];
import { loadActivatedBundledPluginPublicSurfaceModuleSync } from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadActivatedBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "browser",
    artifactBasename: "runtime-api.js",
  });
}
export const createBrowserTool: FacadeModule["createBrowserTool"] = ((...args) =>
  loadFacadeModule()["createBrowserTool"](...args)) as FacadeModule["createBrowserTool"];
